# Default values for ghost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for Ghost.
# Default: "1"
replicaCount: ""

# Container images used for Ghost.
image:
  # Ghost container image configurations.
  # Source: https://github.com/sredevopsorg/ghost-on-kubernetes/pkgs/container/ghost-on-kubernetes
  ghost:
    # The registry where the Ghost container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the Ghost container image used.
    # Default: "sredevopsorg/ghost-on-kubernetes"
    repository: ""
    # The tag that specifies the version of the Ghost container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the Ghost container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Init container image configurations.
  # Source: https://hub.docker.com/_/busybox
  init:
    # The registry where the Init container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Init container image used.
    # Default: "busybox"
    repository: ""
    # The tag that specifies the version of the Init container image used.
    # Default: "stable-musl"
    tag: ""
    # The policy that determines when Kubernetes should pull the Init container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# Ghost configurations.
ghost:
  # Specifies whether Ghost should run in debug mode.
  # Default: "false"
  # Example:
  # debug: "true"
  debug: ""
  # The ingress domain name that hosts the Ghost server.
  # Default: "localhost"
  # Example:
  # domain: "ghost.example.com"
  domain: ""
  # The runtime environment for the Ghost server.
  # Default: "production"
  # Example:
  # environment: "development"
  environment: ""
  # The directory where Ghost is installed on the container.
  # Default: "/home/nonroot/app/ghost"
  # Example:
  # install_dir: "/opt/app/ghost"
  install_dir: ""
  # Custom init script to run before the Ghost container starts.
  # Example:
  # initScript: >-
  #   echo "Hello, World!"
  #   echo "This is a custom init script."
  initScript: ""

# Mail configurations.
mail:
  # Specifies whether email support should be enabled for Ghost.
  # Example:
  # enabled: true
  enabled: false
  # The email address used as the "from" address for sent emails.
  # Default: "${.smtp.user}"
  # Example:
  # from_email: "Example User <no-reply@example.com>"
  from_email: ""
  # Specifies whether Ghost should use a secure TLS connection when sending emails.
  # Note: In most cases, set this to true if the SMTP port is 465 (SSL) and false if you are using port 587 (TLS) or 25 (SSL/TLS).
  # Default: "true"
  # Example
  # secure: "false"
  secure: ""
  # The email service provider used for sending emails.
  # Default: "Google"
  # Example:
  # service: "Mailgun"
  service: ""
  # SMTP server configurations.
  smtp:
    # The hostname or IP address of the SMTP server for sending emails.
    # Default: "smtp.gmail.com"
    # Example:
    # host: "smtp.mail.yahoo.com"
    host: ""
    # The port number on the SMTP server used for sending emails.
    # Default: "465"
    # Example:
    # port: "587"
    port: ""
    # The username for authenticating with the SMTP server.
    # Example:
    # user: "ghost@example.com"
    user: ""
    # The password for authenticating with the SMTP server.
    # Example:
    # password: "password"
    password: ""

# Database configurations.
db:
  # The database engine or backend being used by Ghost.
  # Default: "mysql"
  # Example:
  # type: "postgresql"
  type: ""
  # The hostname or IP address of the Ghost database server.
  # Example:
  # host: "ghost.default.svc.cluster.local"
  host: ""
  # The port number the Ghost database server is listening for connections.
  # Default: "3306"
  # Example:
  # port: "5432"
  port: ""
  # The name of the database being used by Ghost.
  # Example:
  # name: "ghost"
  name: ""
  # The username or user account for accessing the Ghost database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the Ghost database user.
  # Example:
  # password: "password"
  password: ""

# Ingress configurations.
ingress:
  # Specifies whether Ingress should be enabled for hosting Ghost services.
  # Example:
  # enabled: true
  enabled: false
  # The name of the cluster issuer for Ingress.
  # Default: "letsencrypt-dns-prod"
  # Example:
  # clusterIssuer: "letsencrypt-http-prod"
  clusterIssuer: ""
  # Specifies whether the WWW subdomain should be enabled.
  # Example:
  # www: true
  www: false
  # Additional configuration annotations to be added to the Ingress resource.
  # Items: `.prefix`, `.name`, `.value`
  # Example:
  # customAnnotations:
  #   # The prefix of the annotation.
  #   # Default: "nginx.ingress.kubernetes.io"
  #   # Example:
  #   # prefix: "nginx.org"
  #   - prefix: ""
  #   # The name of the annotation.
  #   # Example:
  #   # name: "proxy-connect-timeout"
  #     name: ""
  #   # The value of the annotation.
  #   # Example:
  #   # value: "120"
  #     value: ""
  customAnnotations: []

# Service configurations.
service:
  # The optional node port to expose when the service type is NodePort.
  # Example:
  # nodePort: "32000"
  nodePort: ""
  # The port on which the Ghost server should listen for connections.
  # Default: "80"
  # Example:
  # port: "8080"
  port: ""
  # The type of service used to expose Ghost services.
  # Default: "ClusterIP"
  # Example:
  # type: "NodePort"
  type: ""

# Storage configurations.
storage:
  # Data storage configurations.
  data:
    # Specifies whether persistent storage should be provisioned for data storage.
    # Example:
    # enabled: true
    enabled: false
    # The access mode defining how the data storage can be mounted.
    # Default: "ReadWriteMany"
    # Example:
    # accessMode: "ReadWriteOnce"
    accessMode: ""
    # The path where the data storage should be mounted on the container.
    # Default: "${ghost.install_dir}/content"
    # Example:
    # mountPath: "/data"
    mountPath: ""
    # The subpath within the data storage to mount to the container. Leave empty if not required.
    # Example:
    # subPath: "Data"
    subPath: ""
    # The default amount of persistent storage allocated for the data storage.
    # Default: "1Gi"
    # Example:
    # storage: "10Gi"
    storage: ""
    # The storage class name used for dynamically provisioning a persistent volume for the data storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "smb"
    storageClassName: ""

# Resource requirements and limits for Ghost containers.
resources:
  # Ghost container resources.
  # Example:
  # ghost:
  #   # The minimum amount of resources required by Ghost to run.
  #   requests:
  #     # The minimum amount of CPU resources required by Ghost.
  #     # Example:
  #     # cpu: "10m"
  #     cpu: "100m"
  #     # The minimum amount of memory required by Ghost.
  #     # Example:
  #     # memory: "10Mi"
  #     memory: "256Mi"
  #   # The maximum amount of resources allowed for Ghost.
  #   limits:
  #     # The maximum amount of CPU resources allowed for Ghost.
  #     # Example:
  #     # cpu: "250m"
  #     cpu: "800m"
  #     # The maximum amount of memory allowed for Ghost.
  #     # Example:
  #     # memory: "250Mi"
  #     memory: "800Mi"
  ghost: {}
