# Default values for linkstack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for LinkStack.
# Default: "1"
replicaCount: ""

# Container images used for LinkStack.
image:
  # LinkStack container image configurations.
  # Source: https://hub.docker.com/r/linkstackorg/linkstack
  linkstack:
    # The registry where the LinkStack container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the LinkStack container image used.
    # Default: "linkstackorg/linkstack"
    repository: ""
    # The tag that specifies the version of the LinkStack container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the LinkStack container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Init container image configurations.
  # Source: https://hub.docker.com/_/busybox
  init:
    # The registry where the Init container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Init container image used.
    # Default: "linkstackorg/linkstack"
    repository: ""
    # The tag that specifies the version of the Init container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the Init container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# LinkStack configurations.
linkstack:
  # The ingress domain name that hosts the LinkStack server.
  # Default: "localhost"
  # Example:
  # domain: "linkstack.example.com"
  domain: ""
  # The level of verbosity of the messages recorded in the error log.
  # Default: "info"
  # Example:
  # logLevel: "debug"
  logLevel: ""
  # The maximum amount of memory PHP scripts are allowed to allocate.
  # Default: "256M"
  # Example:
  # phpMemLimit: "512M"
  phpMemLimit: ""
  # The Apache server administrator email address.
  # Default: "admin@example.com"
  # Example:
  # serverAdmin: "foo@example.com"
  serverAdmin: ""
  # The timezone of the LinkStack server.
  # Default: "UTC"
  # Example:
  # timezone: "Asia/Kuala_Lumpur"
  timezone: ""
  # The maximum allowed file size for uploaded files.
  # Default: "8M"
  # Example:
  # uploadMaxFilesize: "10M"
  uploadMaxFilesize: ""
  # Custom init script to run before the LinkStack container starts.
  # Example:
  # initScript: >-
  #   echo "Hello, World!"
  #   echo "This is a custom init script."
  initScript: ""

# Ingress configurations.
ingress:
  # Specifies whether Ingress should be enabled for hosting LinkStack services.
  # Example:
  # enabled: true
  enabled: false
  # The name of the cluster issuer for Ingress.
  # Default: "letsencrypt-dns-prod"
  # Example:
  # clusterIssuer: "letsencrypt-http-prod"
  clusterIssuer: ""
  # Specifies whether the WWW subdomain should be enabled.
  # Example:
  # www: true
  www: false
  # Additional configuration annotations to be added to the Ingress resource.
  # Example:
  # customAnnotations:
  #   # The prefix of the annotation.
  #   # Default: "nginx.ingress.kubernetes.io"
  #   # Example:
  #   # - prefix: "nginx.org"
  #   - prefix: ""
  #   # The name of the annotation.
  #   # Example:
  #     # name: "proxy-connect-timeout"
  #     name: ""
  #   # The value of the annotation.
  #   # Example:
  #     # value: "120"
  #     value: ""
  customAnnotations: []

# Service configurations.
service:
  # HTTP service port configurations.
  http:
    # The optional node port to expose for http when the service type is NodePort.
    # Example:
    # nodePort: "30000"
    nodePort: ""
    # The http port on which the LinkStack server should listen.
    # Default: "80"
    # Example:
    # port: "8080"
    port: ""
  # HTTPS service port configurations.
  https:
    # The optional node port to expose for https when the service type is NodePort.
    # Example:
    # nodePort: "32000"
    nodePort: ""
    # The https port on which the LinkStack server should listen.
    # Default: "443"
    # Example:
    # port: "8443"
    port: ""
  # The type of service used for LinkStack services.
  # Default: "ClusterIP"
  # Example:
  # type: "NodePort"
  type: ""

# Storage configurations.
storage:
  # Data storage configurations.
  data:
    # Specifies whether persistent storage should be provisioned for data storage.
    # Example:
    # enabled: true
    enabled: false
    # The access mode defining how the data storage can be mounted.
    # Default: "ReadWriteOnce"
    # Example:
    # accessMode: "ReadWriteMany"
    accessMode: ""
    # The path where the data storage should be mounted on the container.
    # Default: "/htdocs"
    # Example:
    # mountPath: "/data"
    mountPath: ""
    # The subpath within the data storage to mount to the container. Leave empty if not required.
    # Example:
    # subPath: "Data"
    subPath: ""
    # The default amount of persistent storage allocated for the data storage.
    # Default: "1Gi"
    # Example:
    # storage: "10Gi"
    storage: ""
    # The storage class name used for dynamically provisioning a persistent volume for the data storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

# Resource requirements and limits for LinkStack containers.
resources:
  # LinkStack container resources.
  # Example:
  # linkstack:
  #   # The minimum amount of resources required by LinkStack to run.
  #   requests:
  #     # The minimum amount of CPU resources required by LinkStack.
  #     # Example:
  #     # cpu: "10m"
  #     cpu: "150m"
  #     # The minimum amount of memory required by LinkStack.
  #     # Example:
  #     # memory: "10Mi"
  #     memory: "250Mi"
  #   # The maximum amount of resources allowed for LinkStack.
  #   limits:
  #     # The maximum amount of CPU resources allowed for LinkStack.
  #     # Example:
  #     # cpu: "250m"
  #     cpu: "300m"
  #     # The maximum amount of memory allowed for LinkStack.
  #     # Example:
  #     # memory: "250Mi"
  #     memory: "350Mi"
  linkstack: {}
