{{- $frontend_tag := .Values.image.frontend.tag | default .Chart.AppVersion | toString }}
{{- $platform := .Values.grocy.platform | default "linux/amd64" | toString | quote }}
{{- $mode := .Values.grocy.mode | default "production" | toString | quote }}
{{- $culture := .Values.grocy.culture | default "en_GB" | toString | quote }}
{{- $currency := .Values.grocy.currency | default "MYR" | toString | quote }}
{{- $energy := .Values.grocy.energy | default "kcal" | toString | quote }}
{{- $uploadLimit := .Values.grocy.php.upload_limit | default "50M" | toString | quote }}
{{- $fileLimit := .Values.grocy.php.file_limit | default "200" | toString | quote }}
{{- $postLimit := .Values.grocy.php.post_limit | default "100M" | toString | quote }}
{{- $memoryLimit := .Values.grocy.php.memory_limit | default "512M" | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grocy-cm
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
data:
  GROCY_VERSION: {{ $frontend_tag }}
  PLATFORM: {{ $platform }}
  GROCY_MODE: {{ $mode }}
  GROCY_CULTURE: {{ $culture }}
  GROCY_CURRENCY: {{ $currency }}
  GROCY_ENERGY_UNIT: {{ $energy }}
  MAX_UPLOAD: {{ $uploadLimit }}
  PHP_MAX_FILE_UPLOAD: {{ $fileLimit }}
  PHP_MAX_POST: {{ $postLimit }}
  PHP_MEMORY_LIMIT: {{ $memoryLimit }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grocy-nginx-config
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
data:
  common.conf: |
    {{- include "grocy.common-conf" . | toString | nindent 4 }}
