{{- $dataPersistence := .Values.storage.data.enabled }}
{{- $dataAccessMode := .Values.storage.data.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $dataStorage := .Values.storage.data.storage | default "500Mi" | toString | quote }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- if $dataPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grocy-data-pvc
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
{{- end }}
