apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grocy-svc
  labels:
    {{- include "grocy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: backend
      protocol: TCP
      name: {{ .Release.Name }}-grocy-backend
    - port: 8080
      targetPort: frontend
      protocol: TCP
      name: {{ .Release.Name }}-grocy-frontend
  selector:
    {{- include "grocy.selectorLabels" . | nindent 4 }}
