{{- $secret := .Values.snipeit.secret | toString | b64enc }}
{{- $db_type := .Values.db.type | default "mysql" | toString | b64enc }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | default "3306" | toString | b64enc }}
{{- $smtpHost := .Values.mail.smtp.host | toString | b64enc }}
{{- $smtpPort := .Values.mail.smtp.port | default "587" | toString | b64enc }}
{{- $smtpUser := .Values.mail.smtp.user | toString }}
{{- $smtpPassword := .Values.mail.smtp.password | toString | b64enc }}
{{- $smtpSecure := .Values.mail.smtp.secure | default "true" | toString | b64enc }}
{{- $mailFromEmail := .Values.mail.fromEmail | default $smtpUser | toString | b64enc }}
{{- $mailFromName := .Values.mail.fromName | default "Snipe-IT" | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-snipe-it-secret
  labels:
    {{- include "snipe-it.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: {{ $secret }}
  DB_CONNECTION: {{ $db_type }}
  DB_DATABASE: {{ $db_name }}
  DB_USERNAME: {{ $db_user }}
  DB_PASSWORD: {{ $db_password }}
  DB_HOST: {{ $db_host }}
  DB_PORT: {{ $db_port }}
  MAIL_HOST: {{ $smtpHost }}
  MAIL_PORT: {{ $smtpPort }}
  MAIL_USERNAME: {{ $smtpUser | b64enc }}
  MAIL_PASSWORD: {{ $smtpPassword }}
  MAIL_FROM_ADDR: {{ $mailFromEmail }}
  MAIL_FROM_NAME: {{ $mailFromName }}
  MAIL_REPLYTO_ADDR: {{ $mailFromEmail }}
  MAIL_REPLYTO_NAME: {{ $mailFromName }}
  MAIL_TLS_VERIFY_PEER: {{ $smtpSecure }}
