# Default values for telego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  telego:
    registry: ghcr.io
    repository: irfanhakim-as/telego
    tag: ""
    pullPolicy: IfNotPresent
  
  redis:
    registry: docker.io
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the telego image

telego:
  name: "Telego" # telego name
  debug: false # django debug mode
  secret: "" # django secret key
  celery_timezone: "Asia/Kuala_Lumpur" # scheduler timezone
  telegram:
    token: "" # telegram bot token
    webhook: "telegram/webhooks/" # telegram webhook path
  ngrok:
    enabled: true # enable ngrok
    token: "" # ngrok auth token
  cloudflared:
    enabled: false # enable cloudflared
    domain: "" # cloudflared domain
  commands: "" # custom telegram commands.py file
  messages: "" # custom telegram messages.py file

db:
  type: "postgresql" # database type
  host: "postgres.default.svc.cluster.local" # database server
  port: "5432" # database port
  name: "" # database name
  user: "" # database user
  password: "" # database user password

pvc:
  logs:
    storage: "10Mi" # log files storage size
    storageClassName: "longhorn" # log files storage class name

resources:
  telego:
    requests:
      cpu: "10m" # telego cpu request
      memory: "250Mi" # telego memory request
    limits:
      cpu: "50m" # telego cpu limit
      memory: "500Mi" # telego memory limit
  redis:
    requests:
      cpu: "5m" # redis cpu request
      memory: "30Mi" # redis memory request
    limits:
      cpu: "15m" # redis cpu limit
      memory: "60Mi" # redis memory limit
