# Default values for telego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  telego:
    registry: ghcr.io
    repository: irfanhakim-as/telego
    tag: ""
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the telego image

telego:
  debug: false # django debug mode
  secret: "" # django secret key
  telegram:
    token: "" # telegram bot token
    webhook: "telegram/webhooks/" # telegram webhook path
  ngrok:
    enabled: false # enable ngrok
    token: "" # ngrok auth token
  commands: "" # custom telegram commands.py file
  messages: "" # custom telegram messages.py file

db:
  type: "postgresql" # database type
  host: "postgres.default.svc.cluster.local" # remote host
  port: "5432" # remote database port
  name: "" # telego database name
  user: "" # remote database user
  password: "" # remote database user password

pvc:
  logs:
    storage: "10Mi" # log files storage size
    storageClassName: "longhorn" # log files storage class name

resources:
  requests:
    cpu: "10m" # telego cpu request
    memory: "10Mi" # telego memory request
  limits:
    cpu: "100m" # telego cpu limit
    memory: "100Mi" # telego memory limit
