{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $registry := .Values.image.registry | default "docker.io" | toString }}
{{- $repository := .Values.image.repository | default "postgres" | toString }}
{{- $tag := .Values.image.tag | default .Chart.AppVersion | toString }}
{{- $pullPolicy := .Values.image.pullPolicy | default "IfNotPresent" | toString | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ printf "%s/%s:%s" $registry $repository $tag | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: DB_PASS
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: {{ .Release.Name }}-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: {{ .Release.Name }}-postgres-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-data-pvc
