{{- $storage := .Values.postgres.data.storage | default "1Gi" | toString | quote }}
{{- $storage_class_name := .Values.postgres.data.storageClassName | default "longhorn" | toString | quote }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-data-pvc
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $storage }}
  storageClassName: {{ $storage_class_name }}
