apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  DB_NAME: {{ .Values.postgres.name | b64enc }}
  DB_USER: {{ .Values.postgres.user | b64enc }}
  DB_PASS: {{ .Values.postgres.pass | b64enc }}
