{{- $postgresDB := .Values.postgres.name | default "default" | toString | b64enc }}
{{- $postgresUser := .Values.postgres.user | default "root" | toString | b64enc }}
{{- $postgresPassword := .Values.postgres.password | toString | b64enc }}
{{- $dataMountPath := .Values.storage.data.mountPath | default "/var/lib/postgresql/data" | toString }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ $postgresDB }}
  POSTGRES_USER: {{ $postgresUser }}
  POSTGRES_PASSWORD: {{ $postgresPassword }}
  PGDATA: {{ printf "%s/pgdata" $dataMountPath | toString | b64enc }}
