{{- $postgres_name := .Values.postgres.name | default "default" | toString | b64enc }}
{{- $postgres_user := .Values.postgres.user | default "root" | toString | b64enc }}
{{- $postgres_pass := .Values.postgres.pass | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  DB_NAME: {{ $postgres_name }}
  DB_USER: {{ $postgres_user }}
  DB_PASS: {{ $postgres_pass }}
