{{- $postgresDB := .Values.postgres.name | default "default" | toString | b64enc }}
{{- $postgresUser := .Values.postgres.user | default "root" | toString | b64enc }}
{{- $postgresPassword := .Values.postgres.password | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  DB_NAME: {{ $postgresDB }}
  DB_USER: {{ $postgresUser }}
  DB_PASS: {{ $postgresPassword }}
