# Default values for cloudflared.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Cloudflared image configuration
image:
  cloudflared:
    registry: docker.io
    repository: cloudflare/cloudflared
    tag: ""
    pullPolicy: IfNotPresent

# Cloudflare tunnel configuration
tunnel:
  # Cloudflare tunnel name
  name: ""
  # Cloudflare tunnel credentials file
  file: ""

# Ingress rules
# Example:
# ingress:
#   - hostname: cloudflared.example.com
#     service: cloudflared.default.svc.cluster.local
ingress: []

# Cloudflared system resources
resources:
  requests:
    # Minimum cpu allocation
    cpu: "10m"
    # Minimum ram allocation
    memory: "10Mi"
  limits:
    # Maximum cpu allocation
    cpu: "500m"
    # Maximum ram allocation
    memory: "500Mi"
