{{- $ipv4 := .Values.cloudflareddns.ipv4 | default "true" | toString }}
{{- $ipv6 := .Values.cloudflareddns.ipv6 | default "false" | toString }}
{{- $purge := .Values.cloudflareddns.purge | default "false" | toString }}
{{- $token := .Values.cloudflareddns.token | toString }}
{{- $ttl := .Values.cloudflareddns.ttl | default "300" | toString }}
{{- $zoneID := .Values.cloudflareddns.zoneID | toString }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflareddns-config
  labels:
    {{- include "cloudflareddns.labels" . | nindent 4 }}
type: Opaque
data:
  config.json: |-
    {{- include "cloudflareddns.config-json" . | toString | replace "API_TOKEN" $token | replace "ZONE_ID" $zoneID | replace "ENABLE_IPV4" $ipv4 | replace "ENABLE_IPV6" $ipv6 | replace "ENABLE_PURGE" $purge | replace "TTL_SECONDS" $ttl | b64enc | nindent 4 }}
