{{- $name := .Values.vpbot.name | default "Vpbot" | toString | quote }}
{{- $debug := .Values.vpbot.debug | default "false" | toString | quote }}
{{- $solat_api_id := .Values.vpbot.api.solat.id | default "https://api.myquran.com/v1/sholat/jadwal/%s" | toString | quote }}
{{- $solat_api_my := .Values.vpbot.api.solat.my | default "https://mpt.i906.my/api/prayer/%s" | toString | quote }}
{{- $location := .Values.vpbot.defaults.location | default "wlp-0" | toString | quote }}
{{- $api := .Values.vpbot.telegram.api | default "https://api.telegram.org/bot" | toString | quote }}
{{- $webhook := .Values.vpbot.telegram.webhook | default "webhook/telegram/" | toString | quote }}
{{- $redis_service := printf "redis://%s-vpbot-svc" .Release.Name | quote }}
{{- $scheduler_timezone := .Values.vpbot.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $domain := .Values.vpbot.cloudflared.domain | default "localhost" | toString }}
{{- $clean_model := .Values.vpbot.scheduler.schedule.clean_model | default "0" | toString | quote }}
{{- $object_scheduler := .Values.vpbot.scheduler.schedule.object_scheduler | default "2" | toString | quote }}
{{- $apscheduler := .Values.vpbot.scheduler.apscheduler }}
{{- $celery := .Values.vpbot.scheduler.celery }}
{{- $cloudflared := .Values.vpbot.cloudflared.enabled }}
{{- $ngrok := .Values.vpbot.ngrok.enabled }}
{{- $commands := .Values.vpbot.commands }}
{{- $messages := .Values.vpbot.messages }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-cm
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  APP_NAME: {{ $name }}
  DEBUG: {{ $debug }}
  PRAY_API_ID_URI: {{ $solat_api_id }}
  PRAY_API_MY_URI: {{ $solat_api_my }}
  DEFAULT_LOCATION_CODE: {{ $location }}
  TELEGRAM_BOT_API_URL: {{ $api }}
  TELEGRAM_WEBHOOK_PATH: {{ $webhook }}
  NGROK: {{ $ngrok | toString | quote }}
  {{- if $cloudflared }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
  {{- if or $apscheduler $celery }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  {{- end }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-site-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "vpbot.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
{{- if $apscheduler }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-apscheduler-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- include "vpbot.apscheduler-entrypoint-sh" . | nindent 4 }}
{{- else if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-default-celery-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "vpbot.default-celeryd" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-initd-celery-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "vpbot.initd-celerybeat" . | nindent 4 }}
  celeryd: |-
    {{- include "vpbot.initd-celeryd" . | nindent 4 }}
{{- end }}
{{- if or $apscheduler $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-scheduler-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  tasks.py: |-
    {{- if $apscheduler }}
      {{- include "vpbot.apscheduler-tasks-py" . | replace "CLEAN_MODEL_HOURS" $clean_model | replace "OBJECT_SCHEDULER_SECONDS" $object_scheduler | nindent 4 }}
    {{- else if $celery }}
      {{- include "vpbot.celery-tasks-py" . | nindent 4 }}
    {{- end }}
  {{- if $apscheduler }}
  apps.py: |-
    {{- include "vpbot.apscheduler-apps-py" . | nindent 4 }}
  {{- else if $celery }}
  celery.py: |-
    {{- include "vpbot.celery-py" . | replace "CLEAN_MODEL_HOURS" $clean_model | replace "OBJECT_SCHEDULER_SECONDS" $object_scheduler | nindent 4 }}
  init.py: |-
    {{- include "vpbot.celery-init-py" . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if $commands }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-commands-cm
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  commands.py: |-
    {{ $commands | toString | nindent 4 | trim }}
{{- end }}
{{- if $messages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-messages-cm
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  messages.py: |-
    {{ $messages | toString | nindent 4 | trim }}
{{- end }}
