{{- $domain := .Values.vpbot.cloudflared.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-cm
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.vpbot.name | toString | quote }}
  DEBUG: {{ .Values.vpbot.debug | toString | quote }}
  CELERY_BROKER: redis://{{ .Release.Name }}-vpbot-svc
  CELERY_BACKEND: redis://{{ .Release.Name }}-vpbot-svc
  CELERY_TIMEZONE: {{ .Values.vpbot.celery_timezone | toString | quote }}
  NGROK: {{ .Values.vpbot.ngrok.enabled | toString | quote }}
  {{- if .Values.vpbot.cloudflared.enabled }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
  DJANGO_WEBHOOK_URI: {{ .Values.telegram.webhook | toString | quote }}
  LOG_SIZE_LIMIT: {{ .Values.vpbot.log_size_limit | toString | quote }}
  APP_VERSION: {{ .Values.image.vpbot.tag | default .Chart.AppVersion | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-site-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mika-homelab.com
      DocumentRoot /quarantine-bot
      WSGIScriptAlias / /quarantine-bot/quarantine_bot/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/quarantine-bot" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /quarantine-bot/quarantine_bot>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>

      Alias /media /quarantine-bot/media
      <Directory /quarantine-bot/media>
        Require all granted
      </Directory>
      
      ErrorLog /quarantine-bot/logs/apache.error.log
      CustomLog /quarantine-bot/logs/apache.access.log combined
    </VirtualHost>
