{{- $name := .Values.vpbot.name | default "Vpbot" | toString | quote }}
{{- $debug := .Values.vpbot.debug | default "false" | toString | quote }}
{{- $redis_service := printf "redis://%s-vpbot-svc" .Release.Name | quote }}
{{- $celery_timezone := .Values.vpbot.celery_timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $webhook := .Values.telegram.webhook | default "telegram/webhooks/" | toString | quote }}
{{- $log_size_limit := .Values.vpbot.log_size_limit | default "4" | toString | quote }}
{{- $app_version := .Values.image.vpbot.tag | default .Chart.AppVersion | toString | quote }}
{{- $domain := .Values.vpbot.cloudflared.domain | default "localhost" | toString }}
{{- $cloudflared := .Values.vpbot.cloudflared.enabled }}
{{- $ngrok := .Values.vpbot.ngrok.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-cm
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  APP_NAME: {{ $name }}
  DEBUG: {{ $debug }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  CELERY_TIMEZONE: {{ $celery_timezone }}
  NGROK: {{ $ngrok | toString | quote }}
  DJANGO_WEBHOOK_URI: {{ $webhook }}
  LOG_SIZE_LIMIT: {{ $log_size_limit }}
  APP_VERSION: {{ $app_version }}
  {{- if $cloudflared }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vpbot-site-config
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "vpbot.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
