{{- $storage := .Values.vpbot.persistence.storage | default "10Mi" | toString | quote }}
{{- $storage_class_name := .Values.vpbot.persistence.storageClassName | default "longhorn" | toString | quote }}
{{- $persistence := .Values.vpbot.persistence.enabled }}
{{- if $persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-vpbot-logs-pvc
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $storage }}
  storageClassName: {{ $storage_class_name }}
{{- end }}
