apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.vpbot.secret | toString | b64enc }}
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.token | toString | b64enc }}
  TELEGRAM_ADMIN_ID: {{ .Values.telegram.admin_id | toString | b64enc }}
  TELEGRAM_DEVEL_ID: {{ .Values.telegram.devel_id | toString | b64enc }}
  DEFAULT_USER_PASS: {{ .Values.vpbot.user_pass | toString | b64enc }}
  {{- if .Values.vpbot.ngrok.enabled }}
  NGROK_AUTH_TOKEN: {{ .Values.vpbot.ngrok.auth_token | toString | b64enc }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-postgres-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.db.host | toString | b64enc }}
  DB_NAME: {{ .Values.db.name | toString | b64enc }}
  DB_USER: {{ .Values.db.user | toString | b64enc }}
  DB_PASS: {{ .Values.db.pass | toString | b64enc }}
