apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.vpbot.secret | b64enc }}
  TELEGRAM_BOT_TOKEN: {{ .Values.telegram.token | b64enc }}
  TELEGRAM_ADMIN_ID: {{ .Values.telegram.admin_id | b64enc }}
  TELEGRAM_DEVEL_ID: {{ .Values.telegram.devel_id | b64enc }}
  DEFAULT_USER_PASS: {{ .Values.vpbot.user_pass | b64enc }}
  NGROK_AUTH_TOKEN: {{ .Values.vpbot.ngrok.auth_token | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-postgres-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc }}
  DB_PASS: {{ .Values.db.pass | b64enc }}
