apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.vpbot.SECRET_KEY | b64enc }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secret.vpbot.TELEGRAM_BOT_TOKEN | b64enc }}
  TELEGRAM_ADMIN_ID: {{ .Values.secret.vpbot.TELEGRAM_ADMIN_ID | b64enc }}
  TELEGRAM_DEVEL_ID: {{ .Values.secret.vpbot.TELEGRAM_DEVEL_ID | b64enc }}
  DEFAULT_USER_PASS: {{ .Values.secret.vpbot.DEFAULT_USER_PASS | b64enc }}
  NGROK_AUTH_TOKEN: {{ .Values.secret.vpbot.NGROK_AUTH_TOKEN | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-postgres-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.postgres.DB_USER | b64enc }}
  DB_PASS: {{ .Values.secret.postgres.DB_PASS | b64enc }}
