{{- $secret := .Values.vpbot.secret | toString | b64enc }}
{{- $telegram_token := .Values.telegram.token | toString | b64enc }}
{{- $admin_id := .Values.telegram.admin_id | toString | b64enc }}
{{- $devel_id := .Values.telegram.devel_id | toString | b64enc }}
{{- $user_pass := .Values.vpbot.user_pass | toString | b64enc }}
{{- $ngrok_token := .Values.vpbot.ngrok.token | toString | b64enc }}
{{- $db_type := .Values.db.type | default "postgresql" | toString | b64enc }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | default "5432" | toString | b64enc }}
{{- $ngrok := .Values.vpbot.ngrok.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ $secret }}
  TELEGRAM_BOT_TOKEN: {{ $telegram_token }}
  TELEGRAM_ADMIN_ID: {{ $admin_id }}
  TELEGRAM_DEVEL_ID: {{ $devel_id }}
  DEFAULT_USER_PASS: {{ $user_pass }}
  {{- if $ngrok }}
  NGROK_AUTH_TOKEN: {{ $ngrok_token }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vpbot-postgres-secret
  labels:
    {{- include "vpbot.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $db_host }}
  DB_TYPE: {{ $db_type }}
  DB_PORT: {{ $db_port }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASS: {{ $db_password }}
