{{- $debug := .Values.waktusolat.debug | default "false" | toString | quote }}
{{- $location := .Values.waktusolat.location | default "wlp-0" | join "," | toString | quote }}
{{- $visibility := .Values.waktusolat.visibility | default "public" | toString | quote }}
{{- $post_limit := .Values.waktusolat.post_limit | default "0" | toString | quote }}
{{- $retry_post := .Values.waktusolat.retry_post | default "false" | toString | quote }}
{{- $scheduler_timezone := .Values.waktusolat.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $redis_service := printf "redis://%s-waktusolat-svc" .Release.Name | quote }}
{{- $domain := .Values.waktusolat.domain | default "localhost" | toString }}
{{- $apscheduler := .Values.waktusolat.scheduler.apscheduler }}
{{- $celery := .Values.waktusolat.scheduler.celery }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  LOCATION_CODES: {{ $location }}
  DEFAULT_VISIBILITY: {{ $visibility }}
  POST_LIMIT: {{ $post_limit }}
  RETRY_POST: {{ $retry_post }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
  {{- if or $apscheduler $celery }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "waktusolat.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
{{- if .Values.waktusolat.feed }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-feed-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  feeds.json: |-
    {{- include "waktusolat.feeds-json" . | toString | nindent 4 }}
{{- end }}
{{- if $apscheduler }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-apscheduler-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- include "waktusolat.apscheduler-entrypoint-sh" . | nindent 4 }}
{{- else if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-default-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "waktusolat.default-celeryd" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-initd-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "waktusolat.initd-celerybeat" . | nindent 4 }}
  celeryd: |-
    {{- include "waktusolat.initd-celeryd" . | nindent 4 }}
{{- end }}
{{- if or $apscheduler $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-scheduler-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  {{- if $apscheduler }}
  apps.py: |-
    {{- include "waktusolat.apscheduler-apps-py" . | nindent 4 }}
  {{- else if $celery }}
  celery.py: |-
    {{- include "waktusolat.celery-py" . | nindent 4 }}
  init.py: |-
    {{- include "waktusolat.celery-init-py" . | nindent 4 }}
  {{- end }}
  tasks.py: |-
    {{- if $apscheduler }}
      {{- include "waktusolat.apscheduler-tasks-py" . | nindent 4 }}
    {{- else if $celery }}
      {{- include "waktusolat.celery-tasks-py" . | nindent 4 }}
    {{- end }}
{{- end }}
