{{- $debug := .Values.waktusolat.debug | default "false" | toString | quote }}
{{- $location := .Values.waktusolat.location | default "wlp-0" | toString | quote }}
{{- $api := .Values.waktusolat.mastodon.api | toString | quote }}
{{- $redis_service := printf "redis://%s-waktusolat-svc" .Release.Name | quote }}
{{- $scheduler_timezone := .Values.waktusolat.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $domain := .Values.waktusolat.domain | default "localhost" | toString }}
{{- $apscheduler := .Values.waktusolat.scheduler.apscheduler }}
{{- $celery := .Values.waktusolat.scheduler.celery }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  LOCATION_CODE: {{ $location }}
  API_BASE_URL: {{ $api }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mikahomelab.com
      DocumentRoot /base
      WSGIScriptAlias / /base/base/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/base" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /base/base>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
{{- if $apscheduler }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-apscheduler-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- include "waktusolat.apscheduler-entrypoint-sh" . | nindent 4 }}
{{- else if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-default-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "waktusolat.default-celeryd" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-initd-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "waktusolat.initd-celerybeat" . | nindent 4 }}
  celeryd: |-
    {{- include "waktusolat.initd-celeryd" . | nindent 4 }}
{{- end }}
{{- if or $apscheduler $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-scheduler-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  {{- if $apscheduler }}
  apps.py: |-
    {{- include "waktusolat.apps-py" . | nindent 4 }}
  {{- else if $celery }}
  celery.py: |-
    {{- include "waktusolat.celery-py" . | nindent 4 }}
  init.py: |-
    {{- include "waktusolat.init-py" . | nindent 4 }}
  {{- end }}
  tasks.py: |-
    {{- if $apscheduler }}
      {{- include "waktusolat.apscheduler-tasks-py" . | nindent 4 }}
    {{- else if $celery }}
      {{- include "waktusolat.celery-tasks-py" . | nindent 4 }}
    {{- end }}
{{- end }}
