{{- $debug := .Values.waktusolat.debug | default "false" | toString | quote }}
{{- $location := .Values.waktusolat.location | default "wlp-0" | toString | quote }}
{{- $api := .Values.waktusolat.mastodon.api | toString | quote }}
{{- $redis_service := printf "redis://%s-waktusolat-svc" .Release.Name | quote }}
{{- $celery_timezone := .Values.waktusolat.celery_timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $domain := .Values.waktusolat.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  LOCATION_CODE: {{ $location }}
  API_BASE_URL: {{ $api }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  CELERY_TIMEZONE: {{ $celery_timezone }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mikahomelab.com
      DocumentRoot /base
      WSGIScriptAlias / /base/base/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/base" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /base/base>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  default-celeryd: |-
    {{- include "waktusolat.default-celeryd" . | nindent 4 }}
  celerybeat: |-
    {{- include "waktusolat.initd-celerybeat" . | nindent 4 }}
  initd-celeryd: |-
    {{- include "waktusolat.initd-celeryd" . | nindent 4 }}
