{{- $apscheduler := .Values.scheduler.apscheduler }}
{{- $celery := .Values.scheduler.celery }}
{{- $feeds := .Values.waktusolat.feed }}
{{- $ingress := .Values.ingress.enabled }}
{{- $debug := .Values.waktusolat.debug | default "false" | toString | quote }}
{{- $scheduler_timezone := .Values.scheduler.timezone | default "Etc/UTC" | toString | quote }}
{{- $visibility := .Values.waktusolat.visibility | default "public" | toString | quote }}
{{- $location := .Values.waktusolat.location | default "wlp-0" | join "," | toString | quote }}
{{- $logLevel := .Values.waktusolat.log.level | default "info" | toString | quote }}
{{- $logMaxFiles := .Values.waktusolat.log.maxFiles | default "3" | toString | quote }}
{{- $logMaxFileSize := .Values.waktusolat.log.maxFileSize | default "10" | toString | quote }}
{{- $organic := .Values.waktusolat.organic | default "true" | toString | quote }}
{{- $post_limit := .Values.waktusolat.post_limit | default "0" | toString | quote }}
{{- $retry_post := .Values.waktusolat.retry_post | default "true" | toString | quote }}
{{- $serviceName := printf "%s-waktusolat-svc" .Release.Name | toString }}
{{- $redis_service := printf "redis://%s" $serviceName | quote }}
{{- $domain := .Values.waktusolat.domain | toString }}
{{- $domain = ternary $domain "localhost" (and $ingress (ne $domain "") (ne $domain "localhost")) }}
{{- $serverAdmin := .Values.waktusolat.serverAdmin | default "admin@example.com" | toString }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  DEFAULT_VISIBILITY: {{ $visibility }}
  LOCATION_CODES: {{ $location }}
  ORGANIC_POSTS: {{ $organic }}
  POST_LIMIT: {{ $post_limit }}
  RETRY_POST: {{ $retry_post }}
  LOG_LEVEL: {{ $logLevel }}
  LOG_MAX_BACKUP: {{ $logMaxFiles }}
  LOG_MAX_SIZE: {{ $logMaxFileSize }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
  {{- if or $apscheduler $celery }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "waktusolat.site-config-conf" . | toString | replace "DOMAIN" $domain | replace "SERVER_ADMIN" $serverAdmin | nindent 4 }}
{{- if $feeds }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-feed-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  feeds.json: |-
    {{- include "waktusolat.feeds-json" . | toString | nindent 4 }}
{{- end }}
{{- if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-default-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "waktusolat.default-celeryd" . | toString | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-initd-celery-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "waktusolat.initd-celerybeat" . | toString | nindent 4 }}
  celeryd: |-
    {{- include "waktusolat.initd-celeryd" . | toString | nindent 4 }}
{{- end }}
{{- if or $apscheduler $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-scheduler-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  {{- if $apscheduler }}
  apps.py: |-
    {{- include "waktusolat.apscheduler-apps-py" . | toString | nindent 4 }}
  {{- else if $celery }}
  celery.py: |-
    {{- include "waktusolat.celery-py" . | toString | nindent 4 }}
  init.py: |-
    {{- include "waktusolat.celery-init-py" . | toString | nindent 4 }}
  {{- end }}
  tasks.py: |-
    {{- if $apscheduler }}
      {{- include "waktusolat.apscheduler-tasks-py" . | toString | nindent 4 }}
    {{- else if $celery }}
      {{- include "waktusolat.celery-tasks-py" . | toString | nindent 4 }}
    {{- end }}
{{- end }}
