{{- $domain := .Values.waktusolat.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.waktusolat.debug | toString | quote }}
  LOCATION_CODE: {{ .Values.waktusolat.location | toString | quote }}
  API_BASE_URL: {{ .Values.waktusolat.mastodon.api | toString | quote }}
  CELERY_BROKER: redis://{{ .Release.Name }}-waktusolat-redis-svc:6379/0
  CELERY_BACKEND: redis://{{ .Release.Name }}-waktusolat-redis-svc:6379/0
  CELERY_TIMEZONE: {{ .Values.waktusolat.celery_timezone | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mikahomelab.com
      DocumentRoot /base
      WSGIScriptAlias / /base/base/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/base" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /base/base>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
