{{- $domain := .Values.waktusolat.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-cm
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  DEBUG: {{ .Values.waktusolat.debug | toString | quote }}
  LOCATION_CODE: {{ .Values.waktusolat.location | toString | quote }}
  API_BASE_URL: {{ .Values.waktusolat.mastodon.api | toString | quote }}
  CELERY_BROKER: redis://{{ .Release.Name }}-waktusolat-svc
  CELERY_BACKEND: redis://{{ .Release.Name }}-waktusolat-svc
  CELERY_TIMEZONE: {{ .Values.waktusolat.celery_timezone | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-site-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mikahomelab.com
      DocumentRoot /base
      WSGIScriptAlias / /base/base/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/base" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /base/base>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-celeryd
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celeryd: |-
    # Names of nodes to start
    #   most people will only start one node:
    #CELERYD_NODES="worker1"
    #   but you can also start multiple and configure settings
    #   for each in CELERYD_OPTS
    #CELERYD_NODES="worker1 worker2 worker3"
    #   alternatively, you can specify the number of nodes to start:
    #CELERYD_NODES=10
    CELERYD_NODES="worker1"

    # Absolute or relative path to the 'celery' command:
    #CELERY_BIN="/usr/local/bin/celery"
    #CELERY_BIN="/virtualenvs/def/bin/celery"
    CELERY_BIN="/usr/local/bin/celery"

    # App instance to use
    # comment out this line if you don't use an app
    #CELERY_APP="proj"
    # or fully qualified:
    #CELERY_APP="proj.tasks:app"
    CELERY_APP="base"

    # Where to chdir at start.
    #CELERYD_CHDIR="/opt/Myproject/"
    CELERYD_CHDIR="/base/"

    # Extra command-line arguments to the worker
    #CELERYD_OPTS="--time-limit=300 --concurrency=8"
    # Configure node-specific settings by appending node name to arguments:
    #CELERYD_OPTS="--time-limit=300 -c 8 -c:worker2 4 -c:worker3 2 -Ofair:worker1"
    CELERYD_OPTS="--time-limit=300 --concurrency=8 --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo"

    # Set logging level
    #CELERYD_LOG_LEVEL="DEBUG"
    CELERYD_LOG_LEVEL="INFO"

    # %n will be replaced with the first part of the nodename.
    #CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
    #CELERYD_PID_FILE="/var/run/celery/%n.pid"
    CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
    CELERYD_PID_FILE="/var/run/celery/%n.pid"

    # Workers should run as an unprivileged user.
    #   You need to create this user manually (or you can choose
    #   a user/group combination that already exists (e.g., nobody).
    #CELERYD_USER="celery"
    #CELERYD_GROUP="celery"
    CELERYD_USER="root"
    CELERYD_GROUP="root"

    # If enabled pid and log directories will be created if missing,
    # and owned by the userid/group configured.
    #CELERY_CREATE_DIRS=1
    CELERY_CREATE_DIRS=1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-celeryd-initd
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "waktusolat.celeryd" . | toString | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-waktusolat-celerybeat-initd
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "waktusolat.celerybeat" . | toString | nindent 4 }}
