{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $waktusolat_registry := .Values.image.waktusolat.registry | default "ghcr.io" | toString }}
{{- $waktusolat_repository := .Values.image.waktusolat.repository | default "irfanhakim-as/waktusolat" | toString }}
{{- $waktusolat_tag := .Values.image.waktusolat.tag | default .Chart.AppVersion | toString }}
{{- $waktusolat_pullPolicy := .Values.image.waktusolat.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $redis_registry := .Values.image.redis.registry | default "docker.io" | toString }}
{{- $redis_repository := .Values.image.redis.repository | default "redis" | toString }}
{{- $redis_tag := .Values.image.redis.tag | default "alpine" | toString }}
{{- $redis_pullPolicy := .Values.image.redis.pullPolicy | default "IfNotPresent" | toString | quote }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-waktusolat
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "waktusolat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "waktusolat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: waktusolat
          image: {{ printf "%s/%s:%s" $waktusolat_registry $waktusolat_repository $waktusolat_tag | quote }}
          imagePullPolicy: {{ $waktusolat_pullPolicy }}
          ports:
            - name: waktusolat
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.waktusolat | nindent 12 }}
          env:
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: DEBUG
            - name: LOCATION_CODE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: LOCATION_CODE
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: API_BASE_URL
            - name: CELERY_BROKER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: CELERY_BROKER
            - name: CELERY_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: CELERY_BACKEND
            - name: CELERY_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-waktusolat-cm
                  key: CELERY_TIMEZONE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: SECRET_KEY
            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_TYPE
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-waktusolat-secret
                  key: DB_PORT
          volumeMounts:
            - name: {{ .Release.Name }}-waktusolat-site-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: site-config.conf
              readOnly: true
            - name: {{ .Release.Name }}-waktusolat-default-celery-config
              mountPath: /etc/default/celeryd
              subPath: celeryd
            - name: {{ .Release.Name }}-waktusolat-initd-celery-config
              mountPath: /etc/init.d/celerybeat
              subPath: celerybeat
            - name: {{ .Release.Name }}-waktusolat-initd-celery-config
              mountPath: /etc/init.d/celeryd
              subPath: celeryd
            - name: {{ .Release.Name }}-waktusolat-token-secret
              mountPath: /base/base/mastodon.secret
              subPath: mastodon.secret
              readOnly: true
        - name: redis
          image: {{ printf "%s/%s:%s" $redis_registry $redis_repository $redis_tag | quote }}
          imagePullPolicy: {{ $redis_pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
      volumes:
        - name: {{ .Release.Name }}-waktusolat-site-config
          configMap:
            name: {{ .Release.Name }}-waktusolat-site-config
        - name: {{ .Release.Name }}-waktusolat-default-celery-config
          configMap:
            name: {{ .Release.Name }}-waktusolat-default-celery-config
            defaultMode: 0640
            items:
              - key: celeryd
                path: celeryd
        - name: {{ .Release.Name }}-waktusolat-initd-celery-config
          configMap:
            name: {{ .Release.Name }}-waktusolat-initd-celery-config
            defaultMode: 0755
            items:
              - key: celerybeat
                path: celerybeat
              - key: celeryd
                path: celeryd
        - name: {{ .Release.Name }}-waktusolat-token-secret
          secret:
            secretName: {{ .Release.Name }}-waktusolat-token-secret
