{{- $secret := .Values.waktusolat.secret | toString | b64enc }}
{{- $db_type := .Values.db.type | default "postgresql" | toString | b64enc }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | default "5432" | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-waktusolat-secret
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ $secret }}
  DB_TYPE: {{ $db_type }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASS: {{ $db_password }}
  DB_HOST: {{ $db_host }}
  DB_PORT: {{ $db_port }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-waktusolat-mastodon-config
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
type: Opaque
data:
  accounts.json: |-
    {{- include "waktusolat.accounts-json" . | toString | b64enc | nindent 4 }}
{{- if .Values.waktusolat.mastodon }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-waktusolat-token-secret
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.waktusolat.mastodon }}
  {{- $normalised_api := .api | toString | replace "https" "" | replace ":" "" | replace "/" "" }}
  {{ printf "%s-%s.secret" .id $normalised_api | toString | replace " " "" }}: |-
    {{ .token | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
