{{- $celery := .Values.scheduler.celery }}
{{- $waktusolatPort := .Values.service.waktusolat.port | default "80" | toString }}
{{- $waktusolatNodePort := .Values.service.waktusolat.nodePort | toString }}
{{- $redisPort := .Values.service.redis.port | default "6379" | toString }}
{{- $redisNodePort := .Values.service.redis.nodePort | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-waktusolat-svc
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $waktusolatPort }}
      targetPort: waktusolat
      {{- if and (eq $type "NodePort") $waktusolatNodePort }}
      nodePort: {{ int $waktusolatNodePort }}
      {{- end }}
      protocol: TCP
      name: waktusolat
    {{- if $celery }}
    - port: {{ int $redisPort }}
      targetPort: redis
      {{- if and (eq $type "NodePort") $redisNodePort }}
      nodePort: {{ int $redisNodePort }}
      {{- end }}
      protocol: TCP
      name: redis
    {{- end }}
  selector:
    {{- include "waktusolat.selectorLabels" . | nindent 4 }}
