{{- $celery := .Values.waktusolat.scheduler.celery }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-waktusolat-svc
  labels:
    {{- include "waktusolat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: waktusolat
      protocol: TCP
      name: {{ .Release.Name }}-waktusolat
    {{- if $celery }}
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: {{ .Release.Name }}-redis
    {{- end }}
  selector:
    {{- include "waktusolat.selectorLabels" . | nindent 4 }}
