# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Desired number of running replicas for PostgreSQL.
# Default: "1"
replicaCount: ""

# Container image used for the PostgreSQL database.
image:
  # PostgreSQL image registry.
  # Default: "docker.io"
  registry: ""
  # PostgreSQL image repository.
  # Default: "postgres"
  repository: ""
  # PostgreSQL image version.
  # Default: Chart appVersion
  tag: ""
  # PostgreSQL image pull policy.
  # Default: "IfNotPresent"
  pullPolicy: ""

postgres:
  name: "default" # name of default database
  user: "root" # database user
  pass: "" # database user password
  data:
    # Data storage size.
    # Default: "1Gi"
    # Example:
    # storage: "1Gi"
    storage: ""
    # Data storage class name.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

resources:
  requests:
    cpu: "10m" # postgres cpu request
    memory: "10Mi" # postgres memory request
  limits:
    cpu: "250m" # postgres cpu limit
    memory: "250Mi" # postgres memory limit
