# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  postgres:
    registry: docker.io
    repository: postgres
    tag: ""
    pullPolicy: IfNotPresent

postgres:
  name: "default" # name of default database
  user: "root" # database user
  pass: "" # database user password
  data:
    # Data storage size.
    # Default: "1Gi"
    # Example:
    # storage: "1Gi"
    storage: ""
    # Data storage class name.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

resources:
  requests:
    cpu: "10m" # postgres cpu request
    memory: "10Mi" # postgres memory request
  limits:
    cpu: "250m" # postgres cpu limit
    memory: "250Mi" # postgres memory limit
