# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Desired number of running replicas for PostgreSQL.
# Default: "1"
replicaCount: ""

# Container image used for the PostgreSQL database.
image:
  # PostgreSQL image registry.
  # Default: "docker.io"
  registry: ""
  # PostgreSQL image repository.
  # Default: "postgres"
  repository: ""
  # PostgreSQL image version.
  # Default: Chart appVersion
  tag: ""
  # PostgreSQL image pull policy.
  # Default: "IfNotPresent"
  pullPolicy: ""

postgres:
  name: "default" # name of default database
  user: "root" # database user
  pass: "" # database user password
  data:
    # Data storage size.
    # Default: "1Gi"
    # Example:
    # storage: "1Gi"
    storage: ""
    # Data storage class name.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

# Resource requirements and limits for PostgreSQL.
resources:
  # The minimum amount of resources required by PostgreSQL to run.
  requests:
    # The minimum amount of CPU resources required by PostgreSQL.
    # Example:
    # cpu: "10m"
    cpu: "10m"
    # The minimum amount of memory required by PostgreSQL.
    # Example:
    # memory: "10Mi"
    memory: "10Mi"
  # The maximum amount of resources allowed for PostgreSQL.
  limits:
    # The maximum amount of CPU resources allowed for PostgreSQL.
    # Example:
    # cpu: "250m"
    cpu: "250m"
    # The maximum amount of memory allowed for PostgreSQL.
    # Example:
    # memory: "250Mi"
    memory: "250Mi"
