# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for PostgreSQL.
# Default: "1"
replicaCount: ""

# Container images used for PostgreSQL.
image:
  # PostgreSQL container image configurations.
  # Source: https://hub.docker.com/_/postgres
  postgres:
    # The registry where the PostgreSQL container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the PostgreSQL container image used.
    # Default: "postgres"
    repository: ""
    # The tag that specifies the version of the PostgreSQL container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the PostgreSQL container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# PostgreSQL configurations.
postgres:
  # The name of the default PostgreSQL database.
  # Default: "default"
  # Example:
  # name: "default"
  name: ""
  # The username for accessing the PostgreSQL instance.
  # Default: "root"
  # Example:
  # user: "root"
  user: ""
  # The password for accessing the PostgreSQL instance.
  # Example:
  # pass: "password"
  pass: ""
  # PostgreSQL data configurations.
  data:
    # The amount of persistent storage allocated for the PostgreSQL instance.
    # Default: "1Gi"
    # Example:
    # storage: "1Gi"
    storage: ""
    # The storage class name used for dynamically provisioning a persistent volume for the PostgreSQL storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

# Resource requirements and limits for PostgreSQL.
resources:
  # The minimum amount of resources required by PostgreSQL to run.
  requests:
    # The minimum amount of CPU resources required by PostgreSQL.
    # Example:
    # cpu: "10m"
    cpu: "10m"
    # The minimum amount of memory required by PostgreSQL.
    # Example:
    # memory: "10Mi"
    memory: "100Mi"
  # The maximum amount of resources allowed for PostgreSQL.
  limits:
    # The maximum amount of CPU resources allowed for PostgreSQL.
    # Example:
    # cpu: "250m"
    cpu: "250m"
    # The maximum amount of memory allowed for PostgreSQL.
    # Example:
    # memory: "250Mi"
    memory: "250Mi"
