{{- $debug := .Values.rizz.debug | default "false" | toString | quote }}
{{- $api := .Values.rizz.mastodon.api | toString | quote }}
{{- $bot := .Values.rizz.mastodon.bot | toString | quote }}
{{- $scheduler_timezone := .Values.rizz.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $visibility := .Values.rizz.visibility | default "public" | toString | quote }}
{{- $organic := .Values.rizz.organic | default "true" | toString | quote }}
{{- $post_limit := .Values.rizz.post_limit | default "3" | toString | quote }}
{{- $feed := .Values.rizz.rss.feed | toString | quote }}
{{- $pubdate_format := .Values.rizz.rss.pubdate_format | default "%a, %d %b %Y %H:%M:%S %z" | toString | quote }}
{{- $clean_data := .Values.rizz.scheduler.schedule.clean_data | default "0" | toString | quote }}
{{- $post_scheduler := .Values.rizz.scheduler.schedule.post_scheduler | default "8-23/3" | toString | quote }}
{{- $update_data := .Values.rizz.scheduler.schedule.update_data | default "7-22/3" | toString | quote }}
{{- $redis_service := printf "redis://%s-rizz-svc" .Release.Name | quote }}
{{- $domain := .Values.rizz.domain | default "localhost" | toString }}
{{- $apscheduler := .Values.rizz.scheduler.apscheduler }}
{{- $celery := .Values.rizz.scheduler.celery }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-cm
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  API_BASE_URL: {{ $api }}
  BOT_ID: {{ $bot }}
  DEFAULT_VISIBILITY: {{ $visibility }}
  ORGANIC_POSTS: {{ $organic }}
  POST_LIMIT: {{ $post_limit }}
  RSS_FEED_URL: {{ $feed }}
  RSS_PUBDATE_FORMAT: {{ $pubdate_format }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
  {{- if or $apscheduler $celery }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-site-config
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "rizz.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
{{- if $apscheduler }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-apscheduler-config
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- include "rizz.apscheduler-entrypoint-sh" . | nindent 4 }}
{{- else if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-default-celery-config
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "rizz.default-celeryd" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-initd-celery-config
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "rizz.initd-celerybeat" . | nindent 4 }}
  celeryd: |-
    {{- include "rizz.initd-celeryd" . | nindent 4 }}
{{- end }}
{{- if or $apscheduler $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-rizz-scheduler-config
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
data:
  {{- if $apscheduler }}
  apps.py: |-
    {{- include "rizz.apscheduler-apps-py" . | nindent 4 }}
  {{- else if $celery }}
  celery.py: |-
    {{- include "rizz.celery-py" . | replace "CLEAN_DATA_HOURS" $clean_data | replace "UPDATE_DATA_HOURS" $update_data | replace "POST_SCHEDULER_HOURS" $post_scheduler | nindent 4 }}
  init.py: |-
    {{- include "rizz.celery-init-py" . | nindent 4 }}
  {{- end }}
  tasks.py: |-
    {{- if $apscheduler }}
      {{- include "rizz.apscheduler-tasks-py" . | replace "CLEAN_DATA_HOURS" $clean_data | replace "UPDATE_DATA_HOURS" $update_data | replace "POST_SCHEDULER_HOURS" $post_scheduler | nindent 4 }}
    {{- else if $celery }}
      {{- include "rizz.celery-tasks-py" . | nindent 4 }}
    {{- end }}
{{- end }}
