{{- $logPersistence := .Values.storage.log.enabled }}
{{- $logAccessMode := .Values.storage.log.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $logStorage := .Values.storage.log.storage | default "50Mi" | toString | quote }}
{{- $logStorageClassName := .Values.storage.log.storageClassName | default "longhorn" | toString | quote }}
{{- if $logPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-rizz-log-pvc
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $logAccessMode }}
  resources:
    requests:
      storage: {{ $logStorage }}
  storageClassName: {{ $logStorageClassName }}
{{- end }}
