{{- $celery := .Values.scheduler.celery }}
{{- $rizzPort := .Values.service.rizz.port | default "80" | toString }}
{{- $rizzNodePort := .Values.service.rizz.nodePort | toString }}
{{- $redisPort := .Values.service.redis.port | default "6379" | toString }}
{{- $redisNodePort := .Values.service.redis.nodePort | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rizz-svc
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $rizzPort }}
      targetPort: rizz
      {{- if and (eq $type "NodePort") $rizzNodePort }}
      nodePort: {{ int $rizzNodePort }}
      {{- end }}
      protocol: TCP
      name: rizz
    {{- if $celery }}
    - port: {{ int $redisPort }}
      targetPort: redis
      {{- if and (eq $type "NodePort") $redisNodePort }}
      nodePort: {{ int $redisNodePort }}
      {{- end }}
      protocol: TCP
      name: redis
    {{- end }}
  selector:
    {{- include "rizz.selectorLabels" . | nindent 4 }}
