{{- $celery := .Values.rizz.scheduler.celery }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rizz-svc
  labels:
    {{- include "rizz.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: rizz
      protocol: TCP
      name: {{ .Release.Name }}-rizz
    {{- if $celery }}
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: {{ .Release.Name }}-redis
    {{- end }}
  selector:
    {{- include "rizz.selectorLabels" . | nindent 4 }}
