apiVersion: v2
name: waktusolat
description: Waktu Solat is a simple web application that posts local prayer times on Mastodon.
type: application
version: 0.1.2
appVersion: "0.0.2-dev"
keywords:
  - waktu solat
  - prayer time
  - mastodon
home: https://github.com/irfanhakim-as/waktusolat
icon: https://irfanhakim-as.github.io/charts/logos/mika.png
sources:
  - https://github.com/irfanhakim-as/waktusolat
  - https://github.com/irfanhakim-as/charts
maintainers:
  - name: Irfan Hakim
    email: irfanhakim.as@yahoo.com
    url: https://github.com/irfanhakim-as
