# Default values for waktusolat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for WaktuSolat.
# Default: "1"
replicaCount: ""

# Container images used for WaktuSolat.
image:
  # WaktuSolat container image configurations.
  waktusolat:
    # The registry where the WaktuSolat container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the WaktuSolat container image used.
    # Default: "irfanhakim-as/waktusolat"
    repository: ""
    # The tag that specifies the version of the WaktuSolat container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the WaktuSolat container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Redis container image configurations.
  redis:
    # The registry where the Redis container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Redis container image used.
    # Default: "redis"
    repository: ""
    # The tag that specifies the version of the Redis container image used.
    # Default: "alpine"
    tag: ""
    # The policy that determines when Kubernetes should pull the Redis container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# WaktuSolat configurations.
waktusolat:
  # Specifies whether WaktuSolat should run in debug mode.
  # Default: false
  # Example:
  # debug: true
  debug: false
  # The domain name of the WaktuSolat service.
  # Default: "localhost"
  # Example:
  # domain: "localhost"
  domain: ""
  # A 50-character secret key used for secure session management and cryptographic operations within the WaktuSolat service.
  # Example:
  # secret: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  secret: ""
  # The default location code used by WaktuSolat and its services.
  # Default: "wlp-0"
  # Example:
  # location: "wlp-0"
  location: ""
  # WaktuSolat Mastodon configurations.
  mastodon:
    # API endpoint or URL for the Mastodon instance of the WaktuSolat bot.
    # Example:
    # api: "https://botsin.space/"
    api: ""
    # The username or user account for the Mastodon instance of the WaktuSolat bot.
    # Example:
    # bot: "waktusolat"
    bot: ""
    # A secure token required to authenticate the WaktuSolat service with the Mastodon instance's API.
    # Example:
    # token: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
    token: ""
  # WaktuSolat storage persistence configurations.
  persistence:
    # Specifies whether WaktuSolat should persist its storage.
    # Example:
    # enabled: true
    enabled: false
    # The storage class name used for dynamically provisioning a persistent volume for the WaktuSolat storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""
    # WaktuSolat logs persistence configurations.
    logs:
      # The amount of persistent storage allocated for WaktuSolat logs.
      # Default: "20Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
  # WaktuSolat scheduler configurations.
  scheduler:
    # Specifies whether APScheduler should be used by WaktuSolat as the task scheduler.
    # Example:
    # apscheduler: false
    apscheduler: true
    # Specifies whether Celery should be used by WaktuSolat as the task scheduler.
    # Example:
    # celery: true
    celery: false
    # The timezone for the task scheduler used by WaktuSolat to schedule time-dependent operations.
    # Default: "Asia/Kuala_Lumpur"
    # Example:
    # timezone: "Asia/Kuala_Lumpur"
    timezone: ""

# Database configurations.
db:
  # The type of the database used by WaktuSolat.
  # Default: "postgresql"
  # Example:
  # type: "postgresql"
  type: ""
  # The name of the database used by WaktuSolat.
  # Example:
  # name: "waktusolat"
  name: ""
  # The username or user account for accessing the WaktuSolat database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the WaktuSolat database's user.
  # Example:
  # password: "password"
  password: ""
  # The hostname or IP address of the WaktuSolat database server.
  # Example:
  # host: "waktusolat.default.svc.cluster.local"
  host: ""
  # The port number on which the WaktuSolat database server is listening.
  # Default: "5432"
  # Example:
  # port: "5432"
  port: ""

# Resource requirements and limits for WaktuSolat containers.
resources:
  # WaktuSolat container resources.
  waktusolat:
    # The minimum amount of resources required by WaktuSolat to run.
    requests:
      # The minimum amount of CPU resources required by WaktuSolat.
      # Example:
      # cpu: "20m"
      cpu: "30m"
      # The minimum amount of memory required by WaktuSolat.
      # Example:
      # memory: "250Mi"
      memory: "60Mi"
    # The maximum amount of resources allowed for WaktuSolat.
    limits:
      # The maximum amount of CPU resources allowed for WaktuSolat.
      # Example:
      # cpu: "50m"
      cpu: "50m"
      # The maximum amount of memory allowed for WaktuSolat.
      # Example:
      # memory: "450Mi"
      memory: "120Mi"
  # Scheduler container resources.
  scheduler:
    # The minimum amount of resources required by Scheduler to run.
    requests:
      # The minimum amount of CPU resources required by Scheduler.
      # Example:
      # cpu: "5m"
      cpu: "10m"
      # The minimum amount of memory required by Scheduler.
      # Example:
      # memory: "30Mi"
      memory: "100Mi"
    # The maximum amount of resources allowed for Scheduler.
    limits:
      # The maximum amount of CPU resources allowed for Scheduler.
      # Example:
      # cpu: "15m"
      cpu: "20m"
      # The maximum amount of memory allowed for Scheduler.
      # Example:
      # memory: "50Mi"
      memory: "200Mi"
