# Default values for waktusolat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Waktu Solat image configuration
image:
  waktusolat:
    registry: ghcr.io
    repository: irfanhakim-as/waktusolat
    tag: ""
    pullPolicy: IfNotPresent
  redis:
    registry: docker.io
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent

# Image pull secrets for private registries
imagePullSecrets:
  - name: ghcr-token-secret

# Waktu Solat configuration
waktusolat:
  # Waktu Solat debug mode
  debug: false
  # Waktu Solat secret key
  secret: ""
  # Default location code
  location: "wlp-0"
  # Timezone of the background scheduler
  celery_timezone: "Asia/Kuala_Lumpur"
  # Mastodon configuration
  mastodon:
    # Base API URL
    api: "https://botsin.space/"
    # Mastodon token secret
    token: ""

# Database configuration
db:
  # Database type
  type: "postgresql"
  # Database name
  name: ""
  # Database user
  user: ""
  # Database user password
  password: ""
  # Database server
  host: "postgres.default.svc.cluster.local"
  # Database port
  port: "5432"

# Waktu Solat system resources
resources:
  # Waktu Solat container resources
  waktusolat:
    requests:
      # Minimum CPU allocation
      cpu: "20m"
      # Minimum memory allocation
      memory: "250Mi"
    limits:
      # Maximum CPU allocation
      cpu: "50m"
      # Maximum memory allocation
      memory: "450Mi"
  # Redis container resources
  redis:
    requests:
      # Minimum CPU allocation
      cpu: "5m"
      # Minimum memory allocation
      memory: "30Mi"
    limits:
      # Maximum CPU allocation
      cpu: "15m"
      # Maximum memory allocation
      memory: "50Mi"
