# Default values for waktusolat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for WaktuSolat.
# Default: "1"
replicaCount: ""

# Container images used for WaktuSolat.
image:
  # WaktuSolat container image configurations.
  waktusolat:
    # The registry where the WaktuSolat container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the WaktuSolat container image used.
    # Default: "irfanhakim-as/waktusolat"
    repository: ""
    # The tag that specifies the version of the WaktuSolat container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the WaktuSolat container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Redis container image configurations.
  redis:
    # The registry where the Redis container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Redis container image used.
    # Default: "redis"
    repository: ""
    # The tag that specifies the version of the Redis container image used.
    # Default: "alpine"
    tag: ""
    # The policy that determines when Kubernetes should pull the Redis container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# WaktuSolat configurations.
waktusolat:
  # Specifies whether WaktuSolat should run in debug mode.
  # Default: false
  # Example:
  # debug: true
  debug: false
  # The domain name of the WaktuSolat service.
  # Default: "localhost"
  # Example:
  # domain: "localhost"
  domain: ""
  # The limit number of posts to be scheduled for posting per run.
  # Default: "0" (Unlimited)
  # Example:
  # post_limit: "5"
  post_limit: ""
  # A 50-character secret key used for secure session management and cryptographic operations within the WaktuSolat service.
  # Example:
  # secret: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  secret: ""
  # The default visibility of posts made by the WaktuSolat service.
  # Default: "public"
  # Example:
  # visibility: "unlisted"
  visibility: ""
  # The default location code used by WaktuSolat and its services.
  # Default: "wlp-0"
  # Example:
  # location: "wlp-0"
  location: ""
  # WaktuSolat Mastodon configurations.
  # Example:
  # mastodon:
  #   # API endpoint or URL for the Mastodon instance of the WaktuSolat bot.
  #   # Example:
  #   # api: "https://botsin.space/"
  #   - api: ""
  #   # The username or user account for the Mastodon instance of the WaktuSolat bot.
  #   # Example:
  #   # id: "waktusolat"
  #     id: ""
  #   # A secure token required to authenticate the WaktuSolat service with the Mastodon instance's API.
  #   # Example:
  #   # token: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  #     token: ""
  #   # Specifies whether the WaktuSolat bot should be marked as a bot.
  #   # Default: true
  #   # Example:
  #   # bot: false
  #     bot: ""
  #   # Specifies whether the WaktuSolat bot should appear in the user directory.
  #   # Default: true
  #   # Example:
  #   # discoverable: false
  #     discoverable: ""
  #   # Specifies whether the WaktuSolat bot should be active.
  #   # Default: true
  #   # Example:
  #   # enabled: false
  #     enabled: ""
  #   # The display name of the WaktuSolat bot.
  #   # Default: null
  #   # Example:
  #   # display_name: "WaktuSolat"
  #     display_name: ""
  #   # A list of up to four name-value pairs information to be displayed on the WaktuSolat bot's profile.
  #   # Default: []
  #   # Example:
  #   # fields:
  #   #   - name: "Website 1"
  #   #     value: "https://domain1.example.org"
  #   #   - name: "Website 2"
  #   #     value: "https://domain2.example.org"
  #     fields: []
  #   # Specifies whether the WaktuSolat bot needs to manually approve follow requests.
  #   # Default: false
  #   # Example:
  #   # locked: true
  #     locked: ""
  #   # The bio of the WaktuSolat bot.
  #   # Default: null
  #   # Example:
  #   # note: "This is the bio of the WaktuSolat bot."
  #     note: ""
  mastodon: []
  # WaktuSolat storage persistence configurations.
  persistence:
    # Specifies whether WaktuSolat should persist its storage.
    # Example:
    # enabled: true
    enabled: false
    # The storage class name used for dynamically provisioning a persistent volume for the WaktuSolat storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""
    # WaktuSolat logs persistence configurations.
    logs:
      # The amount of persistent storage allocated for WaktuSolat logs.
      # Default: "20Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
  # WaktuSolat feed configurations.
  # Example:
  # feed:
  #   # The URL of the prayer time API feed to be used by WaktuSolat.
  #   # Example:
  #   # endpoint: "https://mpt.i906.my/api/prayer/%s"
  #   - endpoint: ""
  #   # The unique identifier of the API feed entry, must be an ISO 3166 Alpha-2 country code in uppercase.
  #   # Example:
  #   # id: "MY"
  #     id: ""
  #   # Specifies whether the API feed entry should be active to be used.
  #   # Default: true
  #   # Example:
  #   # enabled: false
  #     enabled: ""
  feed: []
  # WaktuSolat scheduler configurations.
  scheduler:
    # Specifies whether APScheduler should be used by WaktuSolat as the task scheduler.
    # Example:
    # apscheduler: false
    apscheduler: true
    # Specifies whether Celery should be used by WaktuSolat as the task scheduler.
    # Example:
    # celery: true
    celery: false
    # The schedule for the task scheduler used by WaktuSolat.
    schedule:
      # The hours at which the task scheduler cleans up the database.
      # Default: "0"
      # Example:
      # clean_db: "0,6,12,18"
      clean_db: ""
      # The hours at which the task scheduler schedules the daily prayer time schedule posts.
      # Default: "5"
      # Example:
      # notify_solat_schedule: "*"
      notify_solat_schedule: ""
      # The minute intervals at which the task scheduler schedules prayer time notifications.
      # Default: "1"
      # Example:
      # notify_solat_times: "2"
      notify_solat_times: ""
      # The second intervals at which the task scheduler posts scheduled posts.
      # Default: "1"
      # Example:
      # post_scheduler: "10"
      post_scheduler: ""
    # The timezone for the task scheduler used by WaktuSolat to schedule time-dependent operations.
    # Default: "Asia/Kuala_Lumpur"
    # Example:
    # timezone: "Asia/Kuala_Lumpur"
    timezone: ""

# Database configurations.
db:
  # The type of the database used by WaktuSolat.
  # Default: "postgresql"
  # Example:
  # type: "postgresql"
  type: ""
  # The name of the database used by WaktuSolat.
  # Example:
  # name: "waktusolat"
  name: ""
  # The username or user account for accessing the WaktuSolat database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the WaktuSolat database's user.
  # Example:
  # password: "password"
  password: ""
  # The hostname or IP address of the WaktuSolat database server.
  # Example:
  # host: "waktusolat.default.svc.cluster.local"
  host: ""
  # The port number on which the WaktuSolat database server is listening.
  # Default: "5432"
  # Example:
  # port: "5432"
  port: ""

# Resource requirements and limits for WaktuSolat containers.
resources:
  # WaktuSolat container resources.
  waktusolat:
    # The minimum amount of resources required by WaktuSolat to run.
    requests:
      # The minimum amount of CPU resources required by WaktuSolat.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "100m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "20m"
      cpu: "30m"
      # The minimum amount of memory required by WaktuSolat.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "250Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "250Mi"
      memory: "60Mi"
    # The maximum amount of resources allowed for WaktuSolat.
    limits:
      # The maximum amount of CPU resources allowed for WaktuSolat.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "200m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "50m"
      cpu: "50m"
      # The maximum amount of memory allowed for WaktuSolat.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "400Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "450Mi"
      memory: "120Mi"
  # Scheduler container resources.
  scheduler:
    # The minimum amount of resources required by Scheduler to run.
    requests:
      # The minimum amount of CPU resources required by Scheduler.
      # Example:
      # cpu: "5m"
      cpu: "10m"
      # The minimum amount of memory required by Scheduler.
      # Example:
      # memory: "30Mi"
      memory: "100Mi"
    # The maximum amount of resources allowed for Scheduler.
    limits:
      # The maximum amount of CPU resources allowed for Scheduler.
      # Example:
      # cpu: "15m"
      cpu: "20m"
      # The maximum amount of memory allowed for Scheduler.
      # Example:
      # memory: "50Mi"
      memory: "200Mi"
