apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-dropdb-secret
  labels:
    {{- include "postgres-dropdb.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.postgres.DB_USER | b64enc }}
  DB_PASS: {{ .Values.secret.postgres.DB_PASS | b64enc }}
