{{- $dataPersistence := .Values.storage.data.enabled }}
{{- $vaultwarden_registry := .Values.image.vaultwarden.registry | default "ghcr.io" | toString }}
{{- $vaultwarden_repository := .Values.image.vaultwarden.repository | default "dani-garcia/vaultwarden" | toString }}
{{- $vaultwarden_tag := .Values.image.vaultwarden.tag | default .Chart.AppVersion | toString }}
{{- $vaultwarden_pullPolicy := .Values.image.vaultwarden.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $init_registry := .Values.image.init.registry | default "docker.io" | toString }}
{{- $init_repository := .Values.image.init.repository | default "busybox" | toString }}
{{- $init_tag := .Values.image.init.tag | default "1.36.1" | toString }}
{{- $init_pullPolicy := .Values.image.init.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $dataMountPath := .Values.storage.data.mountPath | default "/data" | toString | quote }}
{{- $dataSubPath := .Values.storage.data.subPath | toString }}
{{- $initScript := .Values.vaultwarden.initScript | toString }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vaultwarden
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "vaultwarden.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vaultwarden.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $initScript }}
      initContainers:
        - name: init
          image: {{ printf "%s/%s:%s" $init_registry $init_repository $init_tag | quote }}
          imagePullPolicy: {{ $init_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              {{- $initScript | nindent 14 }}
          {{- if or $dataPersistence }}
          volumeMounts:
            {{- if $dataPersistence }}
            - name: {{ .Release.Name }}-vaultwarden-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}
      containers:
        - name: vaultwarden
          image: {{ printf "%s/%s:%s" $vaultwarden_registry $vaultwarden_repository $vaultwarden_tag | quote }}
          imagePullPolicy: {{ $vaultwarden_pullPolicy }}
          ports:
            - name: vaultwarden
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.vaultwarden | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-vaultwarden-cm
            - secretRef:
                name: {{ .Release.Name }}-vaultwarden-secret
          {{- if or $dataPersistence }}
          volumeMounts:
            {{- if $dataPersistence }}
            - name: {{ .Release.Name }}-vaultwarden-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- if or $dataPersistence }}
      volumes:
        {{- if $dataPersistence }}
        - name: {{ .Release.Name }}-vaultwarden-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-vaultwarden-data-pvc
        {{- end }}
      {{- end }}
