{{- $push := .Values.push.enabled | default "false" | toString }}
{{- $pushID := .Values.push.id | toString | b64enc }}
{{- $pushKey := .Values.push.key | toString | b64enc }}

{{- $dataMountPath := .Values.storage.data.mountPath | default "/data" | toString | trimPrefix "/" }}
{{- $db_type := .Values.db.type | default "sqlite" | toString }}
{{- $db_name := .Values.db.name | toString }}
{{- $db_user := .Values.db.user | toString }}
{{- $db_password := .Values.db.password | toString }}
{{- $db_host := .Values.db.host | toString }}
{{- $db_port := .Values.db.port | toString }}
{{- $db_url := printf "%s/db.sqlite3" $dataMountPath }}
{{- if not (eq $db_type "sqlite") }}
  {{- $db_url = printf "%s://%s:%s@%s:%s/%s" $db_type $db_user $db_password $db_host $db_port $db_name }}
{{- end }}

{{- $hibpApiKey := .Values.vaultwarden.hibpApiKey | toString | b64enc }}
{{- $adminToken := .Values.vaultwarden.adminToken | toString | b64enc }}

{{- $yubico := .Values.yubico.enabled | default "false" | toString }}
{{- $yubicoID := .Values.yubico.id | toString | b64enc }}
{{- $yubicoKey := .Values.yubico.key | toString | b64enc }}
{{- $yubicoServer := .Values.yubico.server | toString | b64enc }}

{{- $smtpHost := .Values.mail.smtp.host | toString | b64enc }}
{{- $smtpPort := .Values.mail.smtp.port | default "587" | toString | b64enc }}
{{- $smtpUser := .Values.mail.smtp.user | toString }}
{{- $smtpPassword := .Values.mail.smtp.password | toString | b64enc }}
{{- $mailFromEmail := .Values.mail.fromEmail | default $smtpUser | toString }}

{{- $mail := and $mailFromEmail $smtpHost }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vaultwarden-secret
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ $db_url | b64enc }}
{{- if eq $push "true" }}
  PUSH_INSTALLATION_ID: {{ $pushID }}
  PUSH_INSTALLATION_KEY: {{ $pushKey }}
{{- end }}
{{- if $hibpApiKey }}
  HIBP_API_KEY: {{ $hibpApiKey }}
{{- end }}
{{- if $adminToken }}
  ADMIN_TOKEN: {{ $adminToken }}
{{- end }}
{{- if eq $yubico "true" }}
  YUBICO_CLIENT_ID: {{ $yubicoID }}
  YUBICO_SECRET_KEY: {{ $yubicoKey }}
  {{- if $yubicoServer }}
  YUBICO_SERVER: {{ $yubicoServer }}
  {{- end }}
{{- end }}
{{- if $mail }}
  SMTP_HOST: {{ $smtpHost }}
  SMTP_PORT: {{ $smtpPort }}
  SMTP_USERNAME: {{ $smtpUser | b64enc }}
  SMTP_PASSWORD: {{ $smtpPassword }}
{{- end }}
