{{- $mail := .Values.mail.enabled | toString | quote }}
{{- $redis := .Values.redis.enabled | toString | quote }}
{{- $admins := .Values.kutt.administration.admins | join "," | toString | quote }}
{{- $dailyUserLimit := .Values.kutt.administration.dailyUserLimit | default "50" | toString | quote }}
{{- $disableAnonLinks := .Values.kutt.administration.disableAnonLinks | default "false" | toString | quote }}
{{- $disableRegistration := .Values.kutt.administration.disableRegistration | default "false" | toString | quote }}
{{- $domain := .Values.kutt.domain | default (printf "%s-kutt-svc:kutt" .Release.Name) | toString | quote }}
{{- $kuttPort := .Values.service.kutt.port | default "3000" | toString | quote }}
{{- $linkLength := .Values.kutt.link_length | default "6" | toString | quote }}
{{- $maxStatsPerLink := .Values.kutt.administration.maxStatsPerLink | default "5000" | toString | quote }}
{{- $name := .Values.kutt.name | default "Kutt" | toString | quote }}
{{- $nonUserCooldown := .Values.kutt.administration.nonUserCooldown | default "0" | toString | quote }}
{{- $useHttps := .Values.kutt.useHttps | default "true" | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kutt-config
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
data:
  PORT: {{ $kuttPort }}
  SITE_NAME: {{ $name }}
  DEFAULT_DOMAIN: {{ $domain }}
  LINK_LENGTH: {{ $linkLength }}
  DISALLOW_REGISTRATION: {{ $disableRegistration }}
  DISALLOW_ANONYMOUS_LINKS: {{ $disableAnonLinks }}
  USER_LIMIT_PER_DAY: {{ $dailyUserLimit }}
  NON_USER_COOLDOWN: {{ $nonUserCooldown }}
  DEFAULT_MAX_STATS_PER_LINK: {{ $maxStatsPerLink }}
  CUSTOM_DOMAIN_USE_HTTPS: {{ $useHttps }}
  ADMIN_EMAILS: {{ $admins }}
  MAIL_ENABLED: {{ $mail }}
  REDIS_ENABLED: {{ $redis }}
