{{- $externalRedis := .Values.redis.external }}
{{- $redis := .Values.redis.enabled }}
{{- $db_type := .Values.postgres.type | default "better-sqlite3" | toString }}
{{- $dataPersistence := and .Values.storage.data.enabled (eq $db_type "better-sqlite3") }}
{{- $dataAccessMode := .Values.storage.data.accessMode | default "ReadWriteOnce" | toString | quote }}
{{- $dataStorage := .Values.storage.data.storage | default "1Gi" | toString | quote }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- $redisPersistence := and .Values.storage.redis.enabled $redis (not $externalRedis) }}
{{- $redisAccessMode := .Values.storage.redis.accessMode | default "ReadWriteOnce" | toString | quote }}
{{- $redisStorage := .Values.storage.redis.storage | default "100Mi" | toString | quote }}
{{- $redisStorageClassName := .Values.storage.redis.storageClassName | default "longhorn" | toString | quote }}
{{- if $dataPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kutt-data-pvc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
{{- end }}
{{- if $redisPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kutt-redis-data-pvc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $redisAccessMode }}
  resources:
    requests:
      storage: {{ $redisStorage }}
  storageClassName: {{ $redisStorageClassName }}
{{- end }}
