{{- $externalRedis := .Values.redis.external }}
{{- $redis := .Values.redis.enabled }}
{{- $redisPersistence := and .Values.storage.redis.enabled $redis (not $externalRedis) }}
{{- $redisAccessMode := .Values.storage.redis.accessMode | default "ReadWriteOnce" | toString | quote }}
{{- $redisStorage := .Values.storage.redis.storage | default "100Mi" | toString | quote }}
{{- $redisStorageClassName := .Values.storage.redis.storageClassName | default "longhorn" | toString | quote }}
{{- if $redisPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kutt-redis-data-pvc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $redisAccessMode }}
  resources:
    requests:
      storage: {{ $redisStorage }}
  storageClassName: {{ $redisStorageClassName }}
{{- end }}
