{{- $dataPersistence := .Values.storage.data.enabled }}
{{- $externalRedis := .Values.redis.external }}
{{- $dataAccessMode := .Values.storage.data.accessMode | default "ReadWriteOnce" | toString | quote }}
{{- $dataStorage := .Values.storage.data.storage | default "100Mi" | toString | quote }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- if and $dataPersistence (not $externalRedis) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kutt-redis-data-pvc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
{{- end }}
