{{- $secret := .Values.kutt.secret | toString | b64enc }}
{{- $db_type := .Values.db.type | default "postgresql" | toString | b64enc }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | default "5432" | toString | b64enc }}
{{- $mail_host := .Values.kutt.mail.host | default "smtp.gmail.com" | toString | b64enc }}
{{- $mail_port := .Values.kutt.mail.port | default "465" | toString | b64enc }}
{{- $mail_user := .Values.kutt.mail.user | toString }}
{{- $mail_password := .Values.kutt.mail.password | toString | b64enc }}
{{- $name := .Values.kutt.name | default "Kutt" | toString }}
{{- $from_email := .Values.kutt.mail.from_email | default (printf "%s <%s>" $name $mail_user) | toString | b64enc }}
{{- $contact_email := .Values.kutt.mail.contact_email | toString | b64enc }}
{{- $report_email := .Values.kutt.mail.report_email | toString | b64enc }}
{{- $redis_host := .Values.redis.host | default "localhost" | toString | b64enc }}
{{- $redis_password := .Values.redis.password | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kutt-secret
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ $secret }}
  DB_TYPE: {{ $db_type }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASSWORD: {{ $db_password }}
  DB_HOST: {{ $db_host }}
  DB_PORT: {{ $db_port }}
  DB_SSL: {{ "false" | toString | b64enc }}
  MAIL_HOST: {{ $mail_host }}
  MAIL_PORT: {{ $mail_port }}
  MAIL_SECURE: {{ "true" | toString | b64enc }}
  MAIL_USER: {{ $mail_user | b64enc }}
  MAIL_PASSWORD: {{ $mail_password }}
  MAIL_FROM: {{ $from_email }}
  CONTACT_EMAIL: {{ $contact_email }}
  REPORT_EMAIL: {{ $report_email }}
  # RECAPTCHA_SITE_KEY: ""
  # RECAPTCHA_SECRET_KEY: ""
  # GOOGLE_SAFE_BROWSING_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kutt-redis-secret
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ $redis_host }}
  REDIS_PORT: {{ "6379" | toString | b64enc }}
  {{- if $redis_password }}
  REDIS_PASSWORD: {{ $redis_password }}
  {{- end }}
  # REDIS_DB: ""
