{{- $secret := .Values.kutt.secret | toString | b64enc }}
{{- $db_name := .Values.postgres.name | toString | b64enc }}
{{- $db_user := .Values.postgres.user | toString | b64enc }}
{{- $db_password := .Values.postgres.password | toString | b64enc }}
{{- $db_host := .Values.postgres.host | toString | b64enc }}
{{- $db_port := .Values.postgres.port | default "5432" | toString | b64enc }}
{{- $db_ssl := .Values.postgres.ssl | default "false" | toString | b64enc }}
{{- $name := .Values.kutt.name | default "Kutt" | toString }}
{{- $mailHost := .Values.mail.smtp.host | default "smtp.gmail.com" | toString | b64enc }}
{{- $mailPort := .Values.mail.smtp.port | default "465" | toString | b64enc }}
{{- $mailUser := .Values.mail.smtp.user | toString }}
{{- $mailPassword := .Values.mail.smtp.password | toString | b64enc }}
{{- $mailContact := .Values.mail.contact_email | toString | b64enc }}
{{- $mailFrom := .Values.mail.from_email | default (printf "%s <%s>" $name $mailUser) | toString | b64enc }}
{{- $mailReport := .Values.mail.report_email | toString | b64enc }}
{{- $mailSecure := .Values.mail.secure | default "true" | toString | b64enc }}
{{- $redisHost := .Values.redis.host | default "localhost" | toString | b64enc }}
{{- $redisPort := .Values.redis.port | default "6379" | toString | b64enc }}
{{- $redisPassword := .Values.redis.password | toString | b64enc }}
{{- $recaptchaSecretKey := .Values.google.recaptchaSecretKey | toString | b64enc }}
{{- $recaptchaSiteKey := .Values.google.recaptchaSiteKey | toString | b64enc }}
{{- $safeBrowsingKey := .Values.google.safeBrowsingKey | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kutt-secret
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ $secret }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASSWORD: {{ $db_password }}
  DB_HOST: {{ $db_host }}
  DB_PORT: {{ $db_port }}
  DB_SSL: {{ $db_ssl }}
  MAIL_HOST: {{ $mailHost }}
  MAIL_PORT: {{ $mailPort }}
  MAIL_SECURE: {{ $mailSecure }}
  MAIL_USER: {{ $mailUser | b64enc }}
  MAIL_PASSWORD: {{ $mailPassword }}
  MAIL_FROM: {{ $mailFrom }}
  CONTACT_EMAIL: {{ $mailContact }}
  REPORT_EMAIL: {{ $mailReport }}
  {{- if $recaptchaSecretKey }}
  RECAPTCHA_SECRET_KEY: {{ $recaptchaSecretKey }}
  {{- end }}
  {{- if $recaptchaSiteKey }}
  RECAPTCHA_SITE_KEY: {{ $recaptchaSiteKey }}
  {{- end }}
  {{- if $safeBrowsingKey }}
  GOOGLE_SAFE_BROWSING_KEY: {{ $safeBrowsingKey }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kutt-redis-secret
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ $redisHost }}
  REDIS_PORT: {{ $redisPort }}
  {{- if $redisPassword }}
  REDIS_PASSWORD: {{ $redis_password }}
  {{- end }}
  # REDIS_DB: ""
