{{- $externalRedis := .Values.redis.external }}
{{- $kuttPort := .Values.service.kutt.port | default "3000" | toString }}
{{- $kuttNodePort := .Values.service.kutt.nodePort | toString }}
{{- $redisPort := .Values.service.redis.port | default "6379" | toString }}
{{- $redisNodePort := .Values.service.redis.nodePort | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kutt-svc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $kuttPort }}
      targetPort: kutt
      {{- if and (eq $type "NodePort") $kuttNodePort }}
      nodePort: {{ int $kuttNodePort }}
      {{- end }}
      protocol: TCP
      name: kutt
    {{- if not $externalRedis }}
    - port: {{ int $redisPort }}
      targetPort: redis
      {{- if and (eq $type "NodePort") $redisNodePort }}
      nodePort: {{ int $redisNodePort }}
      {{- end }}
      protocol: TCP
      name: redis
    {{- end }}
  selector:
    {{- include "kutt.selectorLabels" . | nindent 4 }}
