{{- $externalRedis := .Values.redis.external }}
{{- $redis := .Values.redis.enabled }}
{{- $kuttPort := .Values.service.kutt.port | default "3000" | toString }}
{{- $kuttNodePort := .Values.service.kutt.nodePort | toString }}
{{- $redisPort := .Values.redis.port | default "6379" | toString }}
{{- $redisSvcPort := .Values.service.redis.port | default $redisPort | toString }}
{{- $redisNodePort := .Values.service.redis.nodePort | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kutt-svc
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $kuttPort }}
      targetPort: kutt
      {{- if and (eq $type "NodePort") $kuttNodePort }}
      nodePort: {{ int $kuttNodePort }}
      {{- end }}
      protocol: TCP
      name: kutt
  {{- if and $redis (not $externalRedis) }}
    - port: {{ int $redisSvcPort }}
      targetPort: redis
      {{- if and (eq $type "NodePort") $redisNodePort }}
      nodePort: {{ int $redisNodePort }}
      {{- end }}
      protocol: TCP
      name: redis
  {{- end }}
  selector:
    {{- include "kutt.selectorLabels" . | nindent 4 }}
