{{- $http := .Values.service.http | default "80" | toString }}
{{- $https := .Values.service.https | default "443" | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-linkstack-svc
  labels:
    {{- include "linkstack.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $http }}
      targetPort: linkstack-http
      protocol: TCP
      name: linkstack-http
    - port: {{ int $https }}
      targetPort: linkstack-https
      protocol: TCP
      name: linkstack-https
  selector:
    {{- include "linkstack.selectorLabels" . | nindent 4 }}
