# Default values for mariadb-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Container images used for MariaDB-Agent.
image:
  # MariaDB container image configurations.
  # Source: https://hub.docker.com/r/bitnami/mariadb
  mariadb:
    # The registry where the MariaDB container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the MariaDB container image used.
    # Default: "bitnami/mariadb"
    repository: ""
    # The tag that specifies the version of the MariaDB container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the MariaDB container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# MariaDB-Agent configurations.
mariadb:
  # The hostname or IP address of the MariaDB database server.
  # Example:
  # host: "mariadb.default.svc.cluster.local"
  host: ""
  # MariaDB database server root user configurations.
  root:
    # The username or user account for accessing the MariaDB database server as root.
    # Default: "root"
    # Example:
    # user: "root"
    user: ""
    # The password associated with the MariaDB database server root user.
    # Example:
    # password: "password"
    password: ""
  # Database configurations array.
  # Elements: `.name`, `.user`, `.password`, `.create`, `.drop`, `.custom`, `.custom_command`.
  # .name: The name of the intended MariaDB database.
  # .user: The username or user account for accessing the intended MariaDB database.
  # .password: The password associated with the intended MariaDB database user.
  # .create: Specifies whether to create the database and user in the remote MariaDB instance.
  # .drop: Specifies whether to delete the database and user in the remote MariaDB instance.
  # .custom: Specifies whether to run a custom command against the remote MariaDB instance.
  # .custom_command: Specify a custom command to run against the remote MariaDB instance.
  # Example:
  # databases:
  #   - name: "mariadb"
  #     user: "mariadbuser"
  #     password: "mariadbuserpassword"
  #     create: true
  #     drop: false
  #     custom: false
  #     custom_command: >-
  #       CREATE TABLE IF NOT EXISTS `$.name`.`StorageRecords` (
  #         `id` int(11) NOT NULL AUTO_INCREMENT,
  #         `key` varchar(255) NOT NULL,
  #         `value` text NOT NULL,
  #         `created_at` datetime NOT NULL,
  #         `updated_at` datetime NOT NULL,
  #         PRIMARY KEY (`id`),
  #         UNIQUE KEY `key` (`key`)
  #       );
  databases: []

# Resource requirements and limits for MariaDB-Agent containers.
resources:
  # MariaDB container resources.
  # Example:
  # mariadb:
  #   # The minimum amount of resources required by MariaDB to run.
  #   requests:
  #     # The minimum amount of CPU resources required by MariaDB.
  #     # Example:
  #     # cpu: "10m"
  #     cpu: "10m"
  #     # The minimum amount of memory required by MariaDB.
  #     # Example:
  #     # memory: "10Mi"
  #     memory: "10Mi"
  #   # The maximum amount of resources allowed for MariaDB.
  #   limits:
  #     # The maximum amount of CPU resources allowed for MariaDB.
  #     # Example:
  #     # cpu: "250m"
  #     cpu: "250m"
  #     # The maximum amount of memory allowed for MariaDB.
  #     # Example:
  #     # memory: "250Mi"
  #     memory: "250Mi"
  mariadb: {}
