# Default values for rizz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for Rizz.
# Default: "1"
replicaCount: ""

# Container images used for Rizz.
image:
  # Rizz container image configurations.
  # Source: https://github.com/irfanhakim-as/rizz/pkgs/container/rizz
  rizz:
    # The registry where the Rizz container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the Rizz container image used.
    # Default: "irfanhakim-as/rizz"
    repository: ""
    # The tag that specifies the version of the Rizz container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the Rizz container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Redis container image configurations.
  # Source: https://hub.docker.com/_/redis
  redis:
    # The registry where the Redis container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Redis container image used.
    # Default: "redis"
    repository: ""
    # The tag that specifies the version of the Redis container image used.
    # Default: "alpine"
    tag: ""
    # The policy that determines when Kubernetes should pull the Redis container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# Rizz configurations.
rizz:
  # Specifies whether Rizz should run in debug mode.
  # Default: "false"
  # Example:
  # debug: "true"
  debug: ""
  # The domain name of the Rizz service.
  # Default: "localhost"
  # Example:
  # domain: "localhost"
  domain: ""
  # Specifies whether to enable posting in organic numbers.
  # Default: "true"
  # Example:
  # organic: "false"
  organic: ""
  # The limit number of posts to be scheduled for posting per run.
  # Default: "3"
  # Example:
  # post_limit: "5"
  post_limit: ""
  # Specifies whether to retry posting if the post fails to be sent.
  # Default: "true"
  # Example:
  # retry_post: "false"
  retry_post: ""
  # A 50-character secret key used for secure session management and cryptographic operations within the Rizz service.
  # Example:
  # secret: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  secret: ""
  # The default visibility of posts made by the Rizz service.
  # Default: "public"
  # Example:
  # visibility: "unlisted"
  visibility: ""
  # Mastodon configurations.
  # Items: `.api`, `.id`, `.token`, `.bot`, `.discoverable`, `.enabled`, `.display_name`, `.fields`, `.locked`, `.note`
  # Example:
  # mastodon:
  #   # API endpoint or URL for the Mastodon instance of the Rizz bot.
  #   # Example:
  #   # api: "https://botsin.space"
  #   - api: ""
  #   # The username or user account for the Mastodon instance of the Rizz bot.
  #   # Example:
  #   # id: "rizz"
  #     id: ""
  #   # A secure token required to authenticate the Rizz service with the Mastodon instance's API.
  #   # Example:
  #   # token: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  #     token: ""
  #   # Specifies whether the Rizz bot should be marked as a bot.
  #   # Default: "true"
  #   # Example:
  #   # bot: "false"
  #     bot: ""
  #   # Specifies whether the Rizz bot should appear in the user directory.
  #   # Default: "true"
  #   # Example:
  #   # discoverable: "false"
  #     discoverable: ""
  #   # Specifies whether the Rizz bot should be active.
  #   # Default: "true"
  #   # Example:
  #   # enabled: "false"
  #     enabled: ""
  #   # The display name of the Rizz bot.
  #   # Default: "null"
  #   # Example:
  #   # display_name: "Rizz"
  #     display_name: ""
  #   # A list of up to four name-value pairs information to be displayed on the Rizz bot's profile.
  #   # Example:
  #   # fields:
  #   #   - name: "Website 1"
  #   #     value: "https://domain1.example.org"
  #   #   - name: "Website 2"
  #   #     value: "https://domain2.example.org"
  #     fields: []
  #   # Specifies whether the Rizz bot needs to manually approve follow requests.
  #   # Default: "false"
  #   # Example:
  #   # locked: "true"
  #     locked: ""
  #   # The bio of the Rizz bot.
  #   # Default: "null"
  #   # Example:
  #   # note: "This is the bio of the Rizz bot."
  #     note: ""
  mastodon: []
  # Rizz storage persistence configurations.
  persistence:
    # Specifies whether Rizz should persist its storage.
    # Example:
    # enabled: true
    enabled: false
    # The storage class name used for dynamically provisioning a persistent volume for the Rizz storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""
    # Rizz logs persistence configurations.
    logs:
      # The amount of persistent storage allocated for Rizz logs.
      # Default: "20Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
  # Rizz feed configurations.
  # Example:
  # feed:
  #   # The URL of the RSS feed to be tracked by Rizz.
  #   # Example:
  #   # endpoint: "https://www.reddit.com/r/programming/.rss"
  #   - endpoint: ""
  #   # The publishing date format of the RSS feed entry.
  #   # Default: "%a, %d %b %Y %H:%M:%S %z"
  #   # Example:
  #   # pubdate_format: "%a, %d %b %Y %H:%M:%S %Z"
  #     pubdate_format: ""
  #   # The unique identifier of the RSS feed entry.
  #   # Example:
  #   # id: "MyFeed"
  #     id: ""
  #   # Specifies whether the RSS feed entry should be actively processed.
  #   # Default: true
  #   # Example:
  #   # enabled: false
  #     enabled: ""
  feed: []
  # Rizz scheduler configurations.
  scheduler:
    # Specifies whether APScheduler should be used by Rizz as the task scheduler.
    # Example:
    # apscheduler: false
    apscheduler: true
    # Specifies whether Celery should be used by Rizz as the task scheduler.
    # Example:
    # celery: true
    celery: false
    # The schedule for the task scheduler used by Rizz.
    # Note: The `apscheduler` scheduler supports the `hour`, `minute`, and `second` fields simultaneously. The `celery` scheduler only supports a combination of the `hour` and `minute` fields, or the `second` field alone.
    schedule:
      # The schedule for cleaning up the database.
      clean_data:
        # The hours at which the task scheduler cleans up the database.
        # Default: "0"
        # Example:
        # hour: "1"
        hour: ""
        # The minutes at which the task scheduler cleans up the database.
        # Default: "0"
        # Example:
        # minute: "30"
        minute: ""
        # The seconds at which the task scheduler cleans up the database.
        # Default: "0" for `apscheduler`
        # Example:
        # second: "30"
        second: ""
      # The schedule for posting scheduled posts.
      post_scheduler:
        # The hours at which the task scheduler posts scheduled posts.
        # Default: "8-23/3"
        # Example:
        # hour: "*"
        hour: ""
        # The minutes at which the task scheduler posts scheduled posts.
        # Default: "0"
        # Example:
        # minute: "*/30"
        minute: ""
        # The seconds at which the task scheduler posts scheduled posts.
        # Default: "0" for `apscheduler`
        # Example:
        # second: "30"
        second: ""
      # The schedule for updating up the database.
      update_data:
        # The hours at which the task scheduler updates the database.
        # Default: "7-22/3"
        # Example:
        # hour: "*/2"
        hour: ""
        # The minutes at which the task scheduler updates the database.
        # Default: "0"
        # Example:
        # minute: "15"
        minute: ""
        # The seconds at which the task scheduler updates the database.
        # Default: "0" for `apscheduler`
        # Example:
        # second: "30"
        second: ""
    # The timezone for the task scheduler used by Rizz to schedule time-dependent operations.
    # Default: "Asia/Kuala_Lumpur"
    # Example:
    # timezone: "Asia/Kuala_Lumpur"
    timezone: ""

# Database configurations.
db:
  # The type of the database used by Rizz.
  # Default: "postgresql"
  # Example:
  # type: "postgresql"
  type: ""
  # The name of the database used by Rizz.
  # Example:
  # name: "rizz"
  name: ""
  # The username or user account for accessing the Rizz database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the Rizz database's user.
  # Example:
  # password: "password"
  password: ""
  # The hostname or IP address of the Rizz database server.
  # Example:
  # host: "rizz.default.svc.cluster.local"
  host: ""
  # The port number on which the Rizz database server is listening.
  # Default: "5432"
  # Example:
  # port: "5432"
  port: ""

# Resource requirements and limits for Rizz containers.
resources:
  # Rizz container resources.
  rizz:
    # The minimum amount of resources required by Rizz to run.
    requests:
      # The minimum amount of CPU resources required by Rizz.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "100m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "20m"
      cpu: "30m"
      # The minimum amount of memory required by Rizz.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "250Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "250Mi"
      memory: "60Mi"
    # The maximum amount of resources allowed for Rizz.
    limits:
      # The maximum amount of CPU resources allowed for Rizz.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "200m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "50m"
      cpu: "50m"
      # The maximum amount of memory allowed for Rizz.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "400Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "450Mi"
      memory: "120Mi"
  # Scheduler container resources.
  scheduler:
    # The minimum amount of resources required by Scheduler to run.
    requests:
      # The minimum amount of CPU resources required by Scheduler.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "10m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "5m"
      cpu: "10m"
      # The minimum amount of memory required by Scheduler.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "50Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "30Mi"
      memory: "100Mi"
    # The maximum amount of resources allowed for Scheduler.
    limits:
      # The maximum amount of CPU resources allowed for Scheduler.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "20m" or more if using `celery` as the scheduler.
      # Example:
      # cpu: "15m"
      cpu: "20m"
      # The maximum amount of memory allowed for Scheduler.
      # Note: This is the recommended default when using `apscheduler` as the scheduler. Allocate "100Mi" or more if using `celery` as the scheduler.
      # Example:
      # memory: "50Mi"
      memory: "200Mi"
