{{- $adminUser := .Values.linkding.admin.user | toString | b64enc }}
{{- $adminPassword := .Values.linkding.admin.password | toString | b64enc }}
{{- $db_type := .Values.db.type | default "sqlite" | toString }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-linkding-secret
  labels:
    {{- include "linkding.labels" . | nindent 4 }}
type: Opaque
data:
  LD_SUPERUSER_NAME: {{ $adminUser }}
  LD_SUPERUSER_PASSWORD: {{ $adminPassword }}
  LD_DB_ENGINE: {{ $db_type | b64enc }}
{{- if eq $db_type "postgres" }}
  LD_DB_DATABASE: {{ $db_name }}
  LD_DB_USER: {{ $db_user }}
  LD_DB_PASSWORD: {{ $db_password }}
  LD_DB_HOST: {{ $db_host }}
  LD_DB_PORT: {{ $db_port }}
{{- end }}
