apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-CHART_NAME-cm
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
data:
  FOO: "{{ .Values.configmap.CHART_NAME.FOO }}"
