{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $init_registry := .Values.image.init.registry | default "docker.io" | toString }}
{{- $init_repository := .Values.image.init.repository | default "busybox" | toString }}
{{- $init_tag := .Values.image.init.tag | default "1.34" | toString }}
{{- $init_pullPolicy := .Values.image.init.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $CHART_NAME_registry := .Values.image.CHART_NAME.registry | default "docker.io" | toString }}
{{- $CHART_NAME_repository := .Values.image.CHART_NAME.repository | default "CHART_NAME" | toString }}
{{- $CHART_NAME_tag := .Values.image.CHART_NAME.tag | default .Chart.AppVersion | toString }}
{{- $CHART_NAME_pullPolicy := .Values.image.CHART_NAME.pullPolicy | default "IfNotPresent" | toString | quote }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-CHART_NAME
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "CHART_NAME.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "CHART_NAME.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: {{ printf "%s/%s:%s" $init_registry $init_repository $init_tag | quote }}
          imagePullPolicy: {{ $init_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                mkdir -p /opt/CHART_NAME/data &&
                chmod -R 777 /opt/CHART_NAME
          volumeMounts:
            - name: {{ .Release.Name }}-CHART_NAME-data
              mountPath: /opt/CHART_NAME
      containers:
        - name: CHART_NAME
          image: {{ printf "%s/%s:%s" $CHART_NAME_registry $CHART_NAME_repository $CHART_NAME_tag | quote }}
          imagePullPolicy: {{ $CHART_NAME_pullPolicy }}
          ports:
            - name: CHART_NAME
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-CHART_NAME-cm
            - secretRef:
                name: {{ .Release.Name }}-CHART_NAME-secret
          volumeMounts:
            - name: {{ .Release.Name }}-CHART_NAME-data
              mountPath: /opt/CHART_NAME
      volumes:
        - name: {{ .Release.Name }}-CHART_NAME-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-CHART_NAME-data-pvc
