{{- $storage := .Values.CHART_NAME.data.storage | default "1Gi" | toString | quote }}
{{- $storage_class_name := .Values.CHART_NAME.data.storageClassName | default "longhorn" | toString | quote }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-CHART_NAME-data-pvc
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $storage }}
  storageClassName: {{ $storage_class_name }}
