{{- $bar := .Values.chartName.bar | default "bar" | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chartName-secret
  labels:
    {{- include "chartName.labels" . | nindent 4 }}
type: Opaque
data:
  BAR: {{ $bar }}
