apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-CHART_NAME-secret
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
type: Opaque
data:
  BAR: {{ .Values.secret.CHART_NAME.BAR | b64enc }}
