{{- $bar := .Values.CHART_NAME.bar | default "bar" | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-CHART_NAME-secret
  labels:
    {{- include "CHART_NAME.labels" . | nindent 4 }}
type: Opaque
data:
  BAR: {{ $bar }}
