{{- $syncthingConfigs := .Values.syncthing.customConfigs }}
{{- if or $syncthingConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-syncthing-custom-configs
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $syncthingConfigs }}
  syncthing-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
