{{- $environment := .Values.ghost.environment | default "production" | toString }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ghost-config
  labels:
    {{- include "ghost.labels" . | nindent 4 }}
type: Opaque
data:
  {{ printf "config.%s.json" $environment }}: |-
    {{- include "ghost.config-json" . | toString | b64enc | nindent 4 }}
