apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  SITE_NAME: "{{ .Values.configmap.clog.SITE_NAME }}"
  DEBUG: "{{ .Values.configmap.clog.DEBUG }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-postgres-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.configmap.postgres.DB_HOST }}"
  DB_NAME: "{{ .Values.configmap.postgres.DB_NAME }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-site-config
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      ServerName $(NGROK_URI):443
      UseCanonicalName On
      ServerAdmin support@mika-homelab.com
      DocumentRoot /clog
      WSGIScriptAlias / /clog/clog/wsgi.py
      WSGIDaemonProcess $(NGROK_URI) python-path=/clog
      WSGIProcessGroup $(NGROK_URI)
      
      <Directory /clog/clog>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>

      Alias /media /clog/media
      <Directory /clog/media>
        Require all granted
      </Directory>
      
      ErrorLog /clog/logs/apache.error.log
      CustomLog /clog/logs/apache.access.log combined
    </VirtualHost>
