{{- $name := .Values.clog.name | default "Clog" | toString | quote }}
{{- $debug := .Values.clog.debug | default "false" | toString | quote }}
{{- $cloudflared := .Values.clog.cloudflared.enabled }}
{{- $ingress := .Values.ingress.enabled }}
{{- $ngrok := .Values.clog.ngrok.enabled }}
{{- $domain := "" -}}
{{- if $cloudflared }}
{{- $domain = .Values.clog.cloudflared.domain | default "localhost" | toString }}
{{- else if $ingress }}
{{- $domain = .Values.clog.domain | default "localhost" | toString }}
{{- else }}
{{- $domain = "localhost" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  NGROK: {{ $ngrok | toString | quote }}
  SITE_NAME: {{ $name }}
  {{- if or $cloudflared $ingress }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-site-config
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "clog.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
