apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  SITE_NAME: "{{ .Values.configmap.clog.SITE_NAME }}"
  DEBUG: "{{ .Values.configmap.clog.DEBUG }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-postgres-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.configmap.postgres.DB_HOST }}"
  DB_NAME: "{{ .Values.configmap.postgres.DB_NAME }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-nginx-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  nginx.conf: |
    upstream django {
      server {{ .Release.Name }}-clog-svc:8000;
    }

    server {
      listen 80;
      client_max_body_size 10M;
      keepalive_timeout 2000;
      proxy_connect_timeout 2000;
      proxy_send_timeout 2000;
      proxy_read_timeout 2000;

      location / {
        proxy_pass http://django;
      }

      location /static/ {
        alias /static/;
      }

      location /media/ {
        alias /media/;
      }
    }
