{{- $name := .Values.clog.name | default "Clog" | toString | quote }}
{{- $debug := .Values.clog.debug | default "false" | toString | quote }}
{{- $domain := .Values.clog.cloudflared.domain | default "localhost" | toString }}
{{- $cloudflared := .Values.clog.cloudflared.enabled }}
{{- $ngrok := .Values.clog.ngrok.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  SITE_NAME: {{ $name }}
  DEBUG: {{ $debug }}
  NGROK: {{ $ngrok | toString | quote }}
  {{- if $cloudflared }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-site-config
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "clog.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
