{{- $cloudflared := .Values.clog.cloudflared.enabled }}
{{- $ingress := .Values.ingress.enabled }}
{{- $ngrok := .Values.clog.ngrok.enabled }}
{{- $debug := .Values.clog.debug | default "false" | toString | quote }}
{{- $domain := .Values.clog.domain | default "localhost" | toString }}
{{- $name := .Values.clog.name | default "Clog" | toString | quote }}
{{- $serverAdmin := .Values.clog.serverAdmin | default "admin@example.com" | toString }}
{{- $logMountPath := .Values.storage.log.mountPath | default "/var/log/apache2" | toString }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  DEBUG: {{ $debug }}
  NGROK: {{ $ngrok | toString | quote }}
  SITE_NAME: {{ $name }}
  {{- if or $cloudflared $ingress }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-site-config
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "clog.site-config-conf" . | toString | replace "DOMAIN" $domain | replace "SERVER_ADMIN" $serverAdmin | replace "LOG_MOUNT_PATH" $logMountPath | nindent 4 }}
