{{- $domain := .Values.clog.cloudflared.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  SITE_NAME: "{{ .Values.clog.site_name | toString }}"
  DEBUG: "{{ .Values.clog.debug | toString }}"
  NGROK: "{{ .Values.clog.ngrok.enabled | toString }}"
  {{- if .Values.clog.cloudflared.enabled }}
  DOMAIN: "{{ $domain }}"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-postgres-cm
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.db.host | toString }}"
  DB_NAME: "{{ .Values.db.name | toString }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-clog-site-config
  labels:
    {{- include "clog.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@mika-homelab.com
      DocumentRoot /clog
      WSGIScriptAlias / /clog/clog/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/clog" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /clog/clog>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>

      Alias /media /clog/media
      <Directory /clog/media>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
