apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clog
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clog
          image: "{{ .Values.image.clog.registry }}/{{ .Values.image.clog.repository }}:{{ .Values.image.clog.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.clog.pullPolicy }}
          ports:
            - name: clog
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.clog | nindent 12 }}
          env:
            - name: SITE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-cm
                  key: SITE_NAME
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-cm
                  key: DEBUG
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-cm
                  key: DB_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-cm
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-secret
                  key: DB_PASS
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-secret
                  key: SECRET_KEY
          volumeMounts:
            - name: {{ .Release.Name }}-clog-site-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: site-config.conf
              readOnly: true
            - name: {{ .Release.Name }}-clog-static
              mountPath: /static
            - name: {{ .Release.Name }}-clog-media
              mountPath: /clog/media
            - name: {{ .Release.Name }}-clog-core-migrations
              mountPath: /clog/core/migrations
            - name: {{ .Release.Name }}-clog-money-migrations
              mountPath: /clog/money/migrations
        - name: ngrok
          image: "{{ .Values.image.ngrok.registry }}/{{ .Values.image.ngrok.repository }}:{{ .Values.image.ngrok.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.ngrok.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                ngrok authtoken $(NGROK_AUTH) &&
                ngrok http 80 --bind-tls=true
          ports:
            - name: ngrok
              containerPort: 4040
              protocol: TCP
          env:
            - name: NGROK_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-secret
                  key: NGROK_AUTH_TOKEN
      volumes:
        - name: {{ .Release.Name }}-clog-site-config
          configMap:
            name: {{ .Release.Name }}-clog-site-config
            items:
              - key: site-config.conf
                path: site-config.conf
        - name: {{ .Release.Name }}-clog-static
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-static-pvc
        - name: {{ .Release.Name }}-clog-media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-media-pvc
        - name: {{ .Release.Name }}-clog-core-migrations
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-core-migrations-pvc
        - name: {{ .Release.Name }}-clog-money-migrations
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-money-migrations-pvc
