apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clog
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clog
          image: "{{ .Values.image.clog.registry }}/{{ .Values.image.clog.repository }}:{{ .Values.image.clog.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.clog.pullPolicy }}
          ports:
            - name: clog
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.clog | nindent 12 }}
          env:
            - name: SITE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-cm
                  key: SITE_NAME
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-cm
                  key: DEBUG
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-cm
                  key: DB_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-cm
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-postgres-secret
                  key: DB_PASS
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-secret
                  key: SECRET_KEY
          volumeMounts:
            - name: {{ .Release.Name }}-clog-static
              mountPath: /static
            - name: {{ .Release.Name }}-clog-media
              mountPath: /clog/media
      volumes:
        - name: {{ .Release.Name }}-clog-static
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-static-pvc
        - name: {{ .Release.Name }}-clog-media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-media-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clog-nginx
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "clog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.nginx.registry }}/{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-clog-static
              mountPath: /static
            - name: {{ .Release.Name }}-clog-media
              mountPath: /clog/media
            - name: {{ .Release.Name }}-clog-nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: {{ .Release.Name }}-clog-static
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-static-pvc
        - name: {{ .Release.Name }}-clog-media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-media-pvc
        - name: {{ .Release.Name }}-clog-nginx-conf
          configMap:
            name: {{ .Release.Name }}-clog-nginx-cm
            items:
              - key: nginx.conf
                path: nginx.conf
