{{- $ngrok := .Values.clog.ngrok.enabled }}
{{- $logPersistence := .Values.storage.log.enabled }}
{{- $mediaPersistence := .Values.storage.media.enabled }}
{{- $migrationPersistence := .Values.storage.migration.enabled }}
{{- $staticPersistence := .Values.storage.static.enabled }}
{{- $clog_registry := .Values.image.clog.registry | default "ghcr.io" | toString }}
{{- $clog_repository := .Values.image.clog.repository | default "irfanhakim-as/clog" | toString }}
{{- $clog_tag := .Values.image.clog.tag | default .Chart.AppVersion | toString }}
{{- $clog_pullPolicy := .Values.image.clog.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $ngrok_registry := .Values.image.ngrok.registry | default "docker.io" | toString }}
{{- $ngrok_repository := .Values.image.ngrok.repository | default "wernight/ngrok" | toString }}
{{- $ngrok_tag := .Values.image.ngrok.tag | default "latest" | toString }}
{{- $ngrok_pullPolicy := .Values.image.ngrok.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $logMountPath := .Values.storage.log.mountPath | default "/var/log/apache2" | toString | quote }}
{{- $logSubPath := .Values.storage.log.subPath | toString }}
{{- $mediaMountPath := .Values.storage.media.mountPath | default "/clog/media" | toString | quote }}
{{- $mediaSubPath := .Values.storage.media.subPath | toString }}
{{- $migrationMountPath := .Values.storage.migration.mountPath | default "/clog/%s/migrations" | toString | quote }}
{{- $migrationSubPath := .Values.storage.migration.subPath | toString }}
{{- $staticMountPath := .Values.storage.static.mountPath | default "/static" | toString | quote }}
{{- $staticSubPath := .Values.storage.static.subPath | toString }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-clog
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "clog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: clog
          image: {{ printf "%s/%s:%s" $clog_registry $clog_repository $clog_tag | quote }}
          imagePullPolicy: {{ $clog_pullPolicy }}
          ports:
            - name: clog
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.clog | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-clog-cm
            - secretRef:
                name: {{ .Release.Name }}-clog-secret
          volumeMounts:
            - name: {{ .Release.Name }}-clog-site-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: site-config.conf
              readOnly: true
            {{- if $logPersistence }}
            - name: {{ .Release.Name }}-clog-log
              mountPath: {{ $logMountPath }}
              {{- if $logSubPath }}
              subPath: {{ $logSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $mediaPersistence }}
            - name: {{ .Release.Name }}-clog-media
              mountPath: {{ $mediaMountPath }}
              {{- if $mediaSubPath }}
              subPath: {{ $mediaSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $migrationPersistence }}
            - name: {{ .Release.Name }}-clog-core-migration
              mountPath: {{ printf $migrationMountPath "core" }}
              {{- if $migrationSubPath }}
              subPath: {{ $migrationSubPath | quote }}
              {{- end }}
            - name: {{ .Release.Name }}-clog-money-migration
              mountPath: {{ printf $migrationMountPath "money" }}
              {{- if $migrationSubPath }}
              subPath: {{ $migrationSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $staticPersistence }}
            - name: {{ .Release.Name }}-clog-static
              mountPath: {{ $staticMountPath }}
              {{- if $staticSubPath }}
              subPath: {{ $staticSubPath | quote }}
              {{- end }}
            {{- end }}
        {{- if $ngrok }}
        - name: ngrok
          image: {{ printf "%s/%s:%s" $ngrok_registry $ngrok_repository $ngrok_tag | quote }}
          imagePullPolicy: {{ $ngrok_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                ngrok authtoken $(NGROK_AUTH) &&
                ngrok http 80 --bind-tls=true
          ports:
            - name: ngrok
              containerPort: 4040
              protocol: TCP
          env:
            - name: NGROK_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-clog-secret
                  key: NGROK_AUTH_TOKEN
        {{- end }}
      volumes:
        - name: {{ .Release.Name }}-clog-site-config
          configMap:
            name: {{ .Release.Name }}-clog-site-config
        {{- if $logPersistence }}
        - name: {{ .Release.Name }}-clog-log
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-log-pvc
        {{- end }}
        {{- if $mediaPersistence }}
        - name: {{ .Release.Name }}-clog-media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-media-pvc
        {{- end }}
        {{- if $migrationPersistence }}
        - name: {{ .Release.Name }}-clog-core-migration
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-core-migration-pvc
        - name: {{ .Release.Name }}-clog-money-migration
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-money-migration-pvc
        {{- end }}
        {{- if $staticPersistence }}
        - name: {{ .Release.Name }}-clog-static
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-clog-static-pvc
        {{- end }}
      securityContext:
        fsGroup: 33
