apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-static-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.static.storage }}
  storageClassName: {{ .Values.pvc.static.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-media-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.media.storage }}
  storageClassName: {{ .Values.pvc.media.storageClassName }}
