{{- $static_storage := .Values.clog.persistence.static.storage | default "50Mi" | toString | quote }}
{{- $media_storage := .Values.clog.persistence.media.storage | default "100Mi" | toString | quote }}
{{- $logs_storage := .Values.clog.persistence.logs.storage | default "50Mi" | toString | quote }}
{{- $migrations_storage := .Values.clog.persistence.migrations.storage | default "20Mi" | toString | quote }}
{{- $storage_class_name := .Values.clog.persistence.storageClassName | default "longhorn" | toString | quote }}
{{- $persistence := .Values.clog.persistence.enabled }}
{{- if $persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-static-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $static_storage }}
  storageClassName: {{ $storage_class_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-media-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $media_storage }}
  storageClassName: {{ $storage_class_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-logs-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $logs_storage }}
  storageClassName: {{ $storage_class_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-core-migrations-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $migrations_storage }}
  storageClassName: {{ $storage_class_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-clog-money-migrations-pvc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $migrations_storage }}
  storageClassName: {{ $storage_class_name }}
{{- end }}
