apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clog-secret
  labels:
    {{- include "clog.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.clog.secret | toString | b64enc }}
  NGROK_AUTH_TOKEN: {{ .Values.clog.ngrok_auth_token | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clog-postgres-secret
  labels:
    {{- include "clog.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | toString | b64enc }}
  DB_PASS: {{ .Values.db.pass | toString | b64enc }}
