apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clog-secret
  labels:
    {{- include "clog.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.clog.SECRET_KEY | toString | b64enc }}
  NGROK_AUTH_TOKEN: {{ .Values.secret.clog.NGROK_AUTH_TOKEN | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-clog-postgres-secret
  labels:
    {{- include "clog.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.postgres.DB_USER | toString | b64enc }}
  DB_PASS: {{ .Values.secret.postgres.DB_PASS | toString | b64enc }}
