apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clog-svc
  labels:
    {{- include "clog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: clog
      protocol: TCP
      name: {{ .Release.Name }}-clog
  selector:
    {{- include "clog.selectorLabels" . | nindent 4 }}
