{{- $endpoint := "" }}
{{- $links := .Values.littlelink.links }}
{{- $custom_links := list }}
{{- range $links }}
  {{- if .custom.enabled }}
    {{- $custom_links = append $custom_links . }}
  {{- end }}
{{- end }}
{{- $ingress := .Values.ingress.enabled }}
{{- $author := .Values.littlelink.author | toString | quote }}
{{- $biography := .Values.littlelink.biography | toString | quote }}
{{- $domain := .Values.littlelink.domain | default "localhost" | toString }}
{{- if and $ingress (not (eq $domain "localhost")) }}
{{- $endpoint = printf "https://%s" $domain | quote }}
{{- end }}
{{- $favicon := .Values.littlelink.favicon | toString | quote }}
{{- $footer := .Values.littlelink.footer | toString | quote }}
{{- $site_name := .Values.littlelink.site_name | default "LittleLink" | toString | quote }}
{{- $theme := .Values.littlelink.theme | default "dark" | toString | title | quote }}
{{- $title := .Values.littlelink.title | default "LittleLink" | toString | quote }}
{{- $avatarUrl := .Values.littlelink.avatar.url | toString | quote }}
{{- $avatarAlt := .Values.littlelink.avatar.alt | toString | quote }}
{{- $avatarWidth := .Values.littlelink.avatar.width | default "400" | toString | quote }}
{{- $avatarHeight := .Values.littlelink.avatar.height | default "400" | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-littlelink-cm
  labels:
    {{- include "littlelink.labels" . | nindent 4 }}
data:
  META_AUTHOR: {{ $author }}
  BIO: {{ $biography }}
  META_DESCRIPTION: {{ $biography }}
  OG_DESCRIPTION: {{ $biography }}
  FAVICON_URL: {{ $favicon }}
  FOOTER: {{ $footer }}
  OG_SITE_NAME: {{ $site_name }}
  THEME: {{ $theme }}
  META_TITLE: {{ $title }}
  OG_TITLE: {{ $title }}
  AVATAR_URL: {{ $avatarUrl }}
  OG_IMAGE: {{ $avatarUrl }}
  AVATAR_2X_URL: {{ $avatarUrl }}
  AVATAR_ALT: {{ $avatarAlt }}
  OG_IMAGE_WIDTH: {{ $avatarWidth }}
  OG_IMAGE_HEIGHT: {{ $avatarHeight }}
{{- if $endpoint }}
  OG_URL: {{ $endpoint }}
{{- end }}
{{- if $links }}
  BUTTON_ORDER: "{{- range $index, $link := $links }}{{- if and $index $link.name }},{{- end }}{{ $link.name | toString | upper }}{{- end }}"
  {{- range $index, $link := $links }}
    {{- if and $link.name (not $link.custom.enabled) }}
  {{ $link.name | toString | upper }}: {{ $link.url | toString | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if $custom_links }}
  CUSTOM_BUTTON_NAME: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.name | toString | upper }}{{- end }}"
  CUSTOM_BUTTON_TEXT: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.custom.text | default ($link.name | toString | title) | toString }}{{- end }}"
  CUSTOM_BUTTON_URL: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.url | toString }}{{- end }}"
  CUSTOM_BUTTON_COLOR: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.custom.color | default "#000000" | toString }}{{- end }}"
  CUSTOM_BUTTON_TEXT_COLOR: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.custom.text_color | default "#ffffff" | toString }}{{- end }}"
  CUSTOM_BUTTON_ALT_TEXT: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.custom.alt | default ($link.custom.text | default ($link.name | toString | title)) | toString }}{{- end }}"
  CUSTOM_BUTTON_ICON: "{{- range $index, $link := $custom_links }}{{- if $index }},{{- end }}{{ $link.custom.icon | toString }}{{- end }}"
{{- end }}
