{{- $avatarFile := .Values.littlelink.avatar.file }}
{{- $faviconFile := .Values.littlelink.favicon.file }}
{{- if or $avatarFile $faviconFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-littlelink-assets
  labels:
    {{- include "littlelink.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $avatarFile }}
  avatar.jpg: |-
    {{- $avatarFile | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- if $faviconFile }}
  favicon.jpg: |-
    {{- $faviconFile | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
