{{- $domain := .Values.mango.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mango-cm
  labels:
    {{- include "mango.labels" . | nindent 4 }}
data:
  BOT_ID: {{ .Values.mango.mastodon.id | toString | quote }}
  DEBUG: {{ .Values.mango.debug | toString | quote }}
  API_BASE_URL: {{ .Values.mango.mastodon.api | toString | quote }}
  CELERY_BROKER: redis://{{ .Release.Name }}-mango-svc
  CELERY_BACKEND: redis://{{ .Release.Name }}-mango-svc
  CELERY_TIMEZONE: {{ .Values.mango.celery_timezone | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mango-site-config
  labels:
    {{- include "mango.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin {{ .Values.mango.support | toString }}
      DocumentRoot /base
      WSGIScriptAlias / /base/base/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/base" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /base/base>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>
      
      ErrorLog /var/log/apache2/apache.error.log
      CustomLog /var/log/apache2/apache.access.log combined
    </VirtualHost>
