apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mango-secret
  labels:
    {{- include "mango.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.mango.secret | toString | b64enc }}
  DB_TYPE: {{ .Values.db.type | toString | b64enc }}
  DB_NAME: {{ .Values.db.name | toString | b64enc }}
  DB_USER: {{ .Values.db.user | toString | b64enc }}
  DB_PASS: {{ .Values.db.password | toString | b64enc }}
  DB_HOST: {{ .Values.db.host | toString | b64enc }}
  DB_PORT: {{ .Values.db.port | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mango-token-secret
  labels:
    {{- include "mango.labels" . | nindent 4 }}
type: Opaque
data:
  mastodon.secret: |-
    {{ .Values.mango.mastodon.token | toString | b64enc | nindent 4 }}
