apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mango-svc
  labels:
    {{- include "mango.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: mango
      protocol: TCP
      name: {{ .Release.Name }}-mango
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: {{ .Release.Name }}-redis
  selector:
    {{- include "mango.selectorLabels" . | nindent 4 }}
