# Default values for vpbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  vpbot:
    registry: ghcr.io
    repository: irfanhakim-as/quarantine-bot
    tag: ""
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the vpbot image

configmap:
  vpbot:
    DEBUG: "False" # django debug mode
    DJANGO_WEBHOOK_URI: "telegram/webhooks/" # telegram webhook path
    LOG_SIZE_LIMIT: "4" # log file size limit in MiB
  postgres:
    DB_HOST: "postgres.default.svc.cluster.local" # remote postgres host
    DB_NAME: "vpbot" # vpbot postgres database name

secret:
  vpbot:
    SECRET_KEY: "secret" # django secret key
    TELEGRAM_BOT_TOKEN: "secret" # telegram bot token
    TELEGRAM_ADMIN_ID: "secret" # admin telegram chat id
    TELEGRAM_DEVEL_ID: "secret" # admin telegram chat id
    DEFAULT_USER_PASS: "secret" # default user password
    NGROK_AUTH_TOKEN: "secret" # ngrok auth token
  postgres:
    DB_USER: "secret" # remote postgres user
    DB_PASS: "secret" # remote postgres user password

pvc:
  static:
    storage: "50Mi" # static files storage size
    storageClassName: "longhorn" # static files storage class name
  logs:
    storage: "50Mi" # log files storage size
    storageClassName: "longhorn" # log files storage class name
  migrations:
    storage: "50Mi" # migrations files storage size
    storageClassName: "longhorn" # migrations files storage class name

resources:
  requests:
    cpu: "10m" # vpbot cpu request
    memory: "10Mi" # vpbot memory request
  limits:
    cpu: "1" # vpbot cpu limit
    memory: "1Gi" # vpbot memory limit
