# Default values for vpbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for Vpbot.
# Default: "1"
replicaCount: ""

# Container images used for Vpbot.
image:
  # Vpbot container image configurations.
  vpbot:
    # The registry where the Vpbot container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the Vpbot container image used.
    # Default: "irfanhakim-as/vpbot"
    repository: ""
    # The tag that specifies the version of the Vpbot container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the Vpbot container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Redis container image configurations.
  redis:
    # The registry where the Redis container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Redis container image used.
    # Default: "redis"
    repository: ""
    # The tag that specifies the version of the Redis container image used.
    # Default: "alpine"
    tag: ""
    # The policy that determines when Kubernetes should pull the Redis container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Ngrok container image configurations.
  ngrok:
    # The registry where the Ngrok container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Ngrok container image used.
    # Default: "wernight/ngrok"
    repository: ""
    # The tag that specifies the version of the Ngrok container image used.
    # Default: "latest"
    tag: ""
    # The policy that determines when Kubernetes should pull the Ngrok container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# Vpbot configurations.
vpbot:
  # The name of the Vpbot service.
  # Default: "Vpbot"
  # Example:
  # name: "Vpbot"
  name: ""
  # Specifies whether Vpbot should run in debug mode.
  # Default: false
  # Example:
  # debug: true
  debug: ""
  # A 50-character secret key used for secure session management and cryptographic operations within the Vpbot service.
  # Example:
  # secret: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  secret: ""
  # Vpbot scheduler configurations.
  scheduler:
    # Specifies whether APScheduler should be used by Vpbot as the task scheduler.
    # Example:
    # apscheduler: false
    apscheduler: true
    # Specifies whether Celery should be used by Vpbot as the task scheduler.
    # Example:
    # celery: true
    celery: false
    # The timezone for the task scheduler used by Vpbot to schedule time-dependent operations.
    # Default: "Asia/Kuala_Lumpur"
    # Example:
    # timezone: "Asia/Kuala_Lumpur"
    timezone: ""
    # The schedule for the task scheduler used by Vpbot.
    schedule:
      # The hours at which the task scheduler cleans up the database.
      # Default: "0"
      # Example:
      # clean_model: "0,6,12,18"
      clean_model: ""
      # The second intervals at which the task scheduler sends scheduled messages.
      # Default: "2"
      # Example:
      # object_scheduler: "3"
      object_scheduler: ""
  # Vpbot Telegram configurations.
  telegram:
    # API endpoint or URL for the Telegram bot.
    # Default: "https://api.telegram.org/bot"
    # Example:
    # api: "https://api.telegram.org/bot"
    api: ""
    # The Telegram bot token used by Vpbot to communicate with Telegram.
    # Example:
    # token: "1282813559:RrqoFIuWZwNfMLrx3Jd2mdFJnxrMObgQEvz"
    token: ""
    # The Telegram bot webhook path used by Vpbot to communicate with Telegram. Must contain a trailing slash.
    # Default: "webhook/telegram/"
    # Example:
    # webhook: "telegram/jbbhb73f6s/"
    webhook: ""
  # Vpbot log persistence configurations.
  persistence:
    # Specifies whether Vpbot should persist its logs.
    # Example:
    # enabled: true
    enabled: false
    # The amount of persistent storage allocated for Vpbot logs.
    # Default: "10Mi"
    # Example:
    # storage: "1Gi"
    storage: ""
    # The storage class name used for dynamically provisioning a persistent volume for the Vpbot logs storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""
  # Vpbot Ngrok configurations.
  ngrok:
    # Specifies whether Vpbot should run using an Ngrok tunnel.
    # Example:
    # enabled: true
    enabled: false
    # Ngrok authentication token.
    # Example:
    # token: "s7Ed4IO23nw1HWRJwumSgcyB7BtcXr4ZYLtziJCDDLIVDv7uq"
    token: ""
  # Vpbot Cloudflare configurations.
  cloudflared:
    # Specifies whether Vpbot should run using a Cloudflare tunnel.
    # Example:
    # enabled: true
    enabled: false
    # Registered domain name on Cloudflare used for Vpbot.
    # Example:
    # domain: "vpbot.example.com"
    domain: ""
  # Custom Telegram commands.py file for Vpbot.
  commands: ""
  # Custom Telegram messages.py file for Vpbot.
  messages: ""

# Database configurations.
db:
  # The type of the database used by Vpbot.
  # Default: "postgresql"
  # Example:
  # type: "postgresql"
  type: ""
  # The name of the database used by Vpbot.
  # Example:
  # name: "vpbot"
  name: ""
  # The username or user account for accessing the Vpbot database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the Vpbot database's user.
  # Example:
  # password: "password"
  password: ""
  # The hostname or IP address of the Vpbot database server.
  # Example:
  # host: "vpbot.default.svc.cluster.local"
  host: ""
  # The port number on which the Vpbot database server is listening.
  # Default: "5432"
  # Example:
  # port: "5432"
  port: ""

# Resource requirements and limits for Vpbot containers.
resources:
  # Vpbot container resources.
  vpbot:
    # The minimum amount of resources required by Vpbot to run.
    requests:
      # The minimum amount of CPU resources required by Vpbot.
      # Example:
      # cpu: "20m"
      cpu: "50m"
      # The minimum amount of memory required by Vpbot.
      # Example:
      # memory: "250Mi"
      memory: "300Mi"
    # The maximum amount of resources allowed for Vpbot.
    limits:
      # The maximum amount of CPU resources allowed for Vpbot.
      # Example:
      # cpu: "50m"
      cpu: "200m"
      # The maximum amount of memory allowed for Vpbot.
      # Example:
      # memory: "450Mi"
      memory: "500Mi"
  # Scheduler container resources.
  scheduler:
    # The minimum amount of resources required by Scheduler to run.
    requests:
      # The minimum amount of CPU resources required by Scheduler.
      # Example:
      # cpu: "5m"
      cpu: "10m"
      # The minimum amount of memory required by Scheduler.
      # Example:
      # memory: "30Mi"
      memory: "100Mi"
    # The maximum amount of resources allowed for Scheduler.
    limits:
      # The maximum amount of CPU resources allowed for Scheduler.
      # Example:
      # cpu: "15m"
      cpu: "20m"
      # The maximum amount of memory allowed for Scheduler.
      # Example:
      # memory: "50Mi"
      memory: "200Mi"
  # Ngrok container resources.
  ngrok:
    # The minimum amount of resources required by Ngrok to run.
    requests:
      # The minimum amount of CPU resources required by Ngrok.
      # Example:
      # cpu: "5m"
      cpu: "10m"
      # The minimum amount of memory required by Ngrok.
      # Example:
      # memory: "30Mi"
      memory: "20Mi"
    # The maximum amount of resources allowed for Ngrok.
    limits:
      # The maximum amount of CPU resources allowed for Ngrok.
      # Example:
      # cpu: "15m"
      cpu: "20m"
      # The maximum amount of memory allowed for Ngrok.
      # Example:
      # memory: "50Mi"
      memory: "50Mi"
