# Default values for vpbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  vpbot:
    registry: ghcr.io
    repository: irfanhakim-as/quarantine-bot
    tag: ""
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the vpbot image

vpbot:
  debug: false # django debug mode
  log_size_limit: "4" # log file size limit in MiB
  secret: "secret" # django secret key
  user_pass: "secret" # default user password
  ngrok:
    enabled: false # enable ngrok
    auth_token: "secret" # ngrok auth token
  cloudflared:
    enabled: true # enable cloudflared
    domain: "" # cloudflared domain

telegram:
  webhook: "telegram/webhooks/" # telegram webhook path
  token: "secret" # telegram bot token
  admin_id: "secret" # admin telegram chat id
  devel_id: "secret" # admin telegram chat id

db:
  host: "postgres.default.svc.cluster.local" # remote postgres host
  name: "vpbot" # vpbot postgres database name
  user: "secret" # remote postgres user
  pass: "secret" # remote postgres user password

pvc:
  static:
    storage: "50Mi" # static files storage size
    storageClassName: "longhorn" # static files storage class name
  logs:
    storage: "50Mi" # log files storage size
    storageClassName: "longhorn" # log files storage class name
  migrations:
    storage: "50Mi" # migrations files storage size
    storageClassName: "longhorn" # migrations files storage class name

resources:
  requests:
    cpu: "10m" # vpbot cpu request
    memory: "10Mi" # vpbot memory request
  limits:
    cpu: "1" # vpbot cpu limit
    memory: "1Gi" # vpbot memory limit
