# Default values for vpbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  vpbot:
    registry: ghcr.io
    repository: irfanhakim-as/quarantine-bot
    tag: ""
    pullPolicy: IfNotPresent
  
  redis:
    registry: docker.io
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the vpbot image

vpbot:
  name: "Vpbot" # application name
  debug: false # django debug mode
  log_size_limit: "4" # log file size limit in MiB
  secret: "" # django secret key
  user_pass: "" # default user password
  celery_timezone: "Asia/Kuala_Lumpur" # scheduler timezone
  ngrok:
    enabled: false # enable ngrok
    auth_token: "" # ngrok auth token
  cloudflared:
    enabled: true # enable cloudflared
    domain: "" # cloudflared domain

telegram:
  webhook: "telegram/webhooks/" # telegram webhook path
  token: "" # telegram bot token
  admin_id: "" # admin telegram chat id
  devel_id: "" # admin telegram chat id

db:
  host: "postgres.default.svc.cluster.local" # database host
  type: "postgresql" # database type
  port: "5432" # database port
  name: "" # database name
  user: "" # database user
  pass: "" # database user password

pvc:
  static:
    storage: "50Mi" # static files storage size
    storageClassName: "longhorn" # static files storage class name
  logs:
    storage: "50Mi" # log files storage size
    storageClassName: "longhorn" # log files storage class name
  migrations:
    storage: "50Mi" # migrations files storage size
    storageClassName: "longhorn" # migrations files storage class name

resources:
  vpbot:
    requests:
      cpu: "10m" # vpbot cpu request
      memory: "250Mi" # vpbot memory request
    limits:
      cpu: "50m" # vpbot cpu limit
      memory: "500Mi" # vpbot memory limit
  redis:
    requests:
      cpu: "5m" # redis cpu request
      memory: "30Mi" # redis memory request
    limits:
      cpu: "15m" # redis cpu limit
      memory: "60Mi" # redis memory limit
