{{- $dataPersistence := .Values.storage.data.enabled }}
{{- $dataStorage := .Values.storage.data.storage | default "1Gi" | toString | quote }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- if $dataPersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-chartName-data-pvc
  labels:
    {{- include "chartName.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
{{- end }}
