{{- $releaseName := .Release.Name | toString }}
{{- $qbt := .Values.qbt.enabled }}
{{- $persistent_data := .Values.storage.data.enabled }}
{{- $persistent_downloads := .Values.storage.downloads.enabled }}
{{- $persistent_media := .Values.storage.media.enabled }}
{{- $smb := .Values.smb.enabled }}
{{- $downloadsSmb := .Values.storage.downloads.smb }}
{{- $mediaSmb := .Values.storage.media.smb }}
{{- $jackettConfigs := .Values.jackett.customConfigs }}
{{- $overseerrConfigs := .Values.overseerr.customConfigs }}
{{- $plexConfigs := .Values.plex.customConfigs }}
{{- $qbtConfigs := .Values.qbt.customConfigs }}
{{- $radarrConfigs := .Values.radarr.customConfigs }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
{{- $init_registry := .Values.image.init.registry | default "docker.io" | toString }}
{{- $init_repository := .Values.image.init.repository | default "busybox" | toString }}
{{- $init_tag := .Values.image.init.tag | default "1.34" | toString }}
{{- $init_pullPolicy := .Values.image.init.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $jackett_registry := .Values.image.jackett.registry | default "lscr.io" | toString }}
{{- $jackett_repository := .Values.image.jackett.repository | default "linuxserver/jackett" | toString }}
{{- $jackett_tag := .Values.image.jackett.tag | default "0.21.1700" | toString }}
{{- $jackett_pullPolicy := .Values.image.jackett.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $overseerr_registry := .Values.image.overseerr.registry | default "lscr.io" | toString }}
{{- $overseerr_repository := .Values.image.overseerr.repository | default "linuxserver/overseerr" | toString }}
{{- $overseerr_tag := .Values.image.overseerr.tag | default "v1.33.2-ls95" | toString }}
{{- $overseerr_pullPolicy := .Values.image.overseerr.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $plex_registry := .Values.image.plex.registry | default "index.docker.io" | toString }}
{{- $plex_repository := .Values.image.plex.repository | default "plexinc/pms-docker" | toString }}
{{- $plex_tag := .Values.image.plex.tag | default .Chart.AppVersion | toString }}
{{- $plex_pullPolicy := .Values.image.plex.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $qbt_registry := .Values.image.qbt.registry | default "lscr.io" | toString }}
{{- $qbt_repository := .Values.image.qbt.repository | default "linuxserver/qbittorrent" | toString }}
{{- $qbt_tag := .Values.image.qbt.tag | default "4.6.3-r0-ls310" | toString }}
{{- $qbt_pullPolicy := .Values.image.qbt.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $radarr_registry := .Values.image.radarr.registry | default "lscr.io" | toString }}
{{- $radarr_repository := .Values.image.radarr.repository | default "linuxserver/radarr" | toString }}
{{- $radarr_tag := .Values.image.radarr.tag | default "5.2.6.8376-ls202" | toString }}
{{- $radarr_pullPolicy := .Values.image.radarr.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $sonarr_registry := .Values.image.sonarr.registry | default "lscr.io" | toString }}
{{- $sonarr_repository := .Values.image.sonarr.repository | default "linuxserver/sonarr" | toString }}
{{- $sonarr_tag := .Values.image.sonarr.tag | default "4.0.1.929-ls224" | toString }}
{{- $sonarr_pullPolicy := .Values.image.sonarr.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $jackettResources := .Values.resources.jackett }}
{{- $overseerrResources := .Values.resources.overseerr }}
{{- $plexResources := .Values.resources.plex }}
{{- $qbtResources := .Values.resources.qbt }}
{{- $radarrResources := .Values.resources.radarr }}
{{- $sonarrResources := .Values.resources.sonarr }}
{{- $initScript := .Values.global.initScript | toString }}
{{- $dataMountPath := .Values.storage.data.mountPath | default "/config" | toString | quote }}
{{- $downloadsMountPath := .Values.storage.downloads.mountPath | default "/downloads" | toString | quote }}
{{- $mediaMountPath := .Values.storage.media.mountPath | default "/data" | toString | quote }}
{{- $dataSubPath := .Values.storage.data.subPath | toString }}
{{- $downloadsSubPath := .Values.storage.downloads.subPath | toString }}
{{- $mediaSubPath := .Values.storage.media.subPath | toString }}
{{- $gid := .Values.global.gid | default "1000" | int }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-plexmaster
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "plexmaster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plexmaster.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $initScript }}
      initContainers:
        - name: init
          image: {{ printf "%s/%s:%s" $init_registry $init_repository $init_tag | quote }}
          imagePullPolicy: {{ $init_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              {{- $initScript | nindent 14 }}
      {{- end }}
      containers:
        - name: jackett
          image: {{ printf "%s/%s:%s" $jackett_registry $jackett_repository $jackett_tag | quote }}
          imagePullPolicy: {{ $jackett_pullPolicy }}
          ports:
            - name: jackett
              containerPort: 9117
              protocol: TCP
          resources:
            {{- toYaml $jackettResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plexmaster-cm
            - configMapRef:
                name: {{ .Release.Name }}-jackett-cm
          {{- if or $persistent_data $persistent_downloads $jackettConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-jackett-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_downloads }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $downloadsSmb $smb }}smb{{- else }}downloads{{- end }}
              mountPath: {{ $downloadsMountPath }}
              {{- if $downloadsSubPath }}
              subPath: {{ $downloadsSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $jackettConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: jackett-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
        - name: overseerr
          image: {{ printf "%s/%s:%s" $overseerr_registry $overseerr_repository $overseerr_tag | quote }}
          imagePullPolicy: {{ $overseerr_pullPolicy }}
          ports:
            - name: overseerr
              containerPort: 5055
              protocol: TCP
          resources:
            {{- toYaml $overseerrResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plexmaster-cm
          {{- if or $persistent_data $persistent_media $overseerrConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-overseerr-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $overseerrConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: overseerr-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
        - name: plex
          image: {{ printf "%s/%s:%s" $plex_registry $plex_repository $plex_tag | quote }}
          imagePullPolicy: {{ $plex_pullPolicy }}
          ports:
            - name: plex
              containerPort: 32400
              protocol: TCP
          resources:
            {{- toYaml $plexResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plex-cm
            - secretRef:
                name: {{ .Release.Name }}-plex-secret
          {{- if or $persistent_data $persistent_media $plexConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-plex-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_media }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $mediaSmb $smb }}smb{{- else }}media{{- end }}
              mountPath: {{ $mediaMountPath }}
              {{- if $mediaSubPath }}
              subPath: {{ $mediaSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $plexConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: plex-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
        {{- if $qbt }}
        - name: qbittorrent
          image: {{ printf "%s/%s:%s" $qbt_registry $qbt_repository $qbt_tag | quote }}
          imagePullPolicy: {{ $qbt_pullPolicy }}
          ports:
            - name: qbt
              containerPort: 6881
              protocol: TCP
            - name: qbt-udp
              containerPort: 6881
              protocol: UDP
            - name: qbt-web
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml $qbtResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plexmaster-cm
            - configMapRef:
                name: {{ .Release.Name }}-qbittorrent-cm
          {{- if or $persistent_data $persistent_downloads $qbtConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-qbt-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_downloads }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $downloadsSmb $smb }}smb{{- else }}downloads{{- end }}
              mountPath: {{ $downloadsMountPath }}
              {{- if $downloadsSubPath }}
              subPath: {{ $downloadsSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $qbtConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: qbt-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
        {{- end }}
        - name: radarr
          image: {{ printf "%s/%s:%s" $radarr_registry $radarr_repository $radarr_tag | quote }}
          imagePullPolicy: {{ $radarr_pullPolicy }}
          ports:
            - name: radarr
              containerPort: 7878
              protocol: TCP
          resources:
            {{- toYaml $radarrResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plexmaster-cm
          {{- if or $persistent_data $persistent_downloads $persistent_media $radarrConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-radarr-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_downloads }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $downloadsSmb $smb }}smb{{- else }}downloads{{- end }}
              mountPath: {{ $downloadsMountPath }}
              {{- if $downloadsSubPath }}
              subPath: {{ $downloadsSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_media }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $mediaSmb $smb }}smb{{- else }}media{{- end }}
              mountPath: {{ $mediaMountPath }}
              {{- if $mediaSubPath }}
              subPath: {{ $mediaSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $radarrConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: radarr-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
        - name: sonarr
          image: {{ printf "%s/%s:%s" $sonarr_registry $sonarr_repository $sonarr_tag | quote }}
          imagePullPolicy: {{ $sonarr_pullPolicy }}
          ports:
            - name: sonarr
              containerPort: 8989
              protocol: TCP
          resources:
            {{- toYaml $sonarrResources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-plexmaster-cm
          {{- if or $persistent_data $persistent_downloads $persistent_media $sonarrConfigs }}
          volumeMounts:
            {{- if $persistent_data }}
            - name: {{ .Release.Name }}-plexmaster-sonarr-data
              mountPath: {{ $dataMountPath }}
              {{- if $dataSubPath }}
              subPath: {{ $dataSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_downloads }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $downloadsSmb $smb }}smb{{- else }}downloads{{- end }}
              mountPath: {{ $downloadsMountPath }}
              {{- if $downloadsSubPath }}
              subPath: {{ $downloadsSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- if $persistent_media }}
            - name: {{ .Release.Name }}-plexmaster-{{- if and $mediaSmb $smb }}smb{{- else }}media{{- end }}
              mountPath: {{ $mediaMountPath }}
              {{- if $mediaSubPath }}
              subPath: {{ $mediaSubPath | quote }}
              {{- end }}
            {{- end }}
            {{- range $sonarrConfigs }}
            - name: {{ $releaseName }}-custom-configs
              mountPath: {{ .mountPath }}
              subPath: sonarr-{{ .subPath }}
              readOnly: false
            {{- end }}
          {{- end }}
      {{- if or $persistent_data $persistent_downloads $persistent_media (or $jackettConfigs $overseerrConfigs $plexConfigs $qbtConfigs $radarrConfigs $sonarrConfigs) }}
      volumes:
        {{- if $persistent_data }}
        - name: {{ .Release.Name }}-plexmaster-jackett-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-jackett-data-pvc
        - name: {{ .Release.Name }}-plexmaster-overseerr-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-overseerr-data-pvc
        - name: {{ .Release.Name }}-plexmaster-plex-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-plex-data-pvc
        - name: {{ .Release.Name }}-plexmaster-qbt-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-qbt-data-pvc
        - name: {{ .Release.Name }}-plexmaster-radarr-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-radarr-data-pvc
        - name: {{ .Release.Name }}-plexmaster-sonarr-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-sonarr-data-pvc
        {{- end }}
        {{- if and $persistent_downloads (not (and $downloadsSmb $smb)) }}
        - name: {{ .Release.Name }}-plexmaster-downloads
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-downloads-pvc
        {{- end }}
        {{- if and $persistent_media (not (and $mediaSmb $smb)) }}
        - name: {{ .Release.Name }}-plexmaster-media
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-media-pvc
        {{- end }}
        {{- if and $smb (or $persistent_downloads $persistent_media) (or $downloadsSmb $mediaSmb) }}
        - name: {{ .Release.Name }}-plexmaster-smb
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-plexmaster-smb-pvc
        {{- end }}
        {{- if or $jackettConfigs $overseerrConfigs $plexConfigs $qbtConfigs $radarrConfigs $sonarrConfigs }}
        - name: {{ .Release.Name }}-custom-configs
          secret:
            secretName: {{ .Release.Name }}-custom-configs
        {{- end }}
      {{- end }}
      securityContext:
        fsGroup: {{ $gid }}
