{{- $ingress := .Values.ingress.enabled }}
{{- $clusterIssuer := .Values.ingress.clusterIssuer | default "letsencrypt-dns-prod" | toString | quote }}
{{- $jackettDomain := .Values.jackett.domain | toString | quote }}
{{- $plexDomain := .Values.plex.domain | toString | quote }}
{{- $qbtDomain := .Values.qbt.domain | toString | quote }}
{{- $sonarrDomain := .Values.sonarr.domain | toString | quote }}
{{- if $ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-plexmaster-ingress
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
    cert-manager.io/private-key-algorithm: "ECDSA"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.org/client-max-body-size: "100m"
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ $jackettDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-plexmaster-svc
                port:
                  name: jackett
            path: /
            pathType: Prefix
    - host: {{ $plexDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-plexmaster-svc
                port:
                  name: plex
            path: /
            pathType: Prefix
    - host: {{ $qbtDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-plexmaster-svc
                port:
                  name: qbt-web
            path: /
            pathType: Prefix
    - host: {{ $sonarrDomain }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-plexmaster-svc
                port:
                  name: sonarr
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ $jackettDomain }}
        - {{ $plexDomain }}
        - {{ $qbtDomain }}
        - {{ $sonarrDomain }}
      secretName: {{ .Release.Name }}-plexmaster-tls-cert
{{- end }}
