{{- $persistent_downloads := .Values.storage.downloads.enabled }}
{{- $persistent_media := .Values.storage.media.enabled }}
{{- $smb := .Values.smb.enabled }}
{{- $downloadsSmb := .Values.storage.downloads.smb }}
{{- $mediaSmb := .Values.storage.media.smb }}
{{- $mountOptions := .Values.smb.mountOptions }}
{{- $secretName := .Values.smb.secretName | default "smbcreds" | toString | quote }}
{{- $secretNamespace := .Values.smb.secretNamespace | default "default" | toString | quote }}
{{- $share := .Values.smb.share | toString | quote }}
{{- $storage := .Values.smb.pvStorage | default "100Gi" | toString | quote }}
{{- $storageClassName := .Values.smb.storageClassName | default "smb" | toString | quote }}
{{- $uid := .Values.global.uid | default "1000" | toString }}
{{- $gid := .Values.global.gid | default "1000" | toString }}
{{- if and $smb (or $persistent_downloads $persistent_media) (or $downloadsSmb $mediaSmb) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-plexmaster-smb-pv
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ $storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $storageClassName }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid={{ $uid }}
    - gid={{ $gid }}
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
    {{- range $option := $mountOptions }}
    - {{ $option }}
    {{- end }}
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: {{ .Release.Name }}-plexmaster-smb-pv
    volumeAttributes:
      source: {{ $share }}
    nodeStageSecretRef:
      name: {{ $secretName }}
      namespace: {{ $secretNamespace }}
{{- end }}
