{{- $persistent_data := .Values.storage.data.enabled }}
{{- $persistent_downloads := .Values.storage.downloads.enabled }}
{{- $persistent_media := .Values.storage.media.enabled }}
{{- $smb := .Values.smb.enabled }}
{{- $downloadsSmb := .Values.storage.downloads.smb }}
{{- $mediaSmb := .Values.storage.media.smb }}
{{- $dataStorage := .Values.storage.data.storage | default "1Gi" | toString | quote }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- $downloadsStorage := .Values.storage.downloads.storage | default "1Gi" | toString | quote }}
{{- $downloadsStorageClassName := .Values.storage.downloads.storageClassName | default "longhorn" | toString | quote }}
{{- $mediaStorage := .Values.storage.media.storage | default "1Gi" | toString | quote }}
{{- $mediaStorageClassName := .Values.storage.media.storageClassName | default "longhorn" | toString | quote }}
{{- $smbStorage := .Values.smb.pvcStorage | default "1Gi" | toString | quote }}
{{- $smbStorageClassName := .Values.smb.storageClassName | default "smb" | toString | quote }}
{{- if $persistent_data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-jackett-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-overseerr-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-plex-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-qbt-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-radarr-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-sonarr-data-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $dataStorage }}
  storageClassName: {{ $dataStorageClassName }}
{{- end }}
{{- if and $persistent_downloads (not (and $downloadsSmb $smb)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-downloads-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $downloadsStorage }}
  storageClassName: {{ $downloadsStorageClassName }}
{{- end }}
{{- if and $persistent_media (not (and $mediaSmb $smb)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-media-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $mediaStorage }}
  storageClassName: {{ $mediaStorageClassName }}
{{- end }}
{{- if and $smb (or $persistent_downloads $persistent_media) (or $downloadsSmb $mediaSmb) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-plexmaster-smb-pvc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $smbStorage }}
  volumeName: {{ .Release.Name }}-plexmaster-smb-pv
  storageClassName: {{ $smbStorageClassName }}
{{- end }}
