{{- $plex_claim := .Values.plex.claim | toString | b64enc }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plex_claim }}
{{- if or $sonarrConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-configs
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $sonarrConfigs }}
  sonarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
