{{- $plex_claim := .Values.plex.claim | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plex_claim }}
