{{- $plex_claim := .Values.plex.claim | toString | b64enc }}
{{- $jackettConfigs := .Values.jackett.customConfigs }}
{{- $overseerrConfigs := .Values.overseerr.customConfigs }}
{{- $plexConfigs := .Values.plex.customConfigs }}
{{- $qbtConfigs := .Values.qbt.customConfigs }}
{{- $radarrConfigs := .Values.radarr.customConfigs }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plex_claim }}
{{- if or $jackettConfigs $overseerrConfigs $plexConfigs $qbtConfigs $radarrConfigs $sonarrConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-configs
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $jackettConfigs }}
  jackett-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $overseerrConfigs }}
  overseerr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $plexConfigs }}
  plex-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $qbtConfigs }}
  qbt-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $radarrConfigs }}
  radarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $sonarrConfigs }}
  sonarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
