{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-plexmaster-svc
  labels:
    {{- include "plexmaster.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: 9117
      targetPort: jackett
      protocol: TCP
      name: jackett
    - port: 32400
      targetPort: plex
      protocol: TCP
      name: plex
    - port: 6881
      targetPort: qbt
      protocol: TCP
      name: qbt
    - port: 6881
      targetPort: qbt-udp
      protocol: UDP
      name: qbt-udp
    - port: 8080
      targetPort: qbt-web
      protocol: TCP
      name: qbt-web
    - port: 7878
      targetPort: radarr
      protocol: TCP
      name: radarr
    - port: 8989
      targetPort: sonarr
      protocol: TCP
      name: sonarr
  selector:
    {{- include "plexmaster.selectorLabels" . | nindent 4 }}
