{{- $password := .Values.yuzu.room.password }}
{{- $token := .Values.yuzu.token | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-yuzu-multiplayer-secret
  labels:
    {{- include "yuzu-multiplayer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $password }}
  password: {{ $password | toString | b64enc }}
  {{- end }}
  token: {{ $token }}
