{{- $bazarr := .Values.bazarr.enabled }}
{{- $flaresolverr := .Values.flaresolverr.enabled }}
{{- $jackett := .Values.jackett.enabled }}
{{- $overseerr := .Values.overseerr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $radarr := .Values.radarr.enabled }}
{{- $sonarr := .Values.sonarr.enabled }}
{{- $uid := .Values.global.uid | default "1000" | toString | quote }}
{{- $gid := .Values.global.gid | default "1000" | toString | quote }}
{{- $fsLogHtml := .Values.flaresolverr.logHtml | default "false" | toString | quote }}
{{- $fsLogLevel := .Values.flaresolverr.logLevel | default "info" | toString | quote }}
{{- $fsTimezone := .Values.flaresolverr.timezone | default "UTC" | toString | quote }}
{{- $jackettAutoUpdate := .Values.jackett.autoUpdate | default "true" | toString | quote }}
{{- if or $bazarr $jackett $overseerr $qbt $radarr $sonarr }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flex-lsio-cm
  labels:
    {{- include "flex.labels" . | nindent 4 }}
data:
  PUID: {{ $uid }}
  PGID: {{ $gid }}
{{- end }}
{{- if $flaresolverr }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flex-flaresolverr-cm
  labels:
    {{- include "flex.labels" . | nindent 4 }}
data:
  LOG_HTML: {{ $fsLogHtml }}
  LOG_LEVEL: {{ $fsLogLevel }}
  TZ: {{ $fsTimezone }}
{{- end }}
{{- if $jackett }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flex-jackett-cm
  labels:
    {{- include "flex.labels" . | nindent 4 }}
data:
  AUTO_UPDATE: {{ $jackettAutoUpdate }}
{{- end }}
{{- if $plex }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flex-plex-cm
  labels:
    {{- include "flex.labels" . | nindent 4 }}
data:
  PLEX_UID: {{ $uid }}
  PLEX_GID: {{ $gid }}
{{- end }}
{{- if $qbt }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flex-qbt-cm
  labels:
    {{- include "flex.labels" . | nindent 4 }}
data:
  TORRENTING_PORT: "6881"
  WEBUI_PORT: "8080"
{{- end }}
