{{- $ingress := .Values.ingress.enabled }}
{{- $clusterIssuer := .Values.ingress.clusterIssuer | default "letsencrypt-dns-prod" | toString | quote }}
{{- $customAnnotations := .Values.ingress.customAnnotations }}
{{- $releaseName := .Release.Name | toString }}
{{- if $ingress }}
  {{- $services := list
    (dict "port" "bazarr" "enabled" .Values.bazarr.enabled "ingress" .Values.bazarr.ingress "domains" .Values.bazarr.domains)
    (dict "port" "ersatztv" "enabled" .Values.ersatztv.enabled "ingress" .Values.ersatztv.ingress "domains" .Values.ersatztv.domains)
    (dict "port" "jackett" "enabled" .Values.jackett.enabled "ingress" .Values.jackett.ingress "domains" .Values.jackett.domains)
    (dict "port" "jellyfin-web" "enabled" .Values.jellyfin.enabled "ingress" .Values.jellyfin.ingress "domains" .Values.jellyfin.domains)
    (dict "port" "jellyseerr" "enabled" .Values.jellyseerr.enabled "ingress" .Values.jellyseerr.ingress "domains" .Values.jellyseerr.domains)
    (dict "port" "lidarr" "enabled" .Values.lidarr.enabled "ingress" .Values.lidarr.ingress "domains" .Values.lidarr.domains)
    (dict "port" "overseerr" "enabled" .Values.overseerr.enabled "ingress" .Values.overseerr.ingress "domains" .Values.overseerr.domains)
    (dict "port" "plex" "enabled" .Values.plex.enabled "ingress" .Values.plex.ingress "domains" .Values.plex.domains)
    (dict "port" "qbt-web" "enabled" .Values.qbt.enabled "ingress" .Values.qbt.ingress "domains" .Values.qbt.domains)
    (dict "port" "radarr" "enabled" .Values.radarr.enabled "ingress" .Values.radarr.ingress "domains" .Values.radarr.domains)
    (dict "port" "sonarr" "enabled" .Values.sonarr.enabled "ingress" .Values.sonarr.ingress "domains" .Values.sonarr.domains)
  }}
  {{- range $services }}
    {{- $svc := . }}
    {{- if and $svc.enabled $svc.ingress $svc.domains }}
      {{- range $svc.domains }}
        {{- $tls := ne .tls false }}
        {{- $domainCustomAnnotations := .customAnnotations }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-{{ .name | replace "." "-" }}-flex-ingress
  labels:
    {{- include "flex.labels" $ | nindent 4 }}
  annotations:
  {{- if $tls }}
    cert-manager.io/cluster-issuer: {{ $clusterIssuer }}
    cert-manager.io/private-key-algorithm: "ECDSA"
  {{- end }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.org/client-max-body-size: "100m"
  {{- range $customAnnotations }}
    {{ printf "%s/%s" (.prefix | default "nginx.ingress.kubernetes.io") .name }}: {{ .value | quote }}
  {{- end }}
  {{- range $domainCustomAnnotations }}
    {{ printf "%s/%s" (.prefix | default "nginx.ingress.kubernetes.io") .name }}: {{ .value | quote }}
  {{- end }}
spec:
  ingressClassName: "nginx"
  rules:
    - host: {{ .name | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $releaseName }}-flex-svc
                port:
                  name: {{ $svc.port }}
            path: /
            pathType: Prefix
  {{- if $tls }}
  tls:
    - hosts:
        - {{ .name | quote }}
      secretName: {{ $releaseName }}-{{ .name | replace "." "-" }}-flex-tls-cert
  {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
