{{- $globalPersistence := .Values.storage.global.enabled }}
{{- $downloadsPersistence := and .Values.storage.downloads.enabled (not $globalPersistence) }}
{{- $mediaPersistence := and .Values.storage.media.enabled (not $globalPersistence) }}
{{- $smb := .Values.smb.enabled }}
{{- $downloadsSmb := and $downloadsPersistence $smb .Values.storage.downloads.smb }}
{{- $globalSmb := and $globalPersistence $smb .Values.storage.global.smb }}
{{- $mediaSmb := and $mediaPersistence $smb .Values.storage.media.smb }}
{{- $smbMountOptions := .Values.smb.mountOptions }}
{{- $smbSecretName := .Values.smb.secretName | default "smbcreds" | toString | quote }}
{{- $smbSecretNamespace := .Values.smb.secretNamespace | default "default" | toString | quote }}
{{- $smbShare := .Values.smb.share | toString | quote }}
{{- $smbAccessMode := .Values.smb.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $smbStorage := .Values.smb.pvStorage | default "100Gi" | toString | quote }}
{{- $smbStorageClassName := .Values.smb.storageClassName | default "smb" | toString | quote }}
{{- $uid := .Values.global.uid | default "1000" | toString }}
{{- $gid := .Values.global.gid | default "1000" | toString }}
{{- if or $downloadsSmb $globalSmb $mediaSmb }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-flex-smb-pv
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ $smbStorage }}
  accessModes:
    - {{ $smbAccessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $smbStorageClassName }}
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid={{ $uid }}
    - gid={{ $gid }}
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  {{- range $option := $smbMountOptions }}
    - {{ $option }}
  {{- end }}
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: {{ .Release.Name }}-flex-smb-pv
    volumeAttributes:
      source: {{ $smbShare }}
    nodeStageSecretRef:
      name: {{ $smbSecretName }}
      namespace: {{ $smbSecretNamespace }}
{{- end }}
