{{- $bazarr := .Values.bazarr.enabled }}
{{- $jackett := .Values.jackett.enabled }}
{{- $jellyfin := .Values.jellyfin.enabled }}
{{- $overseerr := .Values.overseerr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $radarr := .Values.radarr.enabled }}
{{- $sonarr := .Values.sonarr.enabled }}
{{- $dataPersistence := .Values.storage.data.enabled }}
{{- $globalPersistence := .Values.storage.global.enabled }}
{{- $downloadsPersistence := and .Values.storage.downloads.enabled (not $globalPersistence) }}
{{- $mediaPersistence := and .Values.storage.media.enabled (not $globalPersistence) }}
{{- $smb := .Values.smb.enabled }}
{{- $downloadsSmb := and $downloadsPersistence $smb .Values.storage.downloads.smb }}
{{- $globalSmb := and $globalPersistence $smb .Values.storage.global.smb }}
{{- $mediaSmb := and $mediaPersistence $smb .Values.storage.media.smb }}
{{- $dataAccessMode := .Values.storage.data.accessMode | default "ReadWriteOnce" | toString | quote }}
{{- $dataStorage := .Values.storage.data.storage | default "1Gi" | toString }}
{{- $dataStorageClassName := .Values.storage.data.storageClassName | default "longhorn" | toString | quote }}
{{- $downloadsAccessMode := .Values.storage.downloads.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $downloadsStorage := .Values.storage.downloads.storage | default "1Gi" | toString | quote }}
{{- $downloadsStorageClassName := .Values.storage.downloads.storageClassName | default "longhorn" | toString | quote }}
{{- $globalAccessMode := .Values.storage.global.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $globalStorage := .Values.storage.global.storage | default "1Gi" | toString | quote }}
{{- $globalStorageClassName := .Values.storage.global.storageClassName | default "longhorn" | toString | quote }}
{{- $mediaAccessMode := .Values.storage.media.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $mediaStorage := .Values.storage.media.storage | default "1Gi" | toString | quote }}
{{- $mediaStorageClassName := .Values.storage.media.storageClassName | default "longhorn" | toString | quote }}
{{- $smbAccessMode := .Values.smb.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $smbStorage := .Values.smb.pvcStorage | default "1Gi" | toString | quote }}
{{- $smbStorageClassName := .Values.smb.storageClassName | default "smb" | toString | quote }}
{{- $bazarrDataStorage := .Values.bazarr.dataStorage | default $dataStorage | toString | quote }}
{{- $jackettDataStorage := .Values.jackett.dataStorage | default $dataStorage | toString | quote }}
{{- $jellyfinDataStorage := .Values.jellyfin.dataStorage | default $dataStorage | toString | quote }}
{{- $overseerrDataStorage := .Values.overseerr.dataStorage | default $dataStorage | toString | quote }}
{{- $plexDataStorage := .Values.plex.dataStorage | default $dataStorage | toString | quote }}
{{- $qbtDataStorage := .Values.qbt.dataStorage | default $dataStorage | toString | quote }}
{{- $radarrDataStorage := .Values.radarr.dataStorage | default $dataStorage | toString | quote }}
{{- $sonarrDataStorage := .Values.sonarr.dataStorage | default $dataStorage | toString | quote }}
{{- if $dataPersistence }}
  {{- if $bazarr }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-bazarr-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $bazarrDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $jackett }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-jackett-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $jackettDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $jellyfin }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-jellyfin-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $jellyfinDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $overseerr }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-overseerr-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $overseerrDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $plex }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-plex-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $plexDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $qbt }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-qbt-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $qbtDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $radarr }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-radarr-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $radarrDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
  {{- if $sonarr }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-sonarr-data-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $dataAccessMode }}
  resources:
    requests:
      storage: {{ $sonarrDataStorage }}
  storageClassName: {{ $dataStorageClassName }}
  {{- end }}
{{- end }}
{{- if and $downloadsPersistence (not $downloadsSmb) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-downloads-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $downloadsAccessMode }}
  resources:
    requests:
      storage: {{ $downloadsStorage }}
  storageClassName: {{ $downloadsStorageClassName }}
{{- end }}
{{- if and $globalPersistence (not $globalSmb) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-global-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $globalAccessMode }}
  resources:
    requests:
      storage: {{ $globalStorage }}
  storageClassName: {{ $globalStorageClassName }}
{{- end }}
{{- if and $mediaPersistence (not $mediaSmb) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-media-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $mediaAccessMode }}
  resources:
    requests:
      storage: {{ $mediaStorage }}
  storageClassName: {{ $mediaStorageClassName }}
{{- end }}
{{- if or $downloadsSmb $globalSmb $mediaSmb }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-flex-smb-pvc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $smbAccessMode }}
  resources:
    requests:
      storage: {{ $smbStorage }}
  volumeName: {{ .Release.Name }}-flex-smb-pv
  storageClassName: {{ $smbStorageClassName }}
{{- end }}
