{{- $bazarr := .Values.bazarr.enabled }}
{{- $flaresolverr := .Values.flaresolverr.enabled }}
{{- $jackett := .Values.jackett.enabled }}
{{- $overseerr := .Values.overseerr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $radarr := .Values.radarr.enabled }}
{{- $sonarr := .Values.sonarr.enabled }}
{{- $plexClaim := .Values.plex.claim | toString | b64enc }}
{{- $bazarrConfigs := .Values.bazarr.customConfigs }}
{{- $bazarrConfigs = ternary $bazarrConfigs (list) (and $bazarr (not (empty $bazarrConfigs))) }}
{{- $fsConfigs := .Values.flaresolverr.customConfigs }}
{{- $fsConfigs = ternary $fsConfigs (list) (and $flaresolverr (not (empty $fsConfigs))) }}
{{- $jackettConfigs := .Values.jackett.customConfigs }}
{{- $jackettConfigs = ternary $jackettConfigs (list) (and $jackett (not (empty $jackettConfigs))) }}
{{- $overseerrConfigs := .Values.overseerr.customConfigs }}
{{- $overseerrConfigs = ternary $overseerrConfigs (list) (and $overseerr (not (empty $overseerrConfigs))) }}
{{- $plexConfigs := .Values.plex.customConfigs }}
{{- $plexConfigs = ternary $plexConfigs (list) (and $plex (not (empty $plexConfigs))) }}
{{- $qbtConfigs := .Values.qbt.customConfigs }}
{{- $qbtConfigs = ternary $qbtConfigs (list) (and $qbt (not (empty $qbtConfigs))) }}
{{- $radarrConfigs := .Values.radarr.customConfigs }}
{{- $radarrConfigs = ternary $radarrConfigs (list) (and $radarr (not (empty $radarrConfigs))) }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
{{- $sonarrConfigs = ternary $sonarrConfigs (list) (and $sonarr (not (empty $sonarrConfigs))) }}
{{- if $plex }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plexClaim }}
{{- end }}
{{- if or $bazarrConfigs $fsConfigs $jackettConfigs $overseerrConfigs $plexConfigs $qbtConfigs $radarrConfigs $sonarrConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-configs
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $bazarrConfigs }}
  bazarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $fsConfigs }}
  flaresolverr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $jackettConfigs }}
  jackett-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $overseerrConfigs }}
  overseerr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $plexConfigs }}
  plex-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $qbtConfigs }}
  qbt-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $radarrConfigs }}
  radarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $sonarrConfigs }}
  sonarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
