{{- $bazarr := .Values.bazarr.enabled }}
{{- $flaresolverr := .Values.flaresolverr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $plexClaim := .Values.plex.claim | toString | b64enc }}
{{- $bazarrConfigs := .Values.bazarr.customConfigs }}
{{- $bazarrConfigs = ternary $bazarrConfigs (list) (and $bazarr (not (empty $bazarrConfigs))) }}
{{- $fsConfigs := .Values.flaresolverr.customConfigs }}
{{- $fsConfigs = ternary $fsConfigs (list) (and $flaresolverr (not (empty $fsConfigs))) }}
{{- $jackettConfigs := .Values.jackett.customConfigs }}
{{- $overseerrConfigs := .Values.overseerr.customConfigs }}
{{- $plexConfigs := .Values.plex.customConfigs }}
{{- $plexConfigs = ternary $plexConfigs (list) (and $plex (not (empty $plexConfigs))) }}
{{- $qbtConfigs := .Values.qbt.customConfigs }}
{{- $qbtConfigs = ternary $qbtConfigs (list) (and $qbt (not (empty $qbtConfigs))) }}
{{- $radarrConfigs := .Values.radarr.customConfigs }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
{{- if $plex }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plexClaim }}
{{- end }}
{{- if or $bazarrConfigs $fsConfigs $jackettConfigs $overseerrConfigs $plexConfigs $qbtConfigs $radarrConfigs $sonarrConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-configs
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $bazarrConfigs }}
  bazarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $fsConfigs }}
  flaresolverr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $jackettConfigs }}
  jackett-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $overseerrConfigs }}
  overseerr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $plexConfigs }}
  plex-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $qbtConfigs }}
  qbt-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $radarrConfigs }}
  radarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $sonarrConfigs }}
  sonarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
