{{- $bazarr := .Values.bazarr.enabled }}
{{- $flaresolverr := .Values.flaresolverr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $plex_claim := .Values.plex.claim | toString | b64enc }}
{{- $bazarrConfigs := .Values.bazarr.customConfigs }}
{{- $fsConfigs := .Values.flaresolverr.customConfigs }}
{{- $jackettConfigs := .Values.jackett.customConfigs }}
{{- $overseerrConfigs := .Values.overseerr.customConfigs }}
{{- $plexConfigs := .Values.plex.customConfigs }}
{{- $qbtConfigs := .Values.qbt.customConfigs }}
{{- $radarrConfigs := .Values.radarr.customConfigs }}
{{- $sonarrConfigs := .Values.sonarr.customConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-plex-secret
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  PLEX_CLAIM: {{ $plex_claim }}
{{- if or (and $bazarr $bazarrConfigs) (and $flaresolverr $fsConfigs) $jackettConfigs $overseerrConfigs (and $plex $plexConfigs) (and $qbt $qbtConfigs) $radarrConfigs $sonarrConfigs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-custom-configs
  labels:
    {{- include "flex.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $bazarr }}
    {{- range $bazarrConfigs }}
  bazarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $flaresolverr }}
    {{- range $fsConfigs }}
  flaresolverr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- range $jackettConfigs }}
  jackett-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $overseerrConfigs }}
  overseerr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- if $plex }}
    {{- range $plexConfigs }}
  plex-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if $qbt }}
    {{- range $qbtConfigs }}
  qbt-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- range $radarrConfigs }}
  radarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
  {{- range $sonarrConfigs }}
  sonarr-{{ .subPath }}: |-
    {{- .config | toString | b64enc | nindent 4 }}
  {{- end }}
{{- end }}
