{{- $bazarr := .Values.bazarr.enabled }}
{{- $flaresolverr := .Values.flaresolverr.enabled }}
{{- $plex := .Values.plex.enabled }}
{{- $qbt := .Values.qbt.enabled }}
{{- $bazarrPort := .Values.service.bazarr.port | default "6767" | toString }}
{{- $flaresolverrPort := .Values.service.flaresolverr.port | default "8191" | toString }}
{{- $jackettPort := .Values.service.jackett.port | default "9117" | toString }}
{{- $overseerrPort := .Values.service.overseerr.port | default "5055" | toString }}
{{- $plexPort := .Values.service.plex.port | default "32400" | toString }}
{{- $qbtPort := .Values.service.qbt.port | default "8080" | toString }}
{{- $radarrPort := .Values.service.radarr.port | default "7878" | toString }}
{{- $sonarrPort := .Values.service.sonarr.port | default "8989" | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flex-svc
  labels:
    {{- include "flex.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
  {{- if $bazarr }}
    - port: {{ int $bazarrPort }}
      targetPort: bazarr
      protocol: TCP
      name: bazarr
  {{- end }}
  {{- if $flaresolverr }}
    - port: {{ int $flaresolverrPort }}
      targetPort: flaresolverr
      protocol: TCP
      name: flaresolverr
  {{- end }}
    - port: {{ int $jackettPort }}
      targetPort: jackett
      protocol: TCP
      name: jackett
    - port: {{ int $overseerrPort }}
      targetPort: overseerr
      protocol: TCP
      name: overseerr
  {{- if $plex }}
    - port: {{ int $plexPort }}
      targetPort: plex
      protocol: TCP
      name: plex
  {{- end }}
  {{- if $qbt }}
    - port: 6881
      targetPort: qbt
      protocol: TCP
      name: qbt
    - port: 6881
      targetPort: qbt-udp
      protocol: UDP
      name: qbt-udp
    - port: {{ int $qbtPort }}
      targetPort: qbt-web
      protocol: TCP
      name: qbt-web
  {{- end }}
    - port: {{ int $radarrPort }}
      targetPort: radarr
      protocol: TCP
      name: radarr
    - port: {{ int $sonarrPort }}
      targetPort: sonarr
      protocol: TCP
      name: sonarr
  selector:
    {{- include "flex.selectorLabels" . | nindent 4 }}
