apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-createdb-cm
  labels:
    {{- include "postgres-createdb.labels" . | nindent 4 }}
data:
  DB_HOST: "{{ .Values.configmap.postgres.DB_HOST }}"
  DB_NAME: "{{ .Values.configmap.postgres.DB_NAME }}"
