apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-createdb-secret
  labels:
    {{- include "postgres-createdb.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.postgres.DB_USER | b64enc }}
  DB_PASS: {{ .Values.secret.postgres.DB_PASS | b64enc }}
  ROOT_USER: {{ .Values.secret.postgres.ROOT_USER | b64enc }}
  ROOT_PASS: {{ .Values.secret.postgres.ROOT_PASS | b64enc }}
