{{- $domain := .Values.telego.cloudflared.domain | default "localhost" | toString }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.telego.name | toString | quote }}
  DEBUG: {{ .Values.telego.debug | toString | quote }}
  DJANGO_WEBHOOK_URI: {{ .Values.telego.webhook | toString | quote }}
  CELERY_BROKER: redis://{{ .Release.Name }}-telego-redis-svc
  CELERY_BACKEND: redis://{{ .Release.Name }}-telego-redis-svc
  CELERY_TIMEZONE: {{ .Values.telego.celery_timezone | toString | quote }}
  NGROK: {{ .Values.telego.ngrok.enabled | toString | quote }}
  {{- if .Values.telego.cloudflared.enabled }}
  DOMAIN: {{ .Values.telego.cloudflared.domain | toString | quote }}
  {{- end }}
{{- if .Values.telego.commands }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-commands-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  commands.py: |-
    {{ .Values.telego.commands | toString | nindent 4 | trim }}
{{- end }}
{{- if .Values.telego.messages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-messages-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  messages.py: |-
    {{ .Values.telego.messages | toString | nindent 4 | trim }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-site-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    <VirtualHost *:80>
      {{ "ServerName $domain:443" | replace "$domain" $domain }}
      UseCanonicalName On
      ServerAdmin support@domain.org
      DocumentRoot /telego
      WSGIScriptAlias / /telego/telego/wsgi.py
      {{ "WSGIDaemonProcess $domain python-path=/telego" | replace "$domain" $domain }}
      {{ "WSGIProcessGroup $domain" | replace "$domain" $domain }}
      
      <Directory /telego/telego>
        <Files wsgi.py>
          Require all granted
        </Files>
      </Directory>

      Alias /static /static
      <Directory /static>
        Require all granted
      </Directory>

      ErrorLog /telego/logs/apache.error.log
      CustomLog /telego/logs/apache.access.log combined
    </VirtualHost>
