{{- $name := .Values.telego.name | default "Telego" | toString | quote }}
{{- $debug := .Values.telego.debug | default "false" | toString | quote }}
{{- $webhook := .Values.telego.telegram.webhook | default "telegram/webhooks/" | toString | quote }}
{{- $redis_service := printf "redis://%s-telego-svc" .Release.Name | quote }}
{{- $scheduler_timezone := .Values.telego.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $domain := .Values.telego.cloudflared.domain | default "localhost" | toString }}
{{- $clean_model := .Values.telego.scheduler.schedule.clean_model | default "0" | toString | quote }}
{{- $object_scheduler := .Values.telego.scheduler.schedule.object_scheduler | default "*/2" | toString | quote }}
{{- $apscheduler := .Values.telego.scheduler.apscheduler }}
{{- $celery := .Values.telego.scheduler.celery }}
{{- $cloudflared := .Values.telego.cloudflared.enabled }}
{{- $ngrok := .Values.telego.ngrok.enabled }}
{{- $commands := .Values.telego.commands }}
{{- $messages := .Values.telego.messages }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  APP_NAME: {{ $name }}
  DEBUG: {{ $debug }}
  TELEGRAM_WEBHOOK_PATH: {{ $webhook }}
  NGROK: {{ $ngrok | toString | quote }}
  {{- if or $apscheduler $celery }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  {{- end }}
  {{- if $celery }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  {{- end }}
  {{- if $cloudflared }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-site-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "telego.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
{{- if $apscheduler }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-apscheduler-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    {{- include "telego.apscheduler-entrypoint-sh" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-scheduler-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  apps.py: |-
    {{- include "telego.apscheduler-apps-py" . | nindent 4 }}
  tasks.py: |-
    {{- include "telego.apscheduler-tasks-py" . | replace "CLEAN_MODEL_HOURS" $clean_model | replace "OBJECT_SCHEDULER_SECONDS" $object_scheduler | nindent 4 }}
{{- else if $celery }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-default-celery-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  celeryd: |-
    {{- include "telego.default-celeryd" . | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-initd-celery-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  celerybeat: |-
    {{- include "telego.initd-celerybeat" . | nindent 4 }}
{{- end }}
{{- if $commands }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-commands-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  commands.py: |-
    {{ $commands | toString | nindent 4 | trim }}
{{- end }}
{{- if $messages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-messages-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  messages.py: |-
    {{ $messages | toString | nindent 4 | trim }}
{{- end }}
