{{- $name := .Values.telego.name | default "Telego" | toString | quote }}
{{- $debug := .Values.telego.debug | default "false" | toString | quote }}
{{- $webhook := .Values.telego.telegram.webhook | default "telegram/webhooks/" | toString | quote }}
{{- $redis_service := printf "redis://%s-telego-svc" .Release.Name | quote }}
{{- $scheduler_timezone := .Values.telego.scheduler.timezone | default "Asia/Kuala_Lumpur" | toString | quote }}
{{- $domain := .Values.telego.cloudflared.domain | default "localhost" | toString }}
{{- $cloudflared := .Values.telego.cloudflared.enabled }}
{{- $ngrok := .Values.telego.ngrok.enabled }}
{{- $commands := .Values.telego.commands }}
{{- $messages := .Values.telego.messages }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  APP_NAME: {{ $name }}
  DEBUG: {{ $debug }}
  DJANGO_WEBHOOK_URI: {{ $webhook }}
  CELERY_BROKER: {{ $redis_service }}
  CELERY_BACKEND: {{ $redis_service }}
  SCHEDULER_TIMEZONE: {{ $scheduler_timezone }}
  NGROK: {{ $ngrok | toString | quote }}
  {{- if $cloudflared }}
  DOMAIN: {{ $domain | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-site-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  site-config.conf: |-
    {{- include "telego.site-config-conf" . | replace "DOMAIN" $domain | nindent 4 }}
{{- if $commands }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-commands-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  commands.py: |-
    {{ $commands | toString | nindent 4 | trim }}
{{- end }}
{{- if $messages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-messages-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  messages.py: |-
    {{ $messages | toString | nindent 4 | trim }}
{{- end }}
