apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  DB_TYPE: {{ .Values.db.type | toString | quote }}
  DEBUG: {{ .Values.telego.debug | toString | quote }}
  DJANGO_WEBHOOK_URI: {{ .Values.telego.webhook | toString | quote }}
  NGROK: {{ .Values.telego.ngrok.enabled | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-database-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.db.host | toString | quote }}
  DB_PORT: {{ .Values.db.port | toString | quote }}
  DB_NAME: {{ .Values.db.name | toString | quote }}
{{- if .Values.telego.commands }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-commands-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  commands.py: |-
    {{ .Values.telego.commands | toString | nindent 4 | trim }}
{{- end }}
{{- if .Values.telego.messages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-telego-messages-cm
  labels:
    {{- include "telego.labels" . | nindent 4 }}
data:
  messages.py: |-
    {{ .Values.telego.messages | toString | nindent 4 | trim }}
{{- end }}
