{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $telego_registry := .Values.image.telego.registry | default "ghcr.io" | toString }}
{{- $telego_repository := .Values.image.telego.repository | default "irfanhakim-as/telego" | toString }}
{{- $telego_tag := .Values.image.telego.tag | default .Chart.AppVersion | toString }}
{{- $telego_pullPolicy := .Values.image.telego.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $redis_registry := .Values.image.redis.registry | default "docker.io" | toString }}
{{- $redis_repository := .Values.image.redis.repository | default "redis" | toString }}
{{- $redis_tag := .Values.image.redis.tag | default "alpine" | toString }}
{{- $redis_pullPolicy := .Values.image.redis.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $ngrok_registry := .Values.image.ngrok.registry | default "docker.io" | toString }}
{{- $ngrok_repository := .Values.image.ngrok.repository | default "wernight/ngrok" | toString }}
{{- $ngrok_tag := .Values.image.ngrok.tag | default "latest" | toString }}
{{- $ngrok_pullPolicy := .Values.image.ngrok.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $cloudflared := .Values.telego.cloudflared.enabled }}
{{- $persistence := .Values.telego.persistence.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-telego
  labels:
    {{- include "telego.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "telego.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        "helm.sh/hook-weight": "1"
      {{- end }}
      labels:
        {{- include "telego.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: telego
          image: {{ printf "%s/%s:%s" $telego_registry $telego_repository $telego_tag | quote }}
          imagePullPolicy: {{ $telego_pullPolicy }}
          ports:
            - name: telego
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.telego | nindent 12 }}
          {{- if $cloudflared }}
          env:
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-telego-cm
                  key: DOMAIN
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-telego-cm
            - secretRef:
                name: {{ .Release.Name }}-telego-secret
            - secretRef:
                name: {{ .Release.Name }}-telego-database-secret
          volumeMounts:
            - name: {{ .Release.Name }}-telego-site-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: site-config.conf
              readOnly: true
            {{- if $persistence }}
            - name: {{ .Release.Name }}-telego-logs
              mountPath: /telego/logs
            {{- end }}
            {{- if .Values.telego.commands }}
            - name: {{ .Release.Name }}-telego-commands-cm
              mountPath: /telego/telego/commands.py
              subPath: commands.py
              readOnly: true
            {{- end }}
            {{- if .Values.telego.messages }}
            - name: {{ .Release.Name }}-telego-messages-cm
              mountPath: /telego/telego/messages.py
              subPath: messages.py
              readOnly: true
            {{- end }}
        - name: redis
          image: {{ printf "%s/%s:%s" $redis_registry $redis_repository $redis_tag | quote }}
          imagePullPolicy: {{ $redis_pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
        {{- if .Values.telego.ngrok.enabled }}
        - name: ngrok
          image: {{ printf "%s/%s:%s" $ngrok_registry $ngrok_repository $ngrok_tag | quote }}
          imagePullPolicy: {{ $ngrok_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
                ngrok authtoken $(NGROK_AUTH) &&
                ngrok http 80 --bind-tls=true
          ports:
            - name: ngrok
              containerPort: 4040
              protocol: TCP
          env:
            - name: NGROK_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-telego-secret
                  key: NGROK_AUTH_TOKEN
        {{- end }}
      volumes:
        - name: {{ .Release.Name }}-telego-site-config
          configMap:
            name: {{ .Release.Name }}-telego-site-config
        {{- if $persistence }}
        - name: {{ .Release.Name }}-telego-logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-telego-logs-pvc
        {{- end }}
        {{- if .Values.telego.commands }}
        - name: {{ .Release.Name }}-telego-commands-cm
          configMap:
            name: {{ .Release.Name }}-telego-commands-cm
        {{- end }}
        {{- if .Values.telego.messages }}
        - name: {{ .Release.Name }}-telego-messages-cm
          configMap:
            name: {{ .Release.Name }}-telego-messages-cm
        {{- end }}
