# helm pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-telego-logs-pvc
  labels:
    {{- include "telego.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.logs.storage }}
  storageClassName: {{ .Values.pvc.logs.storageClassName }}
