apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telego-secret
  labels:
    {{- include "telego.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secret.telego.SECRET_KEY | b64enc }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secret.telego.TELEGRAM_BOT_TOKEN | b64enc }}
  NGROK_AUTH_TOKEN: {{ .Values.secret.telego.NGROK_AUTH_TOKEN | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telego-database-secret
  labels:
    {{- include "telego.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.database.DB_USER | b64enc }}
  DB_PASS: {{ .Values.secret.database.DB_PASS | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-telego-site-config
  labels:
    {{- include "telego.labels" . | nindent 4 }}
type: Opaque
data:
  site-config.conf: |-
    {{- include "telego.site-config" . | toString | b64enc | nindent 4 }}
