{{- $celery := .Values.telego.scheduler.celery }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telego-svc
  labels:
    {{- include "telego.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: telego
      protocol: TCP
      name: {{ .Release.Name }}-telego
    {{- if $celery }}
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: {{ .Release.Name }}-redis
    {{- end }}
  selector:
    {{- include "telego.selectorLabels" . | nindent 4 }}
