{{- $host := .Values.mariadb.host | default "mariadb" | toString }}
{{- $registry := .Values.image.mariadb.registry | default "docker.io" | toString }}
{{- $repository := .Values.image.mariadb.repository | default "bitnami/mariadb" | toString }}
{{- $tag := .Values.image.mariadb.tag | default .Chart.AppVersion | toString }}
{{- $pullPolicy := .Values.image.mariadb.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $create_mode := .Values.mariadb.mode.create }}
{{- $databases := .Values.mariadb.databases }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (index (splitList "." $host) 0) .Release.Name "mariadb-agent" }}
  labels:
    {{- include "mariadb-agent.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mariadb-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mariadb-agent
          image: {{ printf "%s/%s:%s" $registry $repository $tag | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if $create_mode }}
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              mysql -h $(DB_HOST) -u $(ROOT_USER) <<-EOSQL
                {{- range $databases }}
                CREATE DATABASE IF NOT EXISTS {{ .name }};
                CREATE USER IF NOT EXISTS '{{ .user }}'@'%';
                SET PASSWORD FOR '{{ .user }}'@'%' = PASSWORD('{{ .password }}');
                GRANT ALL PRIVILEGES ON {{ .name }}.* TO '{{ .user }}'@'%';
                {{- end }}
                FLUSH PRIVILEGES;
              EOSQL
          {{- else }}
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              mysql -h $(DB_HOST) -u $(ROOT_USER) <<-EOSQL
                {{- range $databases }}
                DROP DATABASE IF EXISTS {{ .name }};
                DROP USER IF EXISTS '{{ .user }}'@'%';
                {{- end }}
                FLUSH PRIVILEGES;
              EOSQL
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-mariadb-agent-secret
      restartPolicy: Never
