{{- $db_host := .Values.mariadb.host | toString | b64enc }}
{{- $db_name := .Values.mariadb.name | toString | b64enc }}
{{- $db_user := .Values.mariadb.user | toString | b64enc }}
{{- $db_password := .Values.mariadb.password | toString | b64enc }}
{{- $root_user := .Values.mariadb.root.user | default "root" | toString | b64enc }}
{{- $root_password := .Values.mariadb.root.password | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-agent-secret
  labels:
    {{- include "mariadb-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $db_host }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASS: {{ $db_password }}
  ROOT_USER: {{ $root_user }}
  ROOT_PASS: {{ $root_password }}
