{{- $db_host := .Values.mariadb.host | toString | b64enc }}
{{- $root_user := .Values.mariadb.root.user | default "root" | toString | b64enc }}
{{- $root_password := .Values.mariadb.root.password | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-agent-secret
  labels:
    {{- include "mariadb-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $db_host }}
  ROOT_USER: {{ $root_user }}
  MYSQL_PWD: {{ $root_password }}
