{{- $mariadbHost := .Values.mariadb.host | toString | b64enc }}
{{- $mariadbPort := .Values.mariadb.port | default "3306" | toString | b64enc }}
{{- $rootUser := .Values.mariadb.root.user | default "root" | toString | b64enc }}
{{- $rootPassword := .Values.mariadb.root.password | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-agent-secret
  labels:
    {{- include "mariadb-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $mariadbHost }}
  DB_PORT: {{ $mariadbPort }}
  ROOT_USER: {{ $rootUser }}
  MYSQL_PWD: {{ $rootPassword }}
