apiVersion: v2
name: borgmatic
description: Simple, configuration-driven backup software for servers and workstations.
type: application
version: 0.1.1
appVersion: "1.9.6"
keywords:
  - "borgmatic"
  - "backup"
  - "borg"
home: "https://torsion.org/borgmatic/"
icon: "https://torsion.org/borgmatic/static/borgmatic.png"
sources:
  - "https://github.com/borgmatic-collective/borgmatic"
  - "https://github.com/borgmatic-collective/docker-borgmatic"
  - "https://github.com/irfanhakim-as/charts"
maintainers:
  - name: "Irfan Hakim"
    email: "irfanhakim.as@yahoo.com"
    url: "https://github.com/irfanhakim-as"
