apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflared-tunnel-creds
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: |-
    {{- .Values.tunnel.file | toString | b64enc | nindent 4 }}
