{{- range $name, $job := .Values.borgmatic.configs }}
{{- $passphrase := $job.passphrase | default $.Values.borgmatic.global.passphrase | toString | b64enc }}
{{- $sshPrivateKey := $job.sshPrivateKey | default $.Values.borgmatic.global.sshPrivateKey | toString | b64enc }}
{{- $secrets := $job.secrets | default $.Values.borgmatic.global.secrets }}
{{- if or $passphrase $secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-borgmatic-{{ $name }}-secret
  labels:
    {{- include "borgmatic.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if $passphrase }}
  BORG_PASSPHRASE: {{ $passphrase }}
  {{- end }}
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | toString | b64enc }}
  {{- end }}
{{- end }}
{{- if $sshPrivateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-borgmatic-{{ $name }}-ssh-secret
  labels:
    {{- include "borgmatic.labels" $ | nindent 4 }}
type: Opaque
data:
  id: {{ $sshPrivateKey }}
{{- end }}
{{- end }}
