{{- $postgres_registry := .Values.image.postgres.registry | default "docker.io" | toString }}
{{- $postgres_repository := .Values.image.postgres.repository | default "bitnami/postgresql" | toString }}
{{- $postgres_tag := .Values.image.postgres.tag | default .Chart.AppVersion | toString }}
{{- $postgres_pullPolicy := .Values.image.postgres.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $databases := .Values.postgres.databases }}
{{- $postgresHost := .Values.postgres.host | default "postgres" | toString }}
{{- $rootDB := .Values.postgres.root.database | default "$(ROOT_USER)" | toString | quote }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (index (splitList "." $postgresHost) 0) .Release.Name "postgres-agent" }}
  labels:
    {{- include "postgres-agent.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres-agent
          image: {{ printf "%s/%s:%s" $postgres_registry $postgres_repository $postgres_tag | quote }}
          imagePullPolicy: {{ $postgres_pullPolicy }}
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
          command: ["/bin/bash"]
          args:
            - -c
            - >-
              psql -h $(DB_HOST) -U $(ROOT_USER) -d {{ $rootDB | quote }} <<EOF
            {{- range $databases }}
            {{- if .create }}
                CREATE USER {{ .user | quote }} WITH ENCRYPTED PASSWORD '{{ .password }}';
                CREATE DATABASE {{ .name | quote }};
                GRANT ALL ON DATABASE {{ .name | quote }} TO {{ .user | quote }};
                ALTER DATABASE {{ .name | quote }} OWNER TO {{ .user | quote }};
                GRANT USAGE, CREATE ON SCHEMA PUBLIC TO {{ .user | quote }};
            {{- end }}
            {{- if .drop }}
                DROP DATABASE IF EXISTS {{ .name | quote }};
                REVOKE ALL ON SCHEMA PUBLIC FROM {{ .user | quote }};
                DROP USER IF EXISTS {{ .user | quote }};
            {{- end }}
            {{- if and .custom .custom_command }}
                \connect {{ .name | quote }};
                {{- .custom_command | replace "$.name" .name | replace "$.user" .user | replace "$.password" .password | nindent 16 }}
                \connect {{ $rootDB | quote }};
            {{- end }}
            {{- end }}
              EOF
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres-agent-secret
      restartPolicy: Never
