{{- $db_host := .Values.postgres.host | toString | b64enc }}
{{- $root_user := .Values.postgres.root.user | default "postgres" | toString | b64enc }}
{{- $root_password := .Values.postgres.root.password | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-agent-secret
  labels:
    {{- include "postgres-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $db_host }}
  ROOT_USER: {{ $root_user }}
  PGPASSWORD: {{ $root_password }}
