{{- $db_host := .Values.postgres.host | toString | b64enc }}
{{- $db_name := .Values.postgres.name | toString | b64enc }}
{{- $db_user := .Values.postgres.user | toString | b64enc }}
{{- $db_password := .Values.postgres.password | toString | b64enc }}
{{- $root_user := .Values.postgres.root.user | default "root" | toString | b64enc }}
{{- $root_password := .Values.postgres.root.password | toString | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-agent-secret
  labels:
    {{- include "postgres-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $db_host }}
  DB_NAME: {{ $db_name }}
  DB_USER: {{ $db_user }}
  DB_PASS: {{ $db_password }}
  ROOT_USER: {{ $root_user }}
  ROOT_PASS: {{ $root_password }}
