{{- $postgresHost := .Values.postgres.host | toString | b64enc }}
{{- $rootUser := .Values.postgres.root.user | default "postgres" | toString | b64enc }}
{{- $rootPassword := .Values.postgres.root.password | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-agent-secret
  labels:
    {{- include "postgres-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ $postgresHost }}
  ROOT_USER: {{ $rootUser }}
  PGPASSWORD: {{ $rootPassword }}
