apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-agent-secret
  labels:
    {{- include "postgres-agent.labels" . | nindent 4 }}
type: Opaque
data:
  DB_HOST: {{ .Values.postgres.host | toString | b64enc }}
  DB_NAME: {{ .Values.postgres.name | toString | b64enc }}
  DB_USER: {{ .Values.postgres.user | toString | b64enc }}
  DB_PASS: {{ .Values.postgres.pass | toString | b64enc }}
  ROOT_USER: {{ .Values.postgres.root.user | toString | b64enc }}
  ROOT_PASS: {{ .Values.postgres.root.pass | toString | b64enc }}
