apiVersion: v2
name: CHART_NAME
description: A Helm chart for deploying CHART_NAME
type: application
version: 0.1.0
appVersion: 0.0.1
keywords:
  - CHART_NAME
home: https://github.com/irfanhakim-as/charts
icon: https://irfanhakim-as.github.io/charts/logos/CHART_NAME.png
sources:
  - https://github.com/irfanhakim-as/charts
maintainers:
  - name: Irfan Hakim
    email: irfanhakim.as@yahoo.com
    url: https://github.com/irfanhakim-as
