# Default values for CHART_NAME.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for CHART_NAME.
# Default: "1"
replicaCount: ""

# Container images used for CHART_NAME.
image:
  # CHART_NAME container image configurations.
  # Source: https://github.com/irfanhakim-as/CHART_NAME/pkgs/container/CHART_NAME
  CHART_NAME:
    # The registry where the CHART_NAME container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the CHART_NAME container image used.
    # Default: "CHART_NAME"
    repository: ""
    # The tag that specifies the version of the CHART_NAME container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the CHART_NAME container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Init container image configurations.
  # Source: https://hub.docker.com/_/busybox
  init:
    # The registry where the Init container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Init container image used.
    # Default: "busybox"
    repository: ""
    # The tag that specifies the version of the Init container image used.
    # Default: "1.36.1"
    tag: ""
    # The policy that determines when Kubernetes should pull the Init container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

# CHART_NAME configurations.
CHART_NAME:
  # The secret value of the CHART_NAME bar.
  # Default: "bar"
  # Example:
  # bar: "bar"
  bar: ""
  # The ingress domain name that hosts the CHART_NAME server.
  # Example:
  # domain: "chart_name.example.com"
  domain: ""
  # The value of the CHART_NAME foo.
  # Default: "foo"
  # Example:
  # foo: "foo"
  foo: ""

# Ingress configurations.
ingress:
  # Specifies whether Ingress should be enabled for hosting CHART_NAME services.
  # Example:
  # enabled: true
  enabled: false
  # The name of the cluster issuer for Ingress.
  # Default: "letsencrypt-dns-prod"
  clusterIssuer: ""

# Service configurations.
service:
  # The type of service used for CHART_NAME services.
  # Default: "ClusterIP"
  # Example:
  # type: "NodePort"
  type: ""

# Storage configurations.
storage:
  # Data storage configurations.
  data:
    # Specifies whether persistent storage should be provisioned for data storage.
    # Example:
    # enabled: false
    enabled: true
    # The path where the data storage should be mounted on the container.
    # Default: "/config"
    # Example:
    # mountPath: "/data"
    mountPath: ""
    # The subpath within the data storage to mount to the container. Leave empty if not required.
    # Example:
    # subPath: "Config"
    subPath: ""
    # The default amount of persistent storage allocated for the data storage.
    # Default: "1Gi"
    # Example:
    # storage: "10Gi"
    storage: ""
    # The storage class name used for dynamically provisioning a persistent volume for the data storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""

# Resource requirements and limits for CHART_NAME container.
resources:
  # CHART_NAME container resources.
  # Example:
  # CHART_NAME:
  #   # The minimum amount of resources required by CHART_NAME to run.
  #   requests:
  #     # The minimum amount of CPU resources required by CHART_NAME.
  #     # Example:
  #     # cpu: "10m"
  #     cpu: "10m"
  #     # The minimum amount of memory required by CHART_NAME.
  #     # Example:
  #     # memory: "10Mi"
  #     memory: "10Mi"
  #   # The maximum amount of resources allowed for CHART_NAME.
  #   limits:
  #     # The maximum amount of CPU resources allowed for CHART_NAME.
  #     # Example:
  #     # cpu: "250m"
  #     cpu: "250m"
  #     # The maximum amount of memory allowed for CHART_NAME.
  #     # Example:
  #     # memory: "250Mi"
  #     memory: "250Mi"
  CHART_NAME: {}
