# Default values for CHART_NAME.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  init:
    registry: docker.io
    repository: busybox
    tag: "1.34"
    pullPolicy: IfNotPresent
  
  CHART_NAME:
    registry: docker.io
    repository: CHART_NAME
    tag: "13.3"
    pullPolicy: IfNotPresent

configmap:
  CHART_NAME:
    FOO: "foo"

secret:
  CHART_NAME:
    BAR: "bar"

pvc:
  data:
    storage: "storage"
    storageClassName: "storageClassName"

resources:
  requests:
    cpu: "cpu"
    memory: "memory"
  limits:
    cpu: "cpu"
    memory: "memory"
