{{- $ingress := .Values.ingress.enabled }}
{{- $domain := .Values.wallabag.domain | toString | default "localhost" }}
{{- $domainName := "" }}
{{- if and $ingress (ne $domain "localhost") }}
{{- $domainName = printf "https://%s" $domain | toString | quote }}
{{- else }}
{{- $domainName = printf "http://%s" $domain | toString | quote }}
{{- end }}
{{- $name := .Values.wallabag.name | default "Wallabag" | toString | quote }}
{{- $foo := .Values.wallabag.foo | default "foo" | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wallabag-cm
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
data:
  DOMAIN_NAME: {{ $domainName }}
  FOO: {{ $foo }}
  SERVER_NAME: {{ $name }}
