{{- $domainName := "" }}
{{- $ingress := .Values.ingress.enabled }}
{{- $domain := .Values.wallabag.domain | toString | default "localhost" }}
{{- if and $ingress (ne $domain "localhost") }}
{{- $domainName = printf "https://%s" $domain | toString | quote }}
{{- else }}
{{- $domainName = printf "http://%s" $domain | toString | quote }}
{{- end }}
{{- $locale := .Values.wallabag.locale | default "en" | toString | quote }}
{{- $name := .Values.wallabag.name | default "Wallabag" | toString | quote }}
{{- $registration := .Values.wallabag.administration.registration | default "false" | toString | quote }}
{{- $verification := .Values.wallabag.administration.verification | default "false" | toString | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-wallabag-cm
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
data:
  SYMFONY__ENV__DOMAIN_NAME: {{ $domainName }}
  SYMFONY__ENV__FOSUSER_REGISTRATION: {{ $registration }}
  SYMFONY__ENV__FOSUSER_CONFIRMATION: {{ $verification }}
  SYMFONY__ENV__LOCALE: {{ $locale }}
  SYMFONY__ENV__SERVER_NAME: {{ $name }}
