{{- $externalRedis := .Values.redis.external }}
{{- $imagePersistence := .Values.storage.image.enabled }}
{{- $wallabag_registry := .Values.image.wallabag.registry | default "ghcr.io" | toString }}
{{- $wallabag_repository := .Values.image.wallabag.repository | default "wallabag/docker" | toString }}
{{- $wallabag_tag := .Values.image.wallabag.tag | default .Chart.AppVersion | toString }}
{{- $wallabag_pullPolicy := .Values.image.wallabag.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $redis_registry := .Values.image.redis.registry | default "docker.io" | toString }}
{{- $redis_repository := .Values.image.redis.repository | default "redis" | toString }}
{{- $redis_tag := .Values.image.redis.tag | default "6.0-alpine" | toString }}
{{- $redis_pullPolicy := .Values.image.redis.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $init_registry := .Values.image.init.registry | default "docker.io" | toString }}
{{- $init_repository := .Values.image.init.repository | default "busybox" | toString }}
{{- $init_tag := .Values.image.init.tag | default "1.36.1" | toString }}
{{- $init_pullPolicy := .Values.image.init.pullPolicy | default "IfNotPresent" | toString | quote }}
{{- $replica_count := .Values.replicaCount | default "1" | toString }}
{{- $imageMountPath := .Values.storage.image.mountPath | default "/var/www/wallabag/web/assets/images" | toString | quote }}
{{- $imageSubPath := .Values.storage.image.subPath | toString }}
{{- $initScript := .Values.wallabag.initScript | toString }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wallabag
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
spec:
  replicas: {{ int $replica_count }}
  selector:
    matchLabels:
      {{- include "wallabag.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wallabag.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $initScript }}
      initContainers:
        - name: init
          image: {{ printf "%s/%s:%s" $init_registry $init_repository $init_tag | quote }}
          imagePullPolicy: {{ $init_pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              {{- $initScript | nindent 14 }}
          {{- if or $imagePersistence }}
          volumeMounts:
            {{- if $imagePersistence }}
            - name: {{ .Release.Name }}-wallabag-image
              mountPath: {{ $imageMountPath }}
              {{- if $imageSubPath }}
              subPath: {{ $imageSubPath | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
      {{- end }}
      containers:
        - name: wallabag
          image: {{ printf "%s/%s:%s" $wallabag_registry $wallabag_repository $wallabag_tag | quote }}
          imagePullPolicy: {{ $wallabag_pullPolicy }}
          ports:
            - name: wallabag
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.wallabag | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-wallabag-cm
            - secretRef:
                name: {{ .Release.Name }}-wallabag-secret
            - secretRef:
                name: {{ .Release.Name }}-wallabag-redis-secret
          {{- if or $imagePersistence }}
          volumeMounts:
            {{- if $imagePersistence }}
            - name: {{ .Release.Name }}-wallabag-image
              mountPath: {{ $imageMountPath }}
              {{- if $imageSubPath }}
              subPath: {{ $imageSubPath | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- if not $externalRedis }}
        - name: redis
          image: {{ printf "%s/%s:%s" $redis_registry $redis_repository $redis_tag | quote }}
          imagePullPolicy: {{ $redis_pullPolicy }}
          # command: ["redis-server"]
          # args:
          #   - "--requirepass"
          #   - "$(REDIS_PASSWORD)"
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-wallabag-redis-secret
        {{- end }}
      {{- if or $imagePersistence }}
      volumes:
        {{- if $imagePersistence }}
        - name: {{ .Release.Name }}-wallabag-image
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wallabag-image-pvc
        {{- end }}
      {{- end }}
