{{- $imagePersistence := .Values.storage.image.enabled }}
{{- $imageAccessMode := .Values.storage.image.accessMode | default "ReadWriteMany" | toString | quote }}
{{- $imageStorage := .Values.storage.image.storage | default "1Gi" | toString | quote }}
{{- $imageStorageClassName := .Values.storage.image.storageClassName | default "longhorn" | toString | quote }}
{{- if $imagePersistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wallabag-image-pvc
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $imageAccessMode }}
  resources:
    requests:
      storage: {{ $imageStorage }}
  storageClassName: {{ $imageStorageClassName }}
{{- end }}
