{{- $secret := .Values.wallabag.secret | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallabag-secret
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET: {{ $secret }}
