{{- $redisHost := "" }}
{{- $redisPort := "" }}
{{- $redisPassword := "" }}
{{- $externalRedis := .Values.redis.external }}
{{- $db_type := printf "pdo_%s" (.Values.db.type | default "mysql") | toString | b64enc }}
{{- $db_name := .Values.db.name | toString | b64enc }}
{{- $db_user := .Values.db.user | toString | b64enc }}
{{- $db_password := .Values.db.password | toString | b64enc }}
{{- $db_host := .Values.db.host | toString | b64enc }}
{{- $db_port := .Values.db.port | default "3306" | toString | b64enc }}
{{- $name := .Values.wallabag.name | default "Wallabag" | toString }}
{{- $mailHost := .Values.mail.smtp.host | default "smtp.gmail.com" | toString }}
{{- $mailPort := .Values.mail.smtp.port | default "465" | toString }}
{{- $mailUser := .Values.mail.smtp.user | toString }}
{{- $mailPassword := .Values.mail.smtp.password | toString }}
{{- $mail2fa := .Values.mail.tfa_email | toString | b64enc }}
{{- $mailFrom := .Values.mail.from_email | default (printf "%s <%s>" $name $mailUser) | toString | b64enc }}
{{- if $externalRedis }}
  {{- $redisHost = .Values.redis.host | toString | b64enc }}
  {{- $redisPort = .Values.redis.port | default "6379" | toString | b64enc }}
  {{- $redisPassword = .Values.redis.password | toString | b64enc }}
{{- else }}
  {{- $redisHost = "localhost" | toString | b64enc }}
  {{- $redisPort = .Values.service.redis.port | default "6379" | toString | b64enc }}
{{- end }}
{{- $sentryDsn := .Values.wallabag.sentryDsn | toString | b64enc }}
{{- $secret := .Values.wallabag.secret | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallabag-secret
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  SYMFONY__ENV__DATABASE_CHARSET: {{ "utf8mb4" | toString | b64enc }}
  SYMFONY__ENV__DATABASE_TABLE_PREFIX: {{ "wallabag_" | toString | b64enc }}
  SYMFONY__ENV__DATABASE_DRIVER: {{ $db_type }}
  SYMFONY__ENV__DATABASE_NAME: {{ $db_name }}
  SYMFONY__ENV__DATABASE_USER: {{ $db_user }}
  SYMFONY__ENV__DATABASE_PASSWORD: {{ $db_password }}
  SYMFONY__ENV__DATABASE_HOST: {{ $db_host }}
  SYMFONY__ENV__DATABASE_PORT: {{ $db_port }}
  {{- if and $mailUser $mailPassword $mailHost $mailPort }}
  SYMFONY__ENV__MAILER_DSN: {{ printf "smtp://%s:%s@%s:%s" $mailUser $mailPassword $mailHost $mailPort | toString | b64enc }}
  {{- end }}
  SYMFONY__ENV__FROM_EMAIL: {{ $mailFrom }}
  SYMFONY__ENV__TWOFACTOR_SENDER: {{ $mail2fa }}
  SYMFONY__ENV__SECRET: {{ $secret }}
  {{- if $sentryDsn }}
  SYMFONY__ENV__SENTRY_DSN: ""
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wallabag-redis-secret
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_HOST: {{ $redisHost }}
  SYMFONY__ENV__REDIS_HOST: {{ $redisHost }}
  REDIS_PORT: {{ $redisPort }}
  SYMFONY__ENV__REDIS_PORT: {{ $redisPort }}
  {{- if and $externalRedis $redisPassword }}
  SYMFONY__ENV__REDIS_PASSWORD: {{ $redisPassword }}
  {{- end }}
  # REDIS_DB: ""
