{{- $nodePort := .Values.service.nodePort | toString }}
{{- $port := .Values.service.port | default "80" | toString }}
{{- $type := .Values.service.type | default "ClusterIP" | toString }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wallabag-svc
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ int $port }}
      targetPort: wallabag
      {{- if and (eq $type "NodePort") $nodePort }}
      nodePort: {{ int $nodePort }}
      {{- end }}
      protocol: TCP
      name: wallabag
  selector:
    {{- include "wallabag.selectorLabels" . | nindent 4 }}
