# Default values for clog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  clog:
    registry: ghcr.io
    repository: irfanhakim-as/clog
    tag: ""
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the clog image

configmap:
  clog:
    SITE_NAME: "Clog" # name of the clog site
    DEBUG: "False" # django debug mode
  
  postgres:
    DB_HOST: "postgres.default.svc.cluster.local" # remote postgres host
    DB_NAME: "clog-db" # clog postgres database name

secret:
  clog:
    SECRET_KEY: "secret" # django secret key
  
  postgres:
    DB_USER: "secret" # remote postgres user
    DB_PASS: "secret" # remote postgres user password

pvc:
  static:
    storage: "20Mi" # static files storage size
    storageClassName: "longhorn" # static files storage class name
  
  media:
    storage: "100Mi" # media files storage size
    storageClassName: "longhorn" # media files storage class name

  migrations:
    core:
      storage: "20Mi" # core migrations files storage size
      storageClassName: "longhorn" # core migrations files storage class name
    money:
      storage: "20Mi" # money migrations files storage size
      storageClassName: "longhorn" # money migrations files storage class name

resources:
  clog:
    requests:
      cpu: "10m" # clog cpu request
      memory: "10Mi" # clog memory request
    limits:
      cpu: "300m" # clog cpu limit
      memory: "300Mi" # clog memory limit
