# Default values for clog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The desired number of running replicas for Clog.
# Default: "1"
replicaCount: ""

# Container images used for Clog.
image:
  # Clog container image configurations.
  clog:
    # The registry where the Clog container image is hosted.
    # Default: "ghcr.io"
    registry: ""
    # The name of the repository that contains the Clog container image used.
    # Default: "irfanhakim-as/clog"
    repository: ""
    # The tag that specifies the version of the Clog container image used.
    # Default: Chart appVersion
    tag: ""
    # The policy that determines when Kubernetes should pull the Clog container image.
    # Default: "IfNotPresent"
    pullPolicy: ""
  # Ngrok container image configurations.
  ngrok:
    # The registry where the Ngrok container image is hosted.
    # Default: "docker.io"
    registry: ""
    # The name of the repository that contains the Ngrok container image used.
    # Default: "wernight/ngrok"
    repository: ""
    # The tag that specifies the version of the Ngrok container image used.
    # Default: "latest"
    tag: ""
    # The policy that determines when Kubernetes should pull the Ngrok container image.
    # Default: "IfNotPresent"
    pullPolicy: ""

# Credentials used to securely authenticate and authorise the pulling of container images from private registries.
# Example:
# imagePullSecrets:
#   - name: "ghcr-token-secret"
imagePullSecrets: []

clog:
  # The name of the Clog service.
  # Default: "Clog"
  # Example:
  # name: "Clog"
  name: "" 
  # Specifies whether Clog should run in debug mode.
  # Default: false
  # Example:
  # debug: true
  debug: "" 
  # A 50-character secret key used for secure session management and cryptographic operations within the Clog service.
  # Example:
  # secret: "6&p4%t)-$8a14fmfh92py8j55+us51r6%e52dzy&=a3-6yd4#e"
  secret: "" 
  # Clog storage persistence configurations.
  persistence:
    # Specifies whether Clog should persist its storage.
    # Example:
    # enabled: true
    enabled: false
    # The storage class name used for dynamically provisioning a persistent volume for the Clog storage.
    # Default: "longhorn"
    # Example:
    # storageClassName: "longhorn"
    storageClassName: ""
    # Clog static files persistence configurations.
    static:
      # The amount of persistent storage allocated for Clog static files.
      # Default: "50Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
    # Clog media files persistence configurations.
    media:
      # The amount of persistent storage allocated for Clog media files.
      # Default: "100Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
    # Clog logs persistence configurations.
    logs:
      # The amount of persistent storage allocated for Clog logs.
      # Default: "50Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
    # Clog migration files persistence configurations.
    migrations:
      # The amount of persistent storage allocated for Clog migration files.
      # Default: "20Mi"
      # Example:
      # storage: "1Gi"
      storage: ""
  # Clog Cloudflare configurations.
  cloudflared:
    # Specifies whether Clog should run using a Cloudflare tunnel.
    # Example:
    # enabled: true
    enabled: false
    # Registered domain name on Cloudflare used for Clog.
    # Example:
    # domain: "clog.example.com"
    domain: ""
  # Clog Ngrok configurations.
  ngrok:
    # Specifies whether Clog should run using an Ngrok tunnel.
    # Example:
    # enabled: true
    enabled: false
    # Ngrok authentication token.
    # Example:
    # token: "s7Ed4IO23nw1HWRJwumSgcyB7BtcXr4ZYLtziJCDDLIVDv7uq"
    token: ""

# Database configurations.
db:
  # The type of the database used by Clog.
  # Default: "postgresql"
  # Example:
  # type: "postgresql"
  type: ""
  # The name of the database used by Clog.
  # Example:
  # name: "clog"
  name: ""
  # The username or user account for accessing the Clog database.
  # Example:
  # user: "root"
  user: ""
  # The password associated with the Clog database's user.
  # Example:
  # password: "password"
  password: ""
  # The hostname or IP address of the Clog database server.
  # Example:
  # host: "clog.default.svc.cluster.local"
  host: ""
  # The port number on which the Clog database server is listening.
  # Default: "5432"
  # Example:
  # port: "5432"
  port: ""

# Resource requirements and limits for Clog containers.
resources:
  # Clog container resources.
  clog:
    # The minimum amount of resources required by Clog to run.
    requests:
      # The minimum amount of CPU resources required by Clog.
      # Example:
      # cpu: "20m"
      cpu: "10m"
      # The minimum amount of memory required by Clog.
      # Example:
      # memory: "250Mi"
      memory: "100Mi"
    # The maximum amount of resources allowed for Clog.
    limits:
      # The maximum amount of CPU resources allowed for Clog.
      # Example:
      # cpu: "50m"
      cpu: "50m"
      # The maximum amount of memory allowed for Clog.
      # Example:
      # memory: "450Mi"
      memory: "200Mi"
