# Default values for clog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  clog:
    registry: ghcr.io
    repository: irfanhakim-as/clog
    tag: ""
    pullPolicy: IfNotPresent
  
  ngrok:
    registry: docker.io
    repository: wernight/ngrok
    tag: "latest"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-token-secret # name of the secret containing the token to access the clog image

clog:
  site_name: "Clog" # name of the clog site
  debug: "False" # django debug mode
  secret: "" # django secret key
  ngrok_auth_token: "" # ngrok auth token

db:
  host: "postgres.default.svc.cluster.local" # remote postgres host
  name: "" # remote postgres database name
  user: "" # remote postgres database user
  pass: "" # remote postgres database user password

pvc:
  static:
    storage: "50Mi" # static files storage size
    storageClassName: "longhorn" # static files storage class name
  
  media:
    storage: "100Mi" # media files storage size
    storageClassName: "longhorn" # media files storage class name

  logs:
    storage: "50Mi" # logs files storage size
    storageClassName: "longhorn" # logs files storage class name

  migrations:
    core:
      storage: "20Mi" # core migrations files storage size
      storageClassName: "longhorn" # core migrations files storage class name
    money:
      storage: "20Mi" # money migrations files storage size
      storageClassName: "longhorn" # money migrations files storage class name

resources:
  clog:
    requests:
      cpu: "10m" # clog cpu request
      memory: "10Mi" # clog memory request
    limits:
      cpu: "300m" # clog cpu limit
      memory: "300Mi" # clog memory limit
