# Default values for postgres-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  postgres:
    registry: docker.io
    repository: postgres
    tag: ""
    pullPolicy: IfNotPresent

postgres:
  # agent mode
  mode:
    create: true
    drop: false
  # postgres host
  host: "postgres.default.svc.cluster.local"
  # postgres database name
  name: ""
  # postgres database user
  user: ""
  # postgres database user password
  pass: ""
  # root postgres user
  root: ""
  # root postgres user password
  root_pass: ""
